### ISSUE TITLE
sar doesnt start while running pbench_fio

### ISSUE THREAD

**Issue by psuriset** [distributed-system-analysis/pbench#100]
sar doesnt start while running pbench_fio  some of the cases.  While these tests in progress i checked for sar on machine. its not started. so it fails to kill once test done.  Its inconsistent.  some cases it works fine.  

Failed tests: 

1) 
running fio job: /var/lib/pbench-agent/fio_single-vm-ext4-cache:none-io:native-disk:hdd-img:qcow2-preallocate:falloc-fs:ext4-iodepth-1-jobs-32-ioeng:sync-profile:throughput-without-perf-full-run-with-stefan-rhel72-patch-ag-vcpu-2-run:1_2015-10-30_04:16:18/7-write-16384KiB/sample5/fio.job
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (36157) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (30111) - No such process
Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-84]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-84]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
fio job complete

2) 
running fio job: /var/lib/pbench-agent/fio_single-vm-ext4-cache:none-io:native-disk:hdd-img:qcow2-preallocate:falloc-fs:ext4-iodepth-1-jobs-32-ioeng:sync-profile:throughput-without-perf-full-run-with-stefan-rhel72-patch-ag-vcpu-2-run:1_2015-10-30_04:16:18/12-read-1024KiB/sample1/fio.job

/opt/pbench-agent/tool-scripts/sar: line 168: kill: (3450) - No such process

/opt/pbench-agent/tool-scripts/sar: line 168: kill: (12532) - No such process

Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.

[virbr0-122-84]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-84]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.

fio job complete

3) running fio job: /var/lib/pbench-agent/fio_single-vm-ext4-cache:none-io:native-disk:hdd-img:qcow2-preallocate:falloc-fs:ext4-iodepth-1-jobs-32-ioeng:sync-profile:throughput-without-perf-full-run-with-stefan-rhel72-patch-ag-vcpu-2-run:1_2015-10-30_04:16:18/12-read-1024KiB/sample2/fio.job

/opt/pbench-agent/tool-scripts/sar: line 168: kill: (6283) - No such process

/opt/pbench-agent/tool-scripts/sar: line 168: kill: (13982) - No such process

Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.

[virbr0-122-84]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-84]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.

fio job complete
The following jobfile was created: /var/lib/pbench-agent/fio_single-vm-ext4-cache:none-io:native-disk:hdd-img:qcow2-preallocate:falloc-fs:ext4-iodepth-1-jobs-32-ioeng:sync-profile:throughput-without-perf-full-run-with-stefan-rhel72-patch-ag-vcpu-2-run:1_2015-10-30_04:16:18/12-read-1024KiB/sample3/fio.job

4) running fio job: /var/lib/pbench-agent/fio_single-vm-ext4-cache:none-io:native-disk:hdd-img:qcow2-preallocate:falloc-fs:ext4-iodepth-1-jobs-32-ioeng:sync-profile:throughput-without-perf-full-run-with-stefan-rhel72-patch-ag-vcpu-2-run:1_2015-10-30_04:16:18/12-read-1024KiB/sample3/fio.job

/opt/pbench-agent/tool-scripts/sar: line 168: kill: (9006) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (15615) - No such process

Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.

[virbr0-122-84]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-84]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.

fio job complete

**Comment by psuriset** [comment]
This is noticed while running fio on kvm VM's . 
both with single vm, multi vm..

**Comment by ashishkamra** [comment]
Closing. Re-open if seen again.
