### ISSUE TITLE
multiple concurrent jobs with pbench-fio

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#1004]
In `pbench-fio`, the value of max-jobs appears to be determined by $targets but that does not seem correct. As it stands max-jobs is always 1 when I set either 'directory' OR 'filename' to multiple colon separated items and set numjobs to >1. Given that, max-jobs ensures that only one file is written. $targets is used to line up multiple jobs sequentially, turning the multiple colon separated items into multiple job stanzas in the jobfile. I modified lines 590 & 604 in pbench-fio to remove --max-jobs from the assembled client_opts string which allowed me to achieve the objective of parallel writes and reads.

**Comment by portante** [comment]
This behavior appears to have been fixed by #1224.
