### ISSUE TITLE
postprocessing - generate data in parallel manner

### ISSUE THREAD

**Issue by mrsiano** [distributed-system-analysis/pbench#1018]
In continuing to #1015 and #700 
as a short term solution, we try to parse data in chunks in order to avoid any oom kills.
chunking data make the pp execution time to be quite longer.
in order to speed up the process we should call the gen_data by another thread in order to support parallelism.

at the same time we should make sure the pidstat collection is synced when calling gen_data.

@atheurer @portante

**Comment by portante** [comment]
Closing this bug because the post-processing step appears to run all the tool post-processing, see #1023.
