### ISSUE TITLE
pbench graph shows 1970 on time axis

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#1021]
some of us are still using pbench graphs, recently I saw 1970 in the time axis for at least one graph, not sure when this started happening.

**Comment by bengland2** [comment]
Here's [an example](http://pbench.perf.lab.eng.bos.redhat.com/results/b06-h31-1029p/fio-glusterblock-hdd-1strun25G/fio_glusterblock-HDD-25GBper-pod-write_randread_2019.01.02T19.12.24/4-randread-4KiB/sample1/fio.html)  from Elko Kuric's dataset collected recently in the scale lab.

**Comment by portante** [comment]
@bengland2, that URL is internal to Red Hat, can you post an example image that is publicly accessible?

**Comment by bengland2** [comment]
[fio 1970 X-axis example](https://github.com/distributed-system-analysis/pbench/files/2739221/fio-1970-x-axis.pdf) - I printed the graph to a PDF and uploaded that so now everyone has it.
