### ISSUE TITLE
iostat and perf prematurelly die when running inside pod on Openshift v3

### ISSUE THREAD

**Issue by ekuric** [distributed-system-analysis/pbench#103]
running pbench_fio inside pod on OSE v3 and once job ends it does not collect iostat / perf data.
Error message as showed below 

The following jobfile was created: /var/lib/pbench-agent/fio_12E_2015-11-05_09:52:44/2-read-64KiB/sample2/fio.job
[global]
bs=64k
ioengine=libaio
iodepth=32
direct=1
sync=0
time_based=1
runtime=30
clocksource=gettimeofday
ramp_time=5
[job1]
rw=read
filename=/var/lib/docker/fiotest/fiotest
size=4096M
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
log_avg_msec=1000
running fio job: /var/lib/pbench-agent/fio_12E_2015-11-05_09:52:44/2-read-64KiB/sample2/fio.job
/opt/pbench-agent/tool-scripts/iostat: line 168: kill: (1456) - No such process
/opt/pbench-agent/tool-scripts/perf: line 139: kill: (1705) - No such process
fio job complete
The following jobfile was created: /var/lib/pbench-agent/fio_12E_2015-11-05_09:52:44/2-read-64KiB/sample3/fio.job

**Comment by atheurer** [comment]
We will probably need to ensure we capture stderr when running these to see if there's an error.  I'll add that to all of the tools soon.

**Comment by ekuric** [comment]
@atheurer ping back if you want me to do more tests.I have OSE v3. environment.

**Comment by ashishkamra** [comment]
Closing. Re-open if reproduced.
