### ISSUE TITLE
Rename pbench dashboard from "PDash" to "Pbench Dashboard"

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1031]
Can we rename the v0.4 pbench dashboard from "PDash" to "Pbench Dashboard"?

**Comment by gurbirkalsi** [comment]
Created the following pull request to resolve this issue: [https://github.com/distributed-system-analysis/pbench/pull/1033](https://github.com/distributed-system-analysis/pbench/pull/1033)

**Comment by gurbirkalsi** [comment]
Closing issue as this has been resolved and merged with #1033
