### ISSUE TITLE
Replace file system hierarchy view with a React-based tree visualizer

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1038]
See https://reactjsexample.com/a-simple-and-configurable-tree-view-control-for-react/

Instead of visualizing a pbench results tree via walking the file system on the web server, let's consider using the indexed table of contents of a tar ball and displaying it using "react-animated-tree".

Once we can load and display the data in the tree, we can then create the same jschart views that exist today without the use of the pre-generated `.html` files.

**Comment by portante** [comment]
@gurbirkalsi, can you and @Anisha1234 comment on what it would take to do this work?

**Comment by gurbirkalsi** [comment]
@portante Hi Peter, according to the `react-animated-tree` documentation, we would need to have an understanding of the tree structure and translate that understanding to the appropriate nested levels using the `<Tree>` tag. 

We can stand this application up using a simple React scaffolding with create-react-app: [https://github.com/facebook/create-react-app](https://github.com/facebook/create-react-app)

Are we planning to make the pbench results tree data available via the elasticsearch API?

**Comment by portante** [comment]
@gurbirkalsi, it is already available.

**Comment by gurbirkalsi** [comment]
@portante Do we have documentation available on how this is indexed and where I can fetch this information from within the index?

**Comment by portante** [comment]
We don't have official documentation that one would read, but we do have a mapping file that describes the TOC entires: https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/lib/mappings/run-toc-entry.json
