### ISSUE TITLE
Move tool triggers into tools-$group directory

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1050]
We really can't use multiple tool triggers from different groups at the same time.  Only one group of tools is in effect for a pbench benchmark.

So instead of having a `/var/lib/pbench-agent/tool-triggers`, we should consider moving this to the tool group directory as, `/var/lib/pbench-agent/tool-${group}/_triggers_`.

**Comment by portante** [comment]
@atheurer, what do you think?

**Comment by atheurer** [comment]
Actually for pbench-trafficgen I have a version which used two different tool groups, so I’d like to preserve that feature. Is there a technical reason having more than one tool group can’t work?  Do t you just need to register triggers for more than one group?

**Comment by portante** [comment]
Well, we'll need to track the iteration per group and generate a result dir per iteration per group.  You can see in the new `pbench-tool-trigger` that it is passed the initial iteration to use, and the run dir to use, so it is possible.

I'll take a stab at that.

**Comment by atheurer** [comment]
FWIW, I think the iteration stuff might be able to be handled differently with the CDM work, as we will have 'periods' per 'sample', and creating a new iteration for each event might be able to be replaced with a different period.  At the moment, I think SPECjbb is the only benchmark with triggers a tool[-group] on/off more than once.  I would be fine with not supporting multiple iterations per tool-group for now, and reimplementing that support as multiple periods, and only starting/stopping tools once per tool-group.

**Comment by portante** [comment]
This was implemented in commit 23cc097e2, PR #1248, and released publicly with v0.71.
