### ISSUE TITLE
RFE: Allow quick comparison of results filtered by Iteration Filters

### ISSUE THREAD

**Issue by smalleni** [distributed-system-analysis/pbench#1062]
Currently, when comparing results, we are able to use "Compare All Iterations" or "Compare Selected Iterations". 
![image](https://user-images.githubusercontent.com/11049799/52081340-04457c80-2568-11e9-8889-832479242b94.png)

However, after filtering the results using iteration filters, there is no easy way to compare all the results that match the iteration filter. User needs to go and select each Iteration that they want to compare.
![image](https://user-images.githubusercontent.com/11049799/52081387-22ab7800-2568-11e9-8296-8e87e31dbbeb.png)

 It would be good to have a way to use the "Compare Selected Iterations" option to quickly compare all the results obtained by using iteration filter. Maybe provide a checkbox to select all the iterations outputted the current iteration filter, so that  "Compare Selected Iterations" button can be used.

**Comment by gurbirkalsi** [comment]
Thanks for the feedback @smalleni! In addition to the suggestion you offered above, iteration selection will be soon improved by taking advantage of a docked modal in the page so the user can scroll and reference iterations as they make selections.

**Comment by gurbirkalsi** [comment]
This issue has been resolve with PR #1165
