### ISSUE TITLE
Update pbench-sysstat, pbench-uperf, pbench-fio to latest upstream.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1070]
Current versions used in pbench vs. what's available upstream at the current time:

- [ ] `fio`: 3.12 vs 3.12
- [ ] `uperf`: 1.0.4 vs 1.0.6
- [ ] `sysstat`: 11.2.0 vs 12.0.3

COPR builds of `uperf` and `sysstat` have succeeded on everything but F29 - the F29 failures are under investigation.

**Comment by portante** [comment]
For `sysstat` upgrade from 11.2.0 to 12.0.3, we have the following issues:

 * `pidstat` output now includes two new columns: `%wait` and `iodelay`
 * `iostat` output now includes additional columns and the columns have been rearranged

An investigation of `sar` output is underway.  `mpstat` output has not changed.

**Comment by portante** [comment]
First, the `sysstat` support was updated with PR #1133 in `pbench-agent` `v0.58`.

Since then, we now support minimum versions of `fio` and `uperf`.

However, we do not maintain packaging mechanisms for `fio` and `uperf` in this repository, so we can close this.
