### ISSUE TITLE
Use pbench-configtools instead of configtools

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1076]
We should have a pbench-specific package for configtools instead of using the same package name, but slightly different implementation of configtools.  Using the same package name leads to confusion (the assumption is that it is the same as regular configtools).  This is the method we follow for other packages which we require and we modify, like pbench-sysstat.  Along with a pbench-configtools, getconf.py should change to pbench-getconf.py, and calls to pbench-getconf.py should have full path, like "/usr/local/bin/pbench-getconf.py" instead of no path at all, like we have now,

**Comment by riya-17** [comment]
@ndokos @portante I think this issue will be resolved after merging configtools with Pbench.

**Comment by portante** [comment]
Fixed by #1457.
