### ISSUE TITLE
It appears that perf data is not being collected properly with the 0.56 release

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1081]
We have a report from a user that the `perf` tool is apparently not collecting data correctly, showing only routines in the perf tool itself.

More investigation needed.

**Comment by atheurer** [comment]
Is this on 0.56 only?

**Comment by portante** [comment]
Unfortunately ... no.

It appears `pbench-trafficgen` has not been using `pbench-metadata-log` properly since it was created.

**Comment by portante** [comment]
Ah, strike that, answered thinking it was the `trafficgen` issue.

As far as I know, it is only with 0.56.  But still waiting to debug the environment from which the report came.

**Comment by portante** [comment]
Not seeing this showing up in my own testing as a problem.  Closing for now, we can re-open if somebody finds an issue.
