### ISSUE TITLE
pbench-tool-trigger should not use 'reference-result', should require sample dir

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1093]
The utility pbench-tool-trigger tries to use $iteration_dir/reference-result/$tool_group when calling start/stop tools, but this directory is not correct.  It works for some benchmarks like pbench-user-benchmark, but not most others, which do not create that directory (actually a symlink) until after the iteration is complete.  Three things need to change:

1) pbench-user-benchmark, and any other benchmark script which does not handle multiple samples,  should use "1" as the sample number for their bench/iteration/sample dir.
2) pbench-tool-trigger should require a sample number in its arguments and use "sample$num" as the directory (passed to start/stop-tools) instead of 'reference-result'

**Comment by portante** [comment]
@atheurer, I'll fix this.

**Comment by atheurer** [comment]
I have some patches for this that I used to get me by, I'll post them soon.

**Comment by portante** [comment]
@atheurer, posted PR #1094.
