### ISSUE TITLE
Setup integration with TravisCI for the individual unit tests

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#11]
We have existing unit tests which we could setup with TravisCI to run automatically on each commit.

**Comment by arcolife** [comment]
@portante need to enable this hook from settings of this repository at https://travis-ci.org/profile/distributed-system-analysis (which I can't since I don't own the repo) ..and then include a .travis.yml with the commands for unit test file. Could you enable the hook? Thanks!

**Comment by portante** [comment]
I enabled that hook.  When we post a .travis.yml file the builds will start working.

**Comment by portante** [comment]
Completed by #66.
