### ISSUE TITLE
JSON files under ./agent/config/benchmark are not included in pbench-agent package

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1102]
We expect these files to reside there:
https://github.com/distributed-system-analysis/pbench/tree/master/agent/config/benchmark

However, after installation of pbench-agent, there is a filename, "benchmark" instead of a directory.

**Comment by ndokos** [comment]
Fixed the spec file to install i/opt/pbench-agent/config/benchmark as a directory and built new RPM with verston 0.56-2g94965f79. This should resolve the problem. Closing this issue but if there is still a problem, please reopen it. Thanks!

**Comment by portante** [comment]
This was a packaging issue which we don't cover in the upstream issue.
