### ISSUE TITLE
BenchPostprocess: don't create timeseries array if empty when creating a aggregation

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1123]
An aggregation metric is composed of multiple other metrics, and usually we create an aggregate time series.  However, there are times where the time series from other metrics do not exist, or their time domains don't overlap.  If that time series is not populated, the default value for 'timeseries' is assigned "all" in error instead of an array of time series data or just an empty array.

**Comment by atheurer** [comment]
I have code to fix this

**Comment by portante** [comment]
Likely subsumed by #2953.
