### ISSUE TITLE
Postprocessing pbench-run-benchmark run generates wrong links in summary page

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1140]
`pbench-run-benchmark` seems to generate 0-based iteration and sample directories with names like `./iteration-0/sample0`. However, the `result.html` file contains links like this: `./0-/sample1`.

**Comment by portante** [comment]
The `pbench-run-benchmark` interface is deprecated as of the v0.71 release.  No further work will be done towards this issue.
