### ISSUE TITLE
Move to JSON::XS module

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1151]
This is related to issue https://github.com/distributed-system-analysis/pbench/issues/895 and in general we need to move to a much faster JSON library, which XS provides.  However, this library is included (as an RPM) in EPEL, not in the base OS repo, so I would suggest we bundle this perl module ourselves in our pbench-agent RPM, just like we have already done with SigFigs.pm.  Also, since we have a standard "lib" directory under pbench-agent now, I would prefer we keep this module and others there, instead of either ./bench-scripts/postprocess or ./tool-scripts/postprocess.

**Comment by atheurer** [comment]
Since @ndokos handled bundling SigFigs.pm in pbench-agent, I am assigning him to this issue.  I can certainly provide the changes to the perl scripts which will need to use the new function calls, but I would like @ndokos to handle the RPM sausage-making to include the perl module.

**Comment by portante** [comment]
Also the core reason for the problem filed in #1016.

**Comment by portante** [comment]
Closing in favor of #895 to track, since that has the history of how it was initially added to pbench-agent.
