### ISSUE TITLE
Selecting a result pushes the selection out from under the mouse causing confusion to the user

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1156]
If I have a result I am going to select:

![PbenchSelectionShiftBefore-20190402](https://user-images.githubusercontent.com/949097/55423243-7ed04f80-554b-11e9-9966-10d61a748cd9.png)

And then I select that entry, the entire window shifts down, and my mouse is no longer over the original selection:

![PbenchSelectionShiftAfter-20190402](https://user-images.githubusercontent.com/949097/55423504-07e78680-554c-11e9-997b-cb4001d8fe58.png)

Can we fix this so that the window does not shift down?

**Comment by gurbirkalsi** [comment]
@portante This has been resolved with PR #1130 as we created a new component which includes a static button and text at the top of the table in order to maintain the page position.

**Comment by portante** [comment]
Fixed by #1130.
