### ISSUE TITLE
"general and lsbrelease plugin is missing" reported by sosreport on f28, f29, rhel7, and rhel8 machines

### ISSUE THREAD

**Issue by tenstormavi** [distributed-system-analysis/pbench#1161]
While trying to run user benchmark got an error: "[pbench-sysinfo-dump]sosreport collection failed!". While on further digging got to know that sosreport was complaining about missing plugins.

**Comment by ndokos** [comment]
sosreport 3.6 (which seems to be the version in current RHEL and current Fedora) has reorganized some plugins: see https://github.com/sosreport/sos/pull/1177 for details. For now, we get no sosreports in the pbench outputs.
