### ISSUE TITLE
Is moongen obsolete?

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1183]
I don't see any results since 2017: should we get rid of `pbench-moongen`?

**Comment by atheurer** [comment]
I don't know of anyone using it anymore.  I would be OK with removing it.

**Comment by k-rister** [comment]
Agreed.  Do we just need a PR that removes the file from the tree?

**Comment by k-rister** [comment]
I created a PR (#1190) to add a deprecation message to pbench-moongen.  Following the release of v0.60 I plan on submitting an aditional patch targeted at release v0.61 which removes pbench-moongen entirely.

**Comment by portante** [comment]
Moving to milestone 0.61 for final deprecation.
