### ISSUE TITLE
dashboard comparison of fio runs uses incorrect metric

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#1208]
When a comparison of pbench-fio produced data is made using the dashboard it is labeled as using the iops_sec metric but the data that is displayed is actually from the clat metric.

**Comment by Anisha1234** [comment]
@k-rister I went through the issue and tried to regenerate the same. The pbench-fio produced data is labeled as iops_sec but when I inspected for the data fetched from the server, I couldn't find any clat metric data. the primary_metric name was  iops_sec only. I also compared the mean of the data and those also seemed to be correct. Can you please help me understand the issue better here.

**Comment by k-rister** [comment]
![image](https://user-images.githubusercontent.com/15911116/62942590-3ac54500-bd9e-11e9-9dc2-c8883b7f95d3.png)

This result shows 11610 IOPs, but when you look at the actual data that is the CLAT metric:

![image](https://user-images.githubusercontent.com/15911116/62942693-73fdb500-bd9e-11e9-84d4-69d8773149a8.png)

You are correct that the primary_metric is set to iops_sec, but it is like it is completely ignoring that.  The JSON file for this particular result has clat data right at the beginning:

![image](https://user-images.githubusercontent.com/15911116/62943042-2d5c8a80-bd9f-11e9-8344-1baf4d1aa735.png)

So I don't know if it is just picking up the first metric that it finds or what.

Additionally, when generating these screen captures I tried to pick all the 4KiB results (read, write, randread, and randwrite) and the dashboard continuously only rendered the read result when I did this and I tried several different times and different results.

**Comment by atheurer** [comment]
This also affects all uperf "rr" (request-response) tests, where there are two metrics, transactions/sec (the primary) and latency.  When I checked this with multiple comparisons and multiple pbench resulrs, these RR results in a bar-chart comparison are always incorrect, claiming to show transactions/sec but actually using values from latency.  Latency values are usually the inverse of transactions, so the opposite impression will be made from these graphs.  So, a warning to anyone who has been sharing comparisons for "rr" tests in uperf, all of that is probably incorrect, and you may need to inform whoever you shared this with that the data and/or conclusions made are false.

**Comment by k-rister** [comment]
This means that 2 of the 3 valid use cases for the dashboard are currently broken (fio and uperf rr) in production until the fix is deployed which means that users will be getting incorrect results, often times the exact opposite of what the real result is (since latency and throughput tend to be inverse of each other).

**Comment by Anisha1234** [comment]
@atheurer @k-rister the modifications made for correct rendering of fio data in PR #1318 should solve the case for uperf data as well. I tried to test the result of uperf "rr" (request-response) tests against the json data as well the bar graph and it seems to render perfectly for me. 
![Comp-select (1)](https://user-images.githubusercontent.com/16955978/64519123-26c72180-d311-11e9-8831-258948ddfbe7.png)
![comp](https://user-images.githubusercontent.com/16955978/64519126-275fb800-d311-11e9-89a6-d474615b407d.png)
Please let me know if I am missing something here.

**Comment by atheurer** [comment]
Thanks, @Anisha1234 it looks good to me.  Do we know when this will land in internal production infrastructure?

**Comment by portante** [comment]
We are working on deploying this to staging this week, hopefully to production late this week or early next.
