### ISSUE TITLE
pbench-fio: make-fio-jobfile.py can only parse default args bs & rw in jfio job templates.

### ISSUE THREAD

**Issue by jtudelag** [distributed-system-analysis/pbench#1215]
When using any other arg, apart from the default ones bs & rw, in a fio job template, [make-fio-jobfile.py](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/templates/make-fio-jobfile.py) fails to generate the fio file, with a `KeyError: 'runtime'` error.

The problem is the function [replace_val](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/templates/make-fio-jobfile.py#L84).

It receives 3 parameters, [def replace_val(dct, magic, delta)](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/templates/make-fio-jobfile.py#L120).

Here it is an output of the three:

dct:
```
OrderedDict([('__name__', 'global'), 
	     ('ioengine', 'libaio'), 
             ('runtime', '$@'), 
             ('bs', '$@'), 
             ('numjobs', '1'), 
             ('direct', '0'), 
             ('sync', '0'), 
             ('buffered', '1'), 
             ('norandommap', None), 
             ('randrepeat', '0'), 
             ('invalidate', '0'), 
             ('time_based', '0'), 
             ('ramp_time', '3')])
```
delta:
```
{'rw': 'write', 'bs': '1024k'}
```
magic
```
$@
```
Also the keys, although not a parameter:
```
['__name__', 'ioengine', 'runtime', 'bs', 'numjobs', 'direct', 'sync', 'buffered', 'norandommap', 'randrepeat', 'invalidate', 'time_based', 'ramp_time']
```
The problem is that the `delta` dict, only contains the default parameters `rw` & `bs`, instead of the dict of all of them.

The thing is that the rest of the command lines are parsed a few lines below the `replace_val` function:

https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/templates/make-fio-jobfile.py#L123

I just commented out [replace_val](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/templates/make-fio-jobfile.py#L120) and now my fio jobs are being generated correctly.

To reproduce, run this command with the following test fio job template:
```
/opt/pbench-agent/bench-scripts/templates/make-fio-jobfile.py -j /tmp/fio-test/files/fio-jobs/ko.job -bs=1024k -rw=write -ioengine= -iodepth= -direct= -sync= -runtime=30 -ramptime= -size= -rate_iops= -log_hist_msec=10000 -numjobs= -targets /var/lib/fio/fiotest.out 
```

Fio job template. Last line with 'runtime = $@', is the one generating the error:
```
[global]
ioengine=libaio
bs = $@
numjobs=1
direct=0
sync=0
buffered=1
numjobs=1
norandommap
randrepeat=0
invalidate=0
time_based = 0
ramp_time=3

[precondition-job]
filename = $target
rw = $@
runtime = $@
```

**Comment by jtudelag** [comment]
So unless there is a corner case I'm not seeing, I would get rid of the replace_val function entirely. I dont think is neeed.

**Comment by portante** [comment]
The use of the `$@` is for internal behavior.  All other key values are replaced with the command line values.

If you change the last line to `runtime = 5` you'll get a properly generated output file with `runtime = 30`.
