### ISSUE TITLE
Stop using `firewall-cmd` in `pbench-fio`

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1217]
Today, `pbench-fio` changes a remote system as a side-effect of executing.

Why not require the caller to open the port in their environment before running `pbench-fio`?

And we don't restore the port state any where, it seems, so it might be best to leave this to the caller of `pbench-fio` to make sure the proper port is opened.

Arguably we should document this behavioral need as well.

**Comment by k-rister** [comment]
Isn't this exactly the kind of thing one might expect an automation harness to take care of for the users?

That said, I absolutely think that it should leave the system in the state that it found it -- so if changes are made during execution they should removed upon completion.

**Comment by portante** [comment]
> Isn't this exactly the kind of thing one might expect an automation harness to take care of for the users?

Making changes to the state of the system to run a benchmark should be left to the user to when automating the running the benchmark via the pbench-agent framework.  The benchmark execution framework does not have the ability to be told the right thing to do in all cases, and, following the principal of separation of concerns, some other automation should take care of that.
