### ISSUE TITLE
Dependencies issues in server installation ansible playbooks

### ISSUE THREAD

**Issue by tenstormavi** [distributed-system-analysis/pbench#1218]
Dependencies issues must be resolved before running server installation ansible playbooks and roles i.e PR #1199 

Some of the dependencies which are found while testing the playbooks:
1. `geerlingguy.apache` needs to be installed using ansible galaxy. 
2. If the user wants to use python2 interpreter for running the playbooks then `python2-dnf` and for python3 `python3-dnf`, needs to be installed on the target host.
3. `python3-firewall` needs to be installed on target hosts. But the problem is if the user wants to use python2 interpreter for the playbooks, then it requires `pyhton2-firewall` which seems to be deprecated after Fedora 27. In RHEL7 the package name is `python-firewall` and RHEL8 it is `python3-firewall`. 

It is not clear now how we gonna approach this problem but we can suggest the user to use python3 interpreter for the playbooks, for systems like Fedora and RHEL8. For RHEL7 we can put instructions in README section.

**Comment by ndokos** [comment]
Fixed with the latest commit to #1199. Let me know if you see any more problems. Note that the RHEL8 RPM had (other) dependency problems which are now fixed.
