### ISSUE TITLE
sysstat tools do not check what version is installed

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1223]
The version is checked if `pbench-register-tool` is invoked because it calls the corresponding tool script with `--install` whcih checks the RPM version and updates if necessary. But if somebody has an old version installed and does not run `pbench-register-tool` (presumably because they did that a long time ago and are happy with the tools they installed), nobody checks that the version is invalid.

**Comment by ndokos** [comment]
Marked it as a bug, but it may be resolved by the tool meister work. That remains to be checked.

**Comment by portante** [comment]
This is now handled by the Tool Meister sub-system (see https://github.com/distributed-system-analysis/pbench/blob/main/lib/pbench/agent/tool_meister.py#L276).
