### ISSUE TITLE
pbench-agent install fails on RHEL8 GA

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#1225]
When I try to follow the [directions for ansible-playbook install](http://pbench.perf.lab.eng.bos.redhat.com/agent/installation.html#pbench:installing-using-ansible) on a RHEL8 server, I get:

```
[root@e24-h09-740xd yum.repos.d]# dnf install -y pbench-agent pbench-fio
Updating Subscription Management repositories.
Copr repo for pbench owned by ndokos                                                                                                         41 kB/s |  29 kB     00:00    
Pbench 8 - x86_64                                                                                                                           5.0 kB/s | 5.3 kB     00:01    
Error: 
 Problem: conflicting requests
  - nothing provides screen needed by pbench-agent-0.60-1gc9e89f8f.noarch
  - nothing provides perl(JSON::MaybeXS) needed by pbench-agent-0.60-1gc9e89f8f.noarch
  - nothing provides perl(REST::Client) needed by pbench-agent-0.60-1gc9e89f8f.noarch
  - nothing provides perl(Switch) needed by pbench-agent-0.60-1gc9e89f8f.noarch
  - nothing provides perl-Switch needed by pbench-agent-0.60-1gc9e89f8f.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
Google gets me [this article](https://access.redhat.com/solutions/3707831)  saying "screen" RPM has been replaced with "tmux" in RHEL8.  Here are the repos that are enabled via subscription manager:

```
Repo ID:   rhel-8-for-x86_64-baseos-rpms
Repo Name: Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)
Repo URL:  https://cdn.redhat.com/content/dist/rhel8/$releasever/x86_64/baseos/os
Enabled:   1
```

**Comment by bengland2** [comment]
Karl Rister gave me these instructions, they seem to work, so far.

http://pbench.perf.lab.eng.bos.redhat.com/agent/rhel8.html

Can someone make it so the ansible installer knows how to do this, now that RHEL8 is released?

**Comment by portante** [comment]
@ndokos, do we carry RHEL 8 ansible code in the pbench tree?  If not, there is not much to track in pbench publicly since it is a RHEL 8 issue.

**Comment by ndokos** [comment]
We do not. Only the generic playbooks are available. Also, we are in the process of reworking the existing playbooks to simplify the installation of site-specific bits  (config and key files) and redoing the documentation.

**Comment by portante** [comment]
Closing as we don't maintain ansible code to enable RHEL 8 to work independent of pbench (we do maintain whatever we need to ensure pbench installs properly on RHEL 8).

**Comment by mohit-sheth** [comment]
> Karl Rister gave me these instructions, they seem to work, so far.
> 
> http://pbench...redhat.com/agent/rhel8.html
> 
> Can someone make it so the ansible installer knows how to do this, now that RHEL8 is released?

Hey @bengland2, facing something similar. How did you solve it?
