### ISSUE TITLE
pbench-agent requires python-ara package which does not exist on F30

### ISSUE THREAD

**Issue by hifzakh** [distributed-system-analysis/pbench#1234]
`pbench-agent` requires `python-ara` package, which does not exist on F30, only `python3-ara` exists, but `pbench-agent` does not work with `python3`. So, `ara` data can not be generated on F30 using `pbench-agent`.

**Comment by portante** [comment]
No longer an issue given https://github.com/distributed-system-analysis/pbench/pull/2991/commits/0428ead48f5c56e768afa185867bb7f99edd4d32.
