### ISSUE TITLE
pbench-agent RPM: stockpile-related problems

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1237]
The pbench-agent RPM needs changes to deal with stockpile:

- All of the relevant directories need to be created in the %install section of the specfile. In particualr, the directories `stockpile/roles/dump-facts/templates` and `stockpile/roles/openstack_common/files` needed to be created.

- The F30 COPR build failed because two scripts use unversioned python shebang lines: `stockpile/roles/openshift-cluster-topology/files/openshift_config_scraper.py` and `stockpile/roles/openstack_common/files/openstack-config-parser.py`. For now, I've made the change manually, but we need to add a patch that the specfile can apply.

- Stockpile handling in the specfile needs to be cleaned up.

**Comment by portante** [comment]
No longer an issue given #2971.
