### ISSUE TITLE
Tokenize indexed table of contents data using path hierarchy tokenizer

### ISSUE THREAD

**Issue by gurbirkalsi** [distributed-system-analysis/pbench#1244]
In order to support searching of table of contents data using Elasticsearch, the indexed data requires a [Path Hierarchy Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html) to take on hierarchical values split on path separators.

**Comment by gurbirkalsi** [comment]
@portante it seems most of hits returned from a toc parent id contains pid data. We should be able to filter this data out until we can query/visualize it efficiently.

**Comment by portante** [comment]
Fixed by #1279.
