### ISSUE TITLE
numjobs not creating more jobs in pbench-fio with shared-fs job file

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1255]
With pbench-agent test RPM v0.61, I am able to test with the shared-fs job file, but when using --numjobs=4 in pbench-fio, I don't believe this is translating into 4 jobs per client.  Results show only log files (bs, iops, clat, etc) for 1 job per client, and there is no "--numjobs=4" in the fio.cmd file that pbench-fio creates.

@portante @bengland2 @ndokos FYI

**Comment by atheurer** [comment]
pbench command: pbench-fio --targets=/tmp --job-file=/opt/pbench-agent/bench-scripts/templates/fio-shared-fs.job --block-sizes=4 --samples=1 --test-types=read --runtime=30 --file-size=256M --clients=localhost,perf84 --numjobs=4

**Comment by atheurer** [comment]
this is the "fio.cmd" that pbench-fio generated for this test:
<pre>/usr/local/bin/fio  --client=/var/lib/pbench-agent/fio__2019.07.11T02.28.23/fio-client.file --max-jobs=8 --output-format=json /var/lib/pbench-agent/fio__2019
.07.11T02.28.23/1-read-4KiB/fio.job</pre>

**Comment by portante** [comment]
I took the above `pbench-fio` command and added it to our unit test infrastructure (PR forthcoming).

Here is the generated job file:
```
[global]
bs=4k
ioengine=libaio
iodepth=32
direct=1
sync=0
time_based=1
clocksource=gettimeofday
ramp_time=5
write_bw_log=fio
write_iops_log=fio
write_lat_log=fio
log_avg_msec=1000
write_hist_log=fio
log_hist_msec=10000

[TheJob]
runtime=30
directory=/tmp
rw=read
size=256M
```

And this is the command like that it generated for `pbench-fio`:

```
pbench-fio --output-format=json /var/lib/pbench-agent/fio_test-30_1900.01.01T00.00.00/1-read-4KiB/fio.job  --client=/var/lib/pbench-agent/fio_test-30_1900.01.01T00.00.00/fio-client.file --max-jobs=8
```

**Comment by portante** [comment]
@bengland2, @k-rister, @atheurer, take a look at #1257 to see if that makes sense.
