### ISSUE TITLE
getconf.py version pbench-fio inside pods/containers

### ISSUE THREAD

**Issue by ekuric** [distributed-system-analysis/pbench#1258]
`getconf.py version pbench-fio` returns empty string inside pods/containers and `pbench-fio` exits

```
ver=$(getconf.py version pbench-fio)
if [ -z "$ver" ] ;then
	echo "pbench-fio: package version is missing in config file" > /dev/tty
	exit 1
fi
```
workaround is to use `ver=$(rpm -qa |grep pbench-fio |cut -d'-' -f3)` ...

**Comment by ndokos** [comment]
@ekuric: can you check that $CONFIG is defined in the pod/container and that it points to an existing and accessible config file?

**Comment by ekuric** [comment]
@ndokos will verify and feedback

**Comment by portante** [comment]
@ekuric, that work-around is not valid.  If the code can't properly find the `pbench-fio` version using `getconf.py`, something else is broken.  Are there any additional logs that might shed light on what is happening?

**Comment by portante** [comment]
This looks to be a bug in how the `pbench-agent.cfg` was being setup and now a bug in the pbench-agent.
