### ISSUE TITLE
Bad sosreport data should not stop all indexing of pbench data

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1263]
Today if we can't find the `hostname` or `hostname_-F` files in a sosreport tar ball, the entire indexing step for that tar ball will be killed.

Instead, we should add a marker of some sort indicating a bad `hostname` field for the sosreport, so that we can re-index them later.

**Comment by riya-17** [comment]
@portante @nick So, where should I keep them after changing the marker. As, I can see at present if the tarball consists of Bad sosreport it just displays the message and ends the script.
