### ISSUE TITLE
name pbench_fio summary files based on env where they ran 

### ISSUE THREAD

**Issue by ekuric** [distributed-system-analysis/pbench#127]
necessary to have summary files summary-results.txt/csv and operations written inside to be differently named based on environment where they ran 
eg : 

now 
summary-results.txt
and inside there are 
 1-read-4KiB
....
18-randrw-1024KiB

proposed 
summary-results_baremetal.txt
 1-read-4KiB_baremetal
18-randrw-1024KiB_baremetal 

this will help to search / grep results based on where they were ran for case when there are multiple files / runs. 

Now,summary files get same name for every test case

**Comment by atheurer** [comment]
Those details (baremetal, etc) should be in the name of the main directory for the result.  I am trying to have the summary-result files maintain consistent naming across all benchmarks, so I would rather not include arbitrary naming in that file.

**Comment by ekuric** [comment]
@atheurer ack,  main directories has different names, then thing here I find as issue it when I need to get summary-results files from multiple tests, ... they have all same names, when I need to compare particular operation from summary files , they are named same across all runs. Is it possible to have it at least as option?

**Comment by ashishkamra** [comment]
closing. Re-open if still feel really need it.
