### ISSUE TITLE
pbench support for POWER architecture

### ISSUE THREAD

**Issue by psuriset** [distributed-system-analysis/pbench#1280]
There is a request on google mail thread. This is for tracking purpose. 

---
 followed the instruction to install pbench on my POWER node, but both dnf and yum failed. 
And https://copr.fedorainfracloud.org/coprs/ndokos/pbench/ only has x86 package.
So I am wondering if pbench works on POWER or x86 only.

root@perfzz6lpar1 tmp]# dnf copr enable ndokos/pbench
No such command: copr. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(copr)'"
[root@perfzz6lpar1 tmp]# dnf install pbench-agent
Red Hat Enterprise Linux 7 for IBM Power LE - Extras (RPMs)                                                                                        0.0  B/s |   0  B     00:00    
Red Hat Enterprise Linux 7 for IBM Power LE - Supplementary (RPMs)                                                                                 0.0  B/s |   0  B     00:00    
Red Hat Enterprise Linux 7 for IBM Power LE - Optional (RPMs)                                                                                      0.0  B/s |   0  B     00:00    
Red Hat Enterprise Linux 7 for IBM Power LE (RPMs)                                                                                                 0.0  B/s |   0  B     00:00    
Copr repo for pbench owned by ndokos                                                                                                               0.0  B/s |   0  B     00:00    
Failed to synchronize cache for repo 'ndokos-pbench', ignoring this repo.
No match for argument: pbench-agent
Error: Unable to find a match: pbench-agent

---

**Comment by ndokos** [comment]
There are now pbench-agent RPMs on COPR for POWER and aarch64. I think I've also built supporting RPMs for these arches, so it should work. If not, I may have missed something: please reopen this issue with what's missing.
