### ISSUE TITLE
Modify generation of crontab entries to decouple the time spec from the command.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1283]
Currently, `pbench-server-default.cfg` contains crontab entries in their entirety, e.g.:

    crontab =  * * * * *  flock -n %(lock-dir)s/pbench-dispatch.lock %(script-dir)s/pbench-dispatch

We should split those into two parts: a time spec and a command. The time spec can then be overridden if necessary in specific `pbench-server.cfg` files, without having to duplicate the command.

That will require changes to `server/bin/pbench-activate-create-crontab` and `server/lib/config/pbench-server-default.cfg`. Environment-specific `pbench-server.cfg` files will also have to be modified, but they are external to this code base.

**Comment by portante** [comment]
We are not going to address this issue via changes to the `crontab` and activate scripts, since we are moving to a containerized server architecture which leverages a message passing sub-system between components.
