### ISSUE TITLE
pbench_cyclictest does not work on F22

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#129]
It's looking for a specific version of the package rt-tests - that fails on F22.

I installed the currently available version of rt-tests (4.2.12-1.fc22)
but there is no command named "cyclictest" in the package.

Is the benchmark obsolete?

**Comment by ashishkamra** [comment]
May be the benchmark is obsolete. Action: remove pbench_cyclictest from pbench. Wait for someone to complain.
