### ISSUE TITLE
Problem while testing v0.63 release candidate: tool installation

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1292]
In addition to the problem described in PR #1291, there was a tool installation problem.

The test run was complaining that when trying to stop the tools, the processes that it was trying to kill did not exist. Indeed, there were `tmp/XXX.pid` files and no corresponding process.

It turns out that I had a `tools-default` directory with the standard set of tools, but I had deleted the `pbench-sysstat` RPM on my test VM some time in the past, so there were no `sysstat` tools to run.

Installing the `pbench-agent` RPM did not install `pbench-sysstat` because it is not defined as a dependency.

The RPM is normally installed when `pbench-register-tool-set` is run, but since I already had a `tools-default` file, I did not rerun that script.

The end result was that `screen` was run (and we duly recorded its pid) and it tried to run e.g. `iostat`. Since `iostat` did not exist, `screen` exited immediately. When we got around to killing it, the `screen` process was nowhere to be found.

A secondary problem is that the `pid` files stick around, instead of being deleted.

**Comment by ndokos** [comment]
Closed by PR #1291.

**Comment by portante** [comment]
This was resolved by the 0.71 release, where the Tool Meister sub-system ensures required dependencies for tools are met before proceeding.
