### ISSUE TITLE
./config/benchmark/$benchmark.json files need to support pbench-agent environment variables instead of embedding things like "/opt/pbench-agent/"

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#1320]
Right now we embed specific paths, like /opt/pbench-agent/ in the $benchmark.json, which may be incorrect if pbench-agent is installed in a different path.  We need to allow the $benchmark.json to reference variables like $pbench_install_dir, or other common pbench variables declared in ./base.

**Comment by portante** [comment]
PR #2993 will render this a `wontfix`.
