### ISSUE TITLE
Script to add the VERSION-BUILD-COMMIT_ID string to config file on installation.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1364]
The RPM build process provides files in the installation root called VERSION, SEQNO, SHA1 that contain the strings out of which we build the complete version string (e.g. v0.64-1ga1b2c3). We need this string to appear in the indexed data in order to be able to trace back problems. To do this, we'll add a script that will be invoked as part of the server "activation" process; the script will construct the string and add it to the config file as the value of the `commit_id` option. The indexer and/or the pbench-report-status script will then be able to retrieve it from there.

**Comment by portante** [comment]
@ndokos, did we already address this issue in a PR somewhere?

**Comment by portante** [comment]
@ndokos, any update on the status of this issue?

**Comment by ndokos** [comment]
Yes, that is done by the current server RPM making machinery: see the [Makefile](https://github.com/distributed-system-analysis/pbench/blob/c69094876cb587c0c7a64af62cfdc0bef0e2721f/server/rpm/Makefile#L66) which saves it to a SHA1 file that gets installed on the server (that is also done by the <=0.69 RPM making machinery that is in the internal repo). Then the [ansible playbook](https://github.com/distributed-system-analysis/pbench/blob/rpm-work/server/ansible/roles/pbench-server-add-commit-id/tasks/main.yml) copies it it into the server config file.

**Comment by portante** [comment]
This was done in PR #1793.
