### ISSUE TITLE
When deploying the server, set it to `Maint` to begin with, not to `Active`

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1370]
`pbench-server-activate-setup-host-info` creates the host info file(s) under `pbench-results-host-info.versioned` in the DocRoot directory and makes links to the *active* file(s), which makes the server visible to `pbench-move-results` immediately. We should instead leave existing link(s) alone and, if we have to create them , make them point to the main file(s).

**Comment by portante** [comment]
Fixed by #3028.
