### ISSUE TITLE
pbench_uperf undeterministic port number for uperf server for server counts over 45

### ISSUE THREAD

**Issue by ofthecurerh** [distributed-system-analysis/pbench#138]
pbench_uperf uses a base port number for the server of 20000 and then adds 1000 for each given server. 

When using more than 45 servers the port number is over 65535 and uperf will start assigning random numbers for the server port instead. 

Would it be possible to only increment the port value only if the server IPs overlap?

**Comment by atheurer** [comment]
We can probably do something like that.  I'll take a look.

**Comment by ashishkamra** [comment]
Port number is being incremented by 10 not 1000 now - Committed on June 2015. So that raises the number of servers before the port number is over 65535 to 4500. Please re-open if still a problem.
