### ISSUE TITLE
Preserve result selections within search component to enable multi-controller search

### ISSUE THREAD

**Issue by gurbirkalsi** [distributed-system-analysis/pbench#1383]
Currently, new search queries made within the Search page component reinitialize the selection results. In order to enable multi-controller search, search result selections should be preserved across new queries within the component state.

**Comment by portante** [comment]
@gurbirkalsi, for now I added it to the "Backlog", but remove that label and assign it to a milestone once work begins.  This seems pretty important.  Thanks!

**Comment by portante** [comment]
Addressed by #1388.
