### ISSUE TITLE
`pbench-make-result-tb` errors when arguments contain %.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1392]
% signs are legal in filenames and they are legal as options to some commands (e.g trafficgen - see PR #1390 and the associated issue #1329). PR #1390 is fixing the issue for options added to the metadata log through `pbench-add-metalog-option`. We we were going to test that by passing a `--prefix` or a `--user` option containing a % sign to `pbench-move/copy-results`, but `pbench-make-result-tb` chokes on that. The reason is that it uses

    printf -- "${prefix} | pbench-add-metalog-option ${mdlog} run prefix

and similar, but if the argument to `printf` contains a '%', that's an error:

> $ printf -- "30%"
bash: printf: `%': missing format character

We should change the `printf` calls to

    printf -- "%s" "${prefix}" | pbench-add-metalog-option ....

In addition, there are problems if the result name contains a '%' (e.g. if the user uses a `--config` option with a value containing a '%'). A similar remedy will fix that case as well, but one gotcha is
when the value to be printed contains a newline, e.g. the penultimate line of `pbench-make-result-tb`:

    printf -- "${tarball}\n"

which should be rewritten as:

   printf -- "%s\n" "${tarball}"

Finally, a change will be needed to `pbench-metadata-log` to make sure that when it adds the result name to the `metadata.log` file, it escapes any '%' signs, else the configparser will choke (as it did in issue #1329).

**Comment by riya-17** [comment]
Hey @ndokos 

```Finally, a change will be needed to pbench-metadata-log to make sure that when it adds the result name to the metadata.log file, it escapes any '%' signs, else the configparser will choke (as it did in issue #1329).```

I couldn't find any relevant code in pbench-metadata-log according to this statement

**Comment by ndokos** [comment]
https://github.com/distributed-system-analysis/pbench/blob/master/agent/util-scripts/pbench-metadata-log#L161

You'll need to get the name and pass it through sed (or the bash idiom I showed you last Friday) before you pass it into the here-document.
