### ISSUE TITLE
Parallelize verify backup tarballs

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1397]
Let's consider what it would take to parallelize `pbench-verify-backup-tarballs`.

On our production instance of the pbench server, with 9TB of pbench result tar balls, slow disks not withstanding, we first check the MD5 check sums for the local `ARCHIVE` tree, then we check the local `BACKUP` tree, then we check the S3 store if available.  All of this is done sequentially.

Instead, we could check each of the three in parallel, and then once they all finish, then compare them.

**Comment by sourabhtk37** [comment]
@portante Would like to take a shot at this. We don't check md5sum for S3 store? Just `ARCHIVE` and `BACKUP`.

**Comment by portante** [comment]
> @portante Would like to take a shot at this.

Sure, if you are up for the task, great!

> We don't check md5sum for S3 store? Just `ARCHIVE` and `BACKUP`.

Right, because S3 maintains the bits and ensures they don't rot.  We just need to make sure we can compare what we have against what is in S3.

**Comment by portante** [comment]
@sourabhtk37, have you made any progress on this issue?

**Comment by sourabhtk37** [comment]
No update on this yet. Will pick it up first thing next week.

**Comment by riya-17** [comment]
@sourabhtk37 May I take up this issue, if you are not working on it?

**Comment by sourabhtk37** [comment]
Sure. Please go ahead.
________________________________

**Comment by portante** [comment]
We are moving to a object-store based implementation which will obviate the need for this work.
