### ISSUE TITLE
Fix metadata-log command to references tools-$group directory for all operations

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#141]
We need to update `metadata-log` to derive tool information from the `tools-$group` directory instead of the old `tools.$group` file.

**Comment by ndokos** [comment]
it can deal with either the new or the old setup, but it prefers the new one: if a tools-$group directory exists, it goes for that; otherwise, it falls back to the tools.$group file. I don't see a problem here.

**Comment by portante** [comment]
I see that now, thanks.  But @ndokos why do we need metadata-log to deal with the old tools file?

**Comment by ashishkamra** [comment]
Fixed. The metadata-log now derives tool information from the tool-$group directory.
