### ISSUE TITLE
Uninitialized values in `uperf-postprocess`

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1416]
While running the standard uperf test on v0.66 in Jenkins, I saw this error:

>...
maximum latency: 317562.7990
test sample 2 of 3
client[10.16.31.168]protocol[tcp]test[stream]instances[64]size[65536] <-> server[10.16.31.4]
Use of uninitialized value $this_server_nr_reads in division (/) at /opt/pbench-agent/bench-scripts/postprocess/uperf-postprocess line 359.
Use of uninitialized value $this_server_read_avg_time in division (/) at /opt/pbench-agent/bench-scripts/postprocess/uperf-postprocess line 359.
Illegal division by zero at /opt/pbench-agent/bench-scripts/postprocess/uperf-postprocess line 359.
test sample 3 of 3
...

**Comment by webbnh** [comment]
Now that we're about to release v0.71 and this has not proven to be a recurring problem, we'll close this now and revisit it if it ever recurs.
