### ISSUE TITLE
Replace echo;log_finish;exit with log_exit

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1446]
Related to work performed in #1444, let's replace the use of the pattern, `echo "" >&4; log_finish; exit 1` with the `log_exit` method from `pbench_base.sh`.

**Comment by riya-17** [comment]
Should the lines with different exit codes also dealt the same way?

https://github.com/distributed-system-analysis/pbench/blob/270d1aab2845631092de5a98ab1a80ed3b504c83/server/bin/pbench-dispatch.sh#L107

**Comment by ndokos** [comment]
I think so: you can pass the exit code as an optional argument. Note BTW, that the `tee -a $mail_content` in the line you quote is useless: since we exit, the `$mail_content` file does not go anywhere. So there is no need to include that in `log_exit`.
