### ISSUE TITLE
Website design [information architecture, style guide, hi-fi site design] 

### ISSUE THREAD

**Issue by maryshak1996** [distributed-system-analysis/pbench#1447]
This issue tracks the design process of creating a website for Pbench. Below is the **design roadmap** with links to the work associated with each phase:

- [X] Phase one: Preparation
[Site map + Content inventory](https://docs.google.com/document/d/1wR_VYBe9oGGDKrT5sD8ZQQZ613h87mc316rnXg8O3HY/edit?usp=sharing)
- [x] **[In progress]** Phase two: Conceptual design 
[Wireframe](https://marvelapp.com/51cfcb9)
Style guide creation
- [x] Phase three: Iteration, high-fidelity design, and early development
Home page exploration -- build 3-5 different high-fi designs for the homepage)
Collateral page design
Iterate on final direction / begin structural dev work
- [x] Phase four: Fine-tuning and development
Provide specs -- visual, spacing, and interaction spec

**Comment by maryshak1996** [comment]
tagging @gurbirkalsi and @portante for awareness

**Comment by maryshak1996** [comment]
just in case there's any issues viewing the Marvel wireframe prototype, here's a PDF of the wires and a screen capture of the general flow of the site
[pbench-wires.pdf](https://github.com/distributed-system-analysis/pbench/files/3995678/pbench-wires.pdf)
https://youtu.be/NzLIZw3pb58

**Comment by portante** [comment]
@Anisha1234, can you review this issue and see if it has already been implemented in the documentation work, and if so, link your documentation work PR to this issue?  If it hasn't been implemented, perhaps we should move this issue to the pbench-dashboard repo?

**Comment by Anisha1234** [comment]
@portante I think these all are already implemented in documentation work. I have referenced this issue in the PR.

**Comment by portante** [comment]
Declaring this done as of #1586.

Please re-open if you think there are issues that need to be addressed still.
