### ISSUE TITLE
perl 5.30 seems to round floats differently from earlier versions

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1464]
Running the tool-scripts/postprocess unittests on a F31 system running perl 5.30 shows multiple failures, invariably because a float is now rounded differently than it was rounded when the gold file was produced. The difference is 1 in the last (10th) place e.g.:

````
                 },
                 {
                    "date" : 1459955170000,
!                   "value" : 59021.9301030206
                 },
                 {
                    "date" : 1459955171000,
--- 178,184 ----
                 },
                 {
                    "date" : 1459955170000,
!                   "value" : 59021.9301030205
                 },
                 {
                    "date" : 1459955171000,
````

At some point, this will bite us in the Travis CI, but it does not seem to currently.

**Comment by portante** [comment]
Fixed by #1830.
