### ISSUE TITLE
Update pbench-fio to release 3.18 when it comes out, and build it without librbd.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1477]
We are currently using fio 3.12 to build the pbench-fio RPM, but there are requests to update to a more recent version: the current version is 3.17 but does not include a crucial fix, so this issue is a placeholder to update to 3.18 when that comes out.

At the same time, there is a request to build pbench-fio without the Ceph dependencies (which are not available in various environements, include RHEL8 currently). This issue  is also meant to solicit feedback on this change: is it enough to have a pbench-fio RPM with no Ceph dependencies or do we need separate RPMs, one with Ceph and one without? Obviously, I would prefer having just one pbench-fio RPM to make, but we will do what is necessary.

**Comment by ndokos** [comment]
There is a 3.18 build of fio (pbench-fio 3.18) in the COPR pbench-test repo. It's built without rbd/rados. Other than creating the RPM in the main COPR pbench repo, this is what is going to be in v0.68 of pbench-agent when it comes out (probably early next week). If there are any problems with this (or with the test RPM), please report them here.

**Comment by portante** [comment]
Fixed by #1569.
