### ISSUE TITLE
Proposal: Break the pbench Git repo into agent, server, and dashboard repos

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1497]
See https://github.com/distributed-system-analysis/pbench/pull/1496#issuecomment-584257005

It seems it is worth considering what it would take to break up the pbench code base into separate agent, server, and dashboard git repos.

Pros:

- Each code base can iterate at their own pace
- The CI infrastructure would be independent and would not longer inadvertently impact another sub-system
- Packaging for each repo can be made simpler

Cons:

- Lots of code churn to make new repositories
- Maintaining history for new repos might be confusing

The proposal is to create two new repos:

- Agent: https://github.com/distributed-system-analysis/pbench-agent
- Dashboard: https://github.com/distributed-system-analysis/pbench-dashboard
- Server: keeps existing repo

The Server repo would be the source of the history.  We'd tag the repo branch points for the agent and dashboard in the server repo, create the new code bases, and then refactor the server code base to only have server code (including the legacy static html file handling).

**Comment by zulcss** [comment]
Can we get a README included in the pbench-agent repo so its populated? I can start proposing PRs for pbench-agent after.

**Comment by k-rister** [comment]
This only seems viable to me if you manage to push the agent and dashboard code into the new repositories in such a way as to maintain the commit history on those files.  I think that makes the work to do so a lot more time consuming but there is a lot of valuable information there that should be readily available without having to go find it in some other repository.

**Comment by atheurer** [comment]
How about forking the repo into 3 repos, then renaming them, and in each of them removing the code not needed for that repo?  For example, fork pbench to pbench-dashboard, then add a commit to remove all non dashboard code.  And so the full history is preserved for each repo you fork..

**Comment by portante** [comment]
As of PR #1509, the pbench dashboard code has been moved to its own [repository](https://github.com/distributed-system-analysis/pbench-dashboard).

We are planning on keep the server and agent code together for the short term.
