### ISSUE TITLE
pbench-verify-backup-tarballs does not scale

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1519]
Currently, `pbench-verify-backup-tarballs` calculates the MD5 sum of every tar ball in the archive, as well as every tar ball in the "local" backup. It then compares the two (and also the archive results with the S3 backup, but that is *not* the problem here).

The problem is that the "local" backup is on an NFS filesystem, at the other end of a network cable, so checking the backup transfers all of the tar balls to the system that does the check (i.e. our production server) in order to check-sum them. That is already a problem with a fast connection; it is going to be much worse with a slow connection now that the network cable got much longer.

We need to reorganize the verification. I propose we split it into two pieces: one piece scans the local filesystem and generates a list of tar balls together with their (current) MD5s plus an error report of any that bit-rotted and failed the local check. This piece can run independently on the machine where the archive is stored and on the machine where the backup is stored. The lists and error reports can be stored either locally or in shared storage (maybe NFS, maybe S3).

The second piece pulls the lists and error reports and does the comparisons, just as is done today in `pbench-verify-backup-tarballs`. It also does the comparison with S3 just as is done today, since only the list is needed. The results of the comparisons and the error reports from the two nodes are enough to create the final report.

**Comment by portante** [comment]
We are moving to an object-store based implementation which will obviate the need for this work.
