### ISSUE TITLE
Setting the logging level for server scripts

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1530]
The logging level for all the (python) server scripts is set to DEBUG right now: we need to be able to turn it down to INFO for production use, although we need to have it at DEBUG for unit tests (the gold files include the debug logging output).

This can be easily done through the config file: set a default logging level, then use it at script it initialization (except in the unit test regime). We can also allow script-specific settings that override the default, allowing us e.g. to temporarily turn on debug logging for a particular script in production.

**Comment by portante** [comment]
Resolved by #1580.
