### ISSUE TITLE
blktrace collection not working

### ISSUE THREAD

**Issue by smalleni** [distributed-system-analysis/pbench#1548]
I registered the blktrace tool for collection using
```pbench-register-tool --name=blktrace```

However, there are two issues when trying to collect blktrace data.

1. After registering the tool and running the benchmark, when looking at the pbench results, it says blktrace was not installed on the system and hence there is no blktrace data. 

2. After installing blktrace on the system and then running the benchmark,  in the pebnch result tools data at blktrace-stderr.txt I see
```
Usage: blktrace 

-d <dev>             | --dev=<dev>
[ -r <debugfs path>  | --relay=<debugfs path> ]
[ -o <file>          | --output=<file>]
[ -D <dir>           | --output-dir=<dir>
[ -w <time>          | --stopwatch=<time>]
[ -a <action field>  | --act-mask=<action field>]
[ -A <action mask>   | --set-mask=<action mask>]
[ -b <size>          | --buffer-size]
[ -n <number>        | --num-sub-buffers=<number>]
[ -l                 | --listen]
[ -h <hostname>      | --host=<hostname>]
[ -p <port number>   | --port=<port number>]
[ -s                 | --no-sendfile]
[ -I <devs file>     | --input-devs=<devs file>]
[ -v <version>       | --version]
[ -V <version>       | --version]
	-d Use specified device. May also be given last after options
	-r Path to mounted debugfs, defaults to /sys/kernel/debug
	-o File(s) to send output to
	-D Directory to prepend to output file names
	-w Stop after defined time, in seconds
	-a Only trace specified actions. See documentation
	-A Give trace mask as a single value. See documentation
	-b Sub buffer size in KiB (default 512)
	-n Number of sub buffers (default 4)
	-l Run in network listen mode (blktrace server)
	-h Run in network client mode, connecting to the given host
	-p Network port to use (default 8462)
	-s Make the network client NOT use sendfile() to transfer data
	-I Add devices found in <devs file>
	-v Print program version info
	-V Print program version info
```

Two issues here
1. Shouldn't pbench warn the user if a registered tool is not installed?
2. Looks like blktrace is not being fired off correctly based on blktrace-stderr.txt

Thoughts @portante @ndokos

**Comment by smalleni** [comment]
This is the blktrace command that is being used
```blktrace  >/var/lib/pbench-agent/fio_esxi-rhelguest-thickprovisioned-eagerlyzeroed-large-file-sda_2020.03.17T20.59.54/1-write-4KiB/sample3/tools-default/blktrace/blktrace-stdout.txt```

**Comment by smalleni** [comment]
RPM info
[root@sai_rhel8 ~]# rpm -qa | grep pbench
pbench-sysstat-12.0.3-1.x86_64
pbench-agent-0.67-1g3fb4270c.noarch
pbench-perl-Types-Serialiser-1.0-1.noarch
pbench-perl-JSON-XS-4.02-1.x86_64
pbench-agent-internal-0.67-1.noarch
pbench-fio-3.12-1.x86_64
pbench-perl-common-sense-3.74-1.x86_64
[root@sai_rhel8 ~]# rpm -qa | grep blktrace
blktrace-1.2.0-10.el8.x86_64

**Comment by smalleni** [comment]
@mnmehta Looks like we need to pass the device path to blktrace?

**Comment by portante** [comment]
@smalleni, try:

```
pbench-register-tool --name=blktrace -- --devices="/dev/sda,/dev/sdb,..."
```

**Comment by k-rister** [comment]
@smalleni 

Even if it did work without specifying the block device I would highly recommend to only run it in targeted mode, ie. against a block device that is being tested and not the whole system.  The amount of data that you would generate otherwise would probably be untenable.

**Comment by smalleni** [comment]
Thanks @portante ! Works now. Ack @k-rister

**Comment by smalleni** [comment]
@portante Another question, what is the pbench policy on tools that are registered but not installed on the system?

**Comment by portante** [comment]
So prior to the 0.68 release (currently in the works), some tools attempt to install the required software (which is a big mistake, and can lead to many issues).

Starting with 0.68, the tools to report that they don't have the required software to run.

Does that make sense?

**Comment by smalleni** [comment]
It would be good if a warning like "you are trying to collect blktrace tool data, but it is not installed on host" would be good instead of user running the entire test suite and realizing blktrace was not installed. Thoughts?

**Comment by portante** [comment]
> It would be good if a warning like "you are trying to collect blktrace tool data, but it is not installed on host" would be good instead of user running the entire test suite and realizing blktrace was not installed. 

See the latest code that will be available in the 0.68 release: https://github.com/distributed-system-analysis/pbench/blob/master/agent/tool-scripts/datalog/blktrace-datalog#L14

That work, performed in PR #1460, was a significant refactoring of the tools infrastructure to add those messages, and unit tests too.

**Comment by atheurer** [comment]
Was there some kind of announcement about this change in behavior with the release notes?

**Comment by portante** [comment]
> Was there some kind of announcement about this change in behavior with the release notes?

We are currently work on finalizing the 0.68 release, so no release notes as of yet.  This change was in the PR #1460 description at the top.
