### ISSUE TITLE
Warnings issued by pbench-fio (upstream issue opened)

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1568]
We have opened an issue with upstream fio: [#947](https://github.com/axboe/fio/issues/947).
This pbench  issue is a tracker for the upstream one. The symptom of this problem is
that pbench-fio postprocessing produces a slew of warnings like this:

```
...
[WARNING] fio_slat.4.log: timestamp 48061 for rwtype 0 found multiple times, values [6217, 2000] will be averaged
[WARNING] fio_slat.4.log: timestamp 51011 for rwtype 0 found multiple times, values [20874, 4000] will be averaged
[WARNING] fio_slat.4.log: timestamp 54007 for rwtype 1 found multiple times, values [5942, 3000] will be averaged
[WARNING] fio_slat.4.log: timestamp 55039 for rwtype 1 found multiple times, values [16264, 3000] will be averaged
[WARNING] fio_slat.4.log: timestamp 55039 for rwtype 0 found multiple times, values [13723, 3000] will be averaged
[WARNING] fio_slat.4.log: timestamp 58038 for rwtype 0 found multiple times, values [7751, 60000] will be averaged
...
```

This is caused by the underlying `fio` and has nothing to do with `pbench`. Currently pbench uses version 3.12 of fio and we are planning to move to version 3.18 of fio for the v0.68 pbench-agent release: both of these versions produce these duplicate timestamps (anecdotally, 3.18 produces more of them than 3.12 - but that's from eyeballing the output, so take it with a grain of salt).

This issue supersedes #991.

**Comment by portante** [comment]
The upstream issue with `fio` was first fixed in `fio-3.20`.  Closing as resolved: we moved to minimally support v3.21 in PR #1748.
