### ISSUE TITLE
pbench-run-benchmark fio support needs to be updated to use the new 3.18 fio package

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#1573]
https://github.com/distributed-system-analysis/pbench/blob/1da70e47c86d6e8e4bc40d2a47e98aa7901fa57b/agent/config/benchmark/fio.json#L114

@ndokos If you know the package name for the new version of fio can you update this?

@portante FYI...

**Comment by ndokos** [comment]
Will do as part of #1574. Thanks for bringing this to my attention.
