### ISSUE TITLE
Get rid of trying to copy directory error (when scp did not use -r)

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#16]
This issue is to remove a harmless but confusing error message when pbench_fio copies over result files on remote systems.  The scp does not use "-r", but tries to copy everything in a directory with a wildcard -including a subdirectory.

**Comment by arcolife** [comment]
@atheurer  you mean like the error message ```$benchmark_results_dir/<subdir>: not a regular file``` ? in that case, would something like ``` grep -v "not a regular file" `` suffice to filter this out? is there something else one might use here?

**Comment by atheurer** [comment]
Yes, that grep would probably work.  However, I would just prefer to provide a more specific name/wildcard for the files we want.

**Comment by atheurer** [comment]
Fixed with https://github.com/distributed-system-analysis/pbench/commit/30faf864a2fa10c04c07ab8a15f373d57ad366fb
