### ISSUE TITLE
Remove [pbench-]unregister-tool script

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#160]
It should now be `clear-tools`.

Or since we use "register", perhaps consider removing the current `unregister-tool` and rename `clear-tools` to `unregister-tools`.

**Comment by ndokos** [comment]
PR #162 - I left the name  as `pbench-clear-tools`.

One question: the travis-ci stuff seems not to have run - why?

**Comment by ndokos** [comment]
Fixed in PR #162 - the tests ran eventually.

**Comment by ndokos** [comment]
Actually, we are missing a major piece of functionality: `pbench-unregister-tools --remote=foo` can not be  simulated using the current implementation of `pbench-clear-tools`.

**Comment by ashishkamra** [comment]
Fixed in PR #482
