### ISSUE TITLE
Improve handling of sync satellite logs

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1609]
If we have connection problems to the remote satellite host, we see the following in the `.log` file:

```
run-2020-02-20T06:35:01-UTC: start - 2020-02-20T06:35:02-UTC
ssh: connect to host pbench-satellite.example.com port 22: No route to host
```

And a single line added to the `.error` file:

```
pbench-sync-satellite: pbench-sync-satellite: pbench-remote-sync-package-tarballs: failed.
```

Let's consider capturing the `ssh` error message into a file, and adding that to a `report_status` call.

We should also consider remove the output in the error file entirely, adding it to the improved `report_status` call.

**Comment by riya-17** [comment]
Hey @portante How can I regenerate this error?

**Comment by portante** [comment]
You can change the mock in the unit tests for ssh to add a case for failure.
