### ISSUE TITLE
Confusing names.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1646]
`pbench-user-benchmark` can be confused with the internal command `pbench-run-benchmark`.

Internal utilities should not be in `$PATH`.

Both scripts are at the same directory - `/opt/pbench-agent/bench-scripts`.

**Comment by portante** [comment]
The `pbench-run-benchmark` interface has been marked deprecated as of #2545.  We'll track the removal of it in issue #2511.
