### ISSUE TITLE
Install a default tool set

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1648]
After the installation, the default tools group is empty. The user has to create it with pbench-register-tool-set. 

Suggestion: call pbench-register-tool-set automatically when installing rpm (%post script in rpm spec file)

Add default/suggested groups for benchmarks

Part of benchmarks RPM files (example pbench-fio.rpm)

In %post section of rpm specfile?

Name: something like “fio-default-tool-group”

**Comment by portante** [comment]
We are no longer going to have a `default` tool set in the Agent 1.0 release time frame, see https://github.com/distributed-system-analysis/pbench/issues/3001.
