### ISSUE TITLE
Error when running pbench-remote-sysinfo-dump --help

### ISSUE THREAD

**Issue by zulcss** [distributed-system-analysis/pbench#1649]
Usage: mkdir [OPTION]... DIRECTORY...
Create the DIRECTORY(ies), if they do not already exist.

Mandatory arguments to long options are mandatory for short options too.
  -m, --mode=MODE   set file mode (as in chmod), not a=rwx - umask
  -p, --parents     no error if existing, make parent directories as needed
  -v, --verbose     print a message for each created directory
  -Z                   set SELinux security context of each created directory
                         to the default type
      --context[=CTX]  like -Z, or if CTX is specified then set the SELinux
                         or SMACK security context to CTX
      --help     display this help and exit
      --version  output version information and exit

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/mkdir>
or available locally via: info '(coreutils) mkdir invocation'
Failed to create --help

**Comment by portante** [comment]
@zulcss, since `pbench-remote-sysinfo-dump` is an internal interface, is this something we have to fix now, or are you going to fix this along with your other Python3 work?

**Comment by zulcss** [comment]
Yeah I was confused.
