### ISSUE TITLE
make pidstat graphs usable

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#166]
Right now the pidstat graphs attempt to plot all the pids on the system.  We should set a threshold to things using more than 1% of CPU or something like that so that the graphs actually work.

**Comment by jeremyeder** [comment]
I think our iostat graphs do something like this already when determining what block devices to display.

**Comment by ndokos** [comment]
@jeremyeder: I think the current graphs implement the threshold you suggested. Closing this, but please reopen if you disagree.
