### ISSUE TITLE
packaged version of pidstat doesn't collected data for new PIDs

### ISSUE THREAD

**Issue by ofthecurerh** [distributed-system-analysis/pbench#167]
The version of pidstat (currently v.11.1.2-1) available in the pbench repos (https://copr.fedorainfracloud.org/coprs/ndokos/pbench/) doesn't collected data for PIDs that start after pidstat is started. 

I couldn't tell by looking at the sysstat changelog when this bug was fixed, but I've verified that it works in version 11.1.5.

**Comment by ndokos** [comment]
There are packages of version 11.2.0 there now - does that resolve the problem?

**Comment by ofthecurerh** [comment]
@ndokos yeah 11.2.0 works, thanks for the quick fix!
