### ISSUE TITLE
Request to add new options to pidstat command 

### ISSUE THREAD

**Issue by ofthecurerh** [distributed-system-analysis/pbench#168]
It seems that right now the only user configurable option for pidstat is the collection interval. 

I think it would be useful to add the following options:
- R option for reporting realtime priority and scheduling policy information
- U option to display the real user name of the tasks being monitored instead of the UID

**Comment by ndokos** [comment]
pbench-register-tool allows specifying options with

```pbench-register-tool --name=pidstat -- --options="-R -U"```

but the tool-scripts/pidstat tool completely ignores the additional options.

We could add these options to the default set (specified in tool-scripts/pidstat) , or we could replace the default set by these options, but there is a significant problem: the postprocessing tools usually assume that there is a well-defined (and a priori fixed) format to the tool output; additional options might modify tje format of the output, with the result that the postrpocessing tool might be thoroughly confused.

@atheurer: WDYT? Is the above right? Is there something we could do with such additional options? Maybe we should delete the --options option in pidstat/sar/etc.?

Alternatively, we could change the standard  options (and the postprocessing script for pidstat). @ofthecurerh: is that what you are suggesting?

**Comment by k-rister** [comment]
On 03/17/2016 02:00 PM, Nick Dokos wrote:
> pbench-register-tool allows specifying options with
> 
> |pbench-register-tool --name=pidstat -- --options="-R -U"|
> 
> but the tool-scripts/pidstat tool completely ignores the additional options.
> 
> We could add these options to the default set (specified in
> tool-scripts/pidstat) , or we could replace the default set by these
> options, but there is a significant problem: the postprocessing tools
> usually assume that there is a well-defined (and a priori fixed) format
> to the tool output; additional options might modify tje format of the
> output, with the result that the postrpocessing tool might be thoroughly
> confused.
> 
> @atheurer <https://github.com/atheurer>: WDYT? Is the above right? Is
> there something we could do with such additional options? Maybe we
> should delete the --options option in pidstat/sar/etc.?
> 
> Alternatively, we could change the standard options (and the
> postprocessing script for pidstat). @ofthecurerh
> <https://github.com/ofthecurerh>: is that what you are suggesting?

What about only enabling the postprocessing when a known set of options
are used while still allowing the user to modify the options if needed?

Pidstat has some pretty nice options which can be useful at times, but
some have significant overhead (threads).  Allowing users to access
those when needed would be nice without requiring their overhead to be
endured by everyone.

> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/distributed-system-analysis/pbench/issues/168#issuecomment-198035008>
> 


-- 
Karl Rister
<krister@redhat.com>

**Comment by atheurer** [comment]
We have support for the threads option, and our post-processing is -supposed- to handle that, but I would not be surprised if that is broken.

At one time (not sure if it's still there), many of the tools would completely disable any post-processing if any --options= was used, for the reason @ndokos stated.

It's possible we can add these two options, but I'd prefer to make them the default if they do not add a lot of overhead.  I really don't want to add another parsing section for two different pidstat output versions.

FWIW, would be a lot easier if pidstat could just export its data in a json or csv file natively.  Actually the pcp tool might end up being better for us since it does that (csv) and it has stats similar to pidatst.

**Comment by ndokos** [comment]
Ideally, the tool would produce self-documenting results (perhaps JSON, or perhaps csv where the postprocessing could parse the header line to figure out what's there).

But @atheurer beat me to it :-)

**Comment by k-rister** [comment]
On 03/17/2016 02:12 PM, Andrew Theurer wrote:
> We have support for the threads option, and our post-processing is
> -supposed- to handle that, but I would not be surprised if that is broken.
> 

Cool if it works.  That was just an example I have experienced, not sure
about other options.

> At one time (not sure if it's still there), many of the tools would
> completely disable any post-processing if any --options= was used, for
> the reason @ndokos <https://github.com/ndokos> stated.

This seems ideal to me, do what it does unless conditions change where
it can't -- but always collect the data the user wants.

> 
> It's possible we can add these two options, but I'd prefer to make them
> the default if they do not add a lot of overhead. I really don't want to
> add another parsing section for two different pidstat output versions.

Agreed.

> 
> FWIW, would be a lot easier if pidstat could just export its data in a
> json or csv file natively. Actually the pcp tool might end up being
> better for us since it does that (csv) and it has stats similar to pidatst.
> 
> —


-- 
Karl Rister
<krister@redhat.com>

**Comment by ofthecurerh** [comment]
@ndokos I realize this would probably break the post processing, but has it been updated to be more usable? I usually just do my own processing on the raw output.

**Comment by ndokos** [comment]
@ofthecurerh: no, not yet. I'll submit a PR along the lines of "do not run postprocessing if the options have been modified from the default" shortly.

**Comment by ndokos** [comment]
PR #200
