### ISSUE TITLE
pbench oc tool should collect master metrics

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#172]
The /metrics endpoint of an openshift/kubernetes master exposes tons of metrics that we need to collect.

It requires authentication, but we should be able to fish that out of /etc/origin/master/admin.kubeconfig as is done by the ops folks in this script:

https://github.com/openshift/openshift-tools/blob/master/openshift_tools/web/openshift_rest_api.py

We will likely want to create graphs of some of the metrics, but let's get the data collection done first.

@hroyrh

**Comment by timothysc** [comment]
Probably better to integrate with other systems both [scrape + storage] (prom) and graphing (prom-dash/grafana)

**Comment by portante** [comment]
@timothysc, do you mean: https://prometheus.io/docs/visualization/promdash/ ?

**Comment by timothysc** [comment]
@portante yup

**Comment by ofthecurerh** [comment]
@jeremyeder If we just want the raw metrics we can replace their python rest client with:
`curl --cacert ./ca.crt --cert ./admin.crt --key ./admin.key https://<public-ip>:8443/metrics`

Is there something extra they are doing that we want to use?

@timothysc how are you wanting to use prometheus here? I think we might be able to grab the raw data with pbench and then load it into prometheus after the fact [https://github.com/prometheus/pushgateway](url)

**Comment by jeremyeder** [comment]
This did it:

```
curl -k --cacert ./ca.crt --cert ./admin.crt --key ./admin.key https://127.0.0.1:8443/metrics
```

**Comment by jeremyeder** [comment]
Prototype of using the "user-tool" method.  It works, with a few caveats:

- Don't see $interval being passed into the external script.
- Now we have to own/distribute this script somehow (external to pbench I guess).

Both are cases for making this a real part of the oc tool IMO.

```
# cat /tmp/metrics.sh 
#!/bin/sh

export ssldir=/etc/origin/master

while true ; do
curl -k --cacert $ssldir/ca.crt --cert $ssldir/admin.crt --key $ssldir/admin.key https://127.0.0.1:8443/metrics
sleep 5
done
```

One thing to note...each scrape of the metrics endpoint outputs 250KB of data.  So, a 1 hour test @ 10sec interval is 90MB of raw text.

```
pbench-register-tool --name=user-tool -- --tool-name=metrics --start-script=/tmp/metrics.sh
pbench-user-benchmark -C metrics3 -- sleep 20

# ls -al /var/lib/pbench-agent/pbench-user-benchmark_metrics3_2016-03-15_14:26:02/1/reference-result/tools-default/ip-172-31-4-39/user-tool-metrics
total 984
drwxr-xr-x. 2 root root     96 Mar 15 10:26 .
drwxr-xr-x. 3 root root     30 Mar 15 10:26 ..
-rwxr-xr-x. 1 root root     16 Mar 15 10:26 user-tool.cmd
-rw-r--r--. 1 root root   1268 Mar 15 10:26 user-tool-metrics-stderr.txt
-rw-r--r--. 1 root root 997664 Mar 15 10:26 user-tool-metrics-stdout.txt

```

**Comment by atheurer** [comment]
The interval option is only used when user-tool captures a file periodically.  An interval for your script should be done as you did with your own "sleep n" command.

**Comment by ndokos** [comment]
Jeremy Eder <notifications@github.com> writes:

> Prototype of using the "user-tool" method. It works, with a few caveats:
>
>   * Don't see $interval being passed into the external script.
>   * Now we have to own/distribute this script somehow (external to
>   pbench I guess).

We can put it in bench-utils/contrib, which is where Ricardo's script is
going until it becomes a "real" pbench script (I sense a new version of
Pinnochio here...)

--
Nick

**Comment by ashishkamra** [comment]
Don't need it any more. Using prometheus now.
