### ISSUE TITLE
Fix typo in Pbench Installation Guide

### ISSUE THREAD

**Issue by riya-17** [distributed-system-analysis/pbench#1720]
Doc is asking to create  ~/.config/**Inventory**/myhosts.inv file, however uses ~/.config/**Inventories**/myhosts.inv

**Comment by gonidelis** [comment]
@riya-17  Could you put some reference please? I can't find the corresponding doc.

**Comment by riya-17** [comment]
@gonidelis here is the link to the doc: [Pbench-installation-doc](http://pbench.perf.lab.eng.bos.redhat.com/agent/installation.html#pbench:installing-using-ansible)

**Comment by gonidelis** [comment]
@riya-17 For some reason the link seems broken to me.

**Comment by riya-17** [comment]
@gonidelis Sorry to not mention that but this doc is only available internally.

**Comment by portante** [comment]
We can't really use GitHub issues to track this problem since this does not exist in the `master` branch or in `gh-pages`.
