### ISSUE TITLE
Bench scripts should require RPMs named generically

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1723]
We want to abandon building `pbench-<benchmark>` RPMs: instead we want to use RPMs available from the distro repos or from EPEL - if available. We might still have to build some internally if they are not available anywhere else (or for other reasons). But we want to use their standard names in any case: no more `pbench-<something>`, just `<something>`.

To that end, all the bench scripts need to be modified to require the "bare" RPM. The `pbench-fio` and `pbench-uperf` bench scripts have already been modified to do that. Now we need to do it for all the rest, but it all requires coordination: an upstream or EPEL RPM needs to be identified for each one if available; then the corresponding script can be modified. For benchmarks where we cannot find an upstream RPM, we need to build one in COPR with the bare name and then modify the corresponding benchscript.

**Comment by portante** [comment]
We want to exit the business of owning multiple benchmark scripts, supporting just `pbench-user-benchmark` and integrating with external workloads.
