### ISSUE TITLE
Add pbench-agent.cfg (without server settings) to pbench-agent RPM

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1727]
As part of `pbench-agent`, we distribute `pbench-agent-default.cfg` which contains the default settings for pbench-agent and `pbench-agent.cfg.example` which contains three things: a setting for the installation directory (by default `/opt/pbench-agent` which is where the `pbench-agent` RPM installs things), some dummy settings for how the agent should communicate with the server in order to send results to it, and a link to the default config file in order to pick up the rest of the settings.

The idea was that after installation of the RPM, a user can copy the example `pbench-agent.cfg.example` to `pbench-agent.cfg` and make the necessary changes to allow the agent to communicate with the server.

Note however that it is quite possible to do all of the normal "pbench-agent" things (register tools, run benchmarks, collect results locally, even view results locally with the help of the `pbench-web-server` RPM) *without* the settings that allow the agent to communicate with the server. The only time those settings are used is when the user tries to invoke `pbench-copy-results` or `pbench-move-results`.

So we could distribute a  `pbench-agent.cfg` file without any server settings that would allow a user to do anything except send results to the server. That would make the RPM  completely self-sufficient in that sense.  If a user tries to use `pbench-copy/move-results` without those settings, they should get a complaint to that effect and instructions on how to go about remedying the situation (e.g. run some ansible playbook to add the appropriate settings).

BTW, this is probably a bug, but I don't think `pbench_results_redirector` is used at all: `pbench-agent-default.cfg` misspells it as `pbench_result_redirector` so I doubt anybody uses it.

**Comment by portante** [comment]
@ndokos, now that we have merged #1745, is there anything else we need to do in the `pbench-agent` RPM `.spec` file?

**Comment by ndokos** [comment]
No, I forgot to link the issue, so it was not closed automatically.

**Comment by ndokos** [comment]
Closed by #1745
