### ISSUE TITLE
fio: Fedora RPM 3.19-3 does not install `fio-hist-log-pctiles.py`

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1728]
Installing the `fio` RPM on Fedora 32 satisfies the dependency that `pbench-fio` is looking for, but there are failures in post-processing, because `fio-histo-log-pctiles.py` is *not* installed.

**Comment by sandeen** [comment]
FYI, this file (actually fio-histo-log-pctiles.py) is present but not installed by "make install" upstream; I would suggest proposing a change to upstream to add it to the "make install" target, and then the Fedora fio RPM will have it as well.

**Comment by sandeen** [comment]
Ah, sorry I should have looked past 3.19.  This was resolved in fio-3.20 with the upstream commit:

```
commit 6f4e03b08edea90f0adad4bb4f05c12729a58217
Author: Aakarsh Gopi <aakarsh.g2012@gmail.com>
Date:   Thu Apr 16 14:34:46 2020 -0400

    Add fio-histo-log-pctiles to make file
    
    This was missing earlier
```

**Comment by portante** [comment]
@sandeen, thanks!

**Comment by portante** [comment]
FYI, filed BZ [#1861158](https://bugzilla.redhat.com/show_bug.cgi?id=1861158) to track addition to Fedora builds.
