### ISSUE TITLE
turbostat tool fails when run inside a KVM guest

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#173]
turbostat tool is part of the default tool-set.  But when pbench is used inside a KVM guest turbostat cannot/will not run.

Actually it's not a huge issue because it only shows up as a "cant find a turbostat pid to kill" when user-benchmark ends.

```
# dmidecode|grep KVM
	Product Name: KVM
# turbostat -i1
turbostat: /dev/cpu/7/msr offset 0xe2 read failed: Input/output error
```

turbostat datalog needs to be conditionalized to only run when not in KVM.

What's funny is that turbostat runs OK inside Xen/EC2, but I don't know if we can trust the data.

```
# dmidecode|grep Product
	Product Name: HVM domU
root@ip-172-31-2-226: ~ # turbostat sleep 3
     CPU TSC_MHz     SMI  CPU%c1  CPU%c3  CPU%c6  CPU%c7 Pkg%pc2 PkgWatt RAMWatt   PKG_%   RAM_%
       -    2394       0  100.00    0.00    0.00    0.00    0.00   51.44    8.25    0.00    0.00
       0    2394       0  100.00    0.00    0.00    0.00    0.00   51.44    8.25    0.00    0.00
       1    2394       0  100.00
3.009719 sec
```

**Comment by atheurer** [comment]
Let's add some kind of test for turbostat --install, so when register-tool is called, it will not be added when that turbostat --install call fails

**Comment by jeremyeder** [comment]
#175

**Comment by ndokos** [comment]
PR #175 has been merged. Closing this issue.
