### ISSUE TITLE
upgrade to sysstat-11.2 has broken memory graphs

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#174]
sysstat-11.1.2-32:  http://pbench.perf.lab.eng.bos.redhat.com/results/jerms-lab7/pbench-user-benchmark_test-pbench-sysstat-11.1.2-32_2016-02-17_14:49:48/1/reference-result/tools-default/jerms-lab7/sar/memory.html

sysstat-11.2.0-1:  http://pbench.perf.lab.eng.bos.redhat.com/results/jerms-lab7/pbench-user-benchmark_test-pbench-sysstat-11.2.0-1_2016-02-17_14:56:12/1/reference-result/tools-default/jerms-lab7/sar/memory.html

**Comment by atheurer** [comment]
There are a lot more memory stats on the new version which makes the parsing fail.  I'll add a new parser for this.

**Comment by atheurer** [comment]
I have compared all sar headers to see if there are any other new stats, and there are not (other than memory)

**Comment by ndokos** [comment]
Fixed in PR #181.
