### ISSUE TITLE
pbench-server RPM incorrectly provides `getconf.py` instead of `pbench-config`

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1740]
As a result of the `br69` branch merge, the pbench-server RPM incorrectly provides `getconf.py` instead of the new `pbench-config` command.  This causes the pbench-server installation via the supported ansible playbooks to fail.

**Comment by ndokos** [comment]
The current workaround is a branch `b0.69` based on the last release before the `br69` merge. Switching to that branch before trying to install the server RPM makes the ansible playbooks work. Obviously, this is a short-term workaround until the v0.70 release, at which point the branch can be deleted.

**Comment by portante** [comment]
Fixed by #1871.
