### ISSUE TITLE
Provide an ansible playbook & role for installing the pbench-agent on RHEL 7 / 8 with subscription manager

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1744]
We really should provide an ansible playbook & role for installing the pbench-agent bits on RHEL 7 & 8 environments with the proper required repositories for Red Hat subscription manager.

**Comment by ndokos** [comment]
We have a role for that in the internal repo. Do we need it in Github?

**Comment by portante** [comment]
We don't.
