### ISSUE TITLE
Make the error message about a missing default tool-set more user-friendly

### ISSUE THREAD

**Issue by frival** [distributed-system-analysis/pbench#1747]
`pbench-user-benchmark` (and the other `pbench-*` benchmark scripts) could use a more user-friendly error message when the tool group, `default`, is not created.

If you get `-EEXIST` or `-ENOTDIR`, it would probably be better to swallow the `errno` value and spit out an english statement that the user needs to invoke `pbench-register-tool-set` with a tool set name (using `default` if they did not create their own), or supply an alternate tool group on the command line of the `pbench-*` benchmark script.

**Comment by portante** [comment]
This behavior was fixed with the [v0.71](https://github.com/distributed-system-analysis/pbench/releases/tag/v0.71.0) release.
