### ISSUE TITLE
When using tcpdump with 2 args like --interface=br1 --packets=1000 2nd arg is ignored

### ISSUE THREAD

**Issue by mnmehta** [distributed-system-analysis/pbench#1751]
https://github.com/distributed-system-analysis/pbench/blob/e9a3b3fa2d54ee11940e5e4b014e1fe48936a65b/agent/util-scripts/pbench-postprocess-tools#L166

@David Gray looks like you ran into a bug, if you specify something like --interface=br1 --packets=1000 the 2nd arg is being ignored, and gets the default value of 500. Your quick fix is to edit /opt/pbench-agent/util-scripts/pbench-postprocess-tool around line 166 replace "printf --" with "echo -e". @Peter Portante it looks like  printf -- --interface=br1 --packets=100 will only print the first arg, it does not print the 2nd. You can probably fix it by putting more escaped quotes on around tool_opts, or the echo -e also seems to work.

**Comment by portante** [comment]
Fixed by #1813.
