### ISSUE TITLE
RFC: Only check script version when benchmark_bin not supplied

### ISSUE THREAD

**Issue by ldoktor** [distributed-system-analysis/pbench#1758]
Hello guys, recently I needed to use my custom built `fio` benchmark, but `pbench` still complains about `fio` not being installed. This is because the `fio_install` function doesn't really verify whether the `benchmark_bin` path contains a `fio` with the right version, but it only checks that the `rpm` installed on the system is of the right version.

I can see 2 issues with this:

1. It does not work for custom supplied `benchmark_bin` (meaning it might not check the benchmark_bin's version and instead assumes the version based on system-installed RPM)
2. It does not work at all on non-rpm based distros

I'd like to suggest 2 ways to handle this:

1. In case custom `benchmark_bin` is supplied skip the check
2. In case `rpm` is not detected use `[ -x "$benchmark_bin" ]` (and warn the user that the version is not checked)
3. Add custom handling for each benchmark script to get the version from each benchmark (eg. via `fio -v`)
4. A combination of the above

I like the `(3)` the most as it should work for any distro but it might require more code in each script (although for majority of tools the `-v` plus a simple regexp should do...)

**Comment by ldoktor** [comment]
Note this does not really block me at this point as I am using rpm-based distro and I am installing system-wide `fio` to satisfy the check, but then running the benchmark with a custom-built `fio`. Still it'd be nice to lower the dependency on RPM.

**Comment by portante** [comment]
I agree, option (3) as presented sounds good, dropping the use of `check_install_rpm` entirely.  It also saves a who set of round-trips with `ssh` operations on client nodes.

This also would take care of issue #2233.

**Comment by portante** [comment]
Fixed by PR #2528.
