### ISSUE TITLE
pbench-index.py: obsolete error codes

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1763]
The pbench-index.py  error codes need some updating: on[ ll.90 and 91](https://github.com/distributed-system-analysis/pbench/blob/80c8d8e2fa8d99066bf9c637286f7729a5935b73/server/bin/pbench-index.py#L90), the error codes 10 and 11 are no longer generated, so the comments referring to them can be removed.

**Comment by riya-17** [comment]
@ndokos  10 and 11 seem to be used in [ll.349](https://github.com/distributed-system-analysis/pbench/blob/80c8d8e2fa8d99066bf9c637286f7729a5935b73/server/bin/pbench-index.py#L349) and [354](https://github.com/distributed-system-analysis/pbench/blob/80c8d8e2fa8d99066bf9c637286f7729a5935b73/server/bin/pbench-index.py#L354) respectively, are those conditions not valid, or am I looking at the wrong place?

**Comment by ndokos** [comment]
I think the question is whether either of those two exceptions is ever raised: if they are not, then they cannot be caught and the error codes are useless. Looking at the SorreportHostname exception, I'm pretty sure that nobody raises it: it's a user defined exception and there is no occurrence of that name anywhere in server code. The tarball.TarError exception is not defined by us, so it is conceivable that one of the tarball methods might raise it. That will require closer investigation I think.
