### ISSUE TITLE
Refactor Tool Meister work to move common variables, constants, methods, functions, and classes to a proper module

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1784]
The Tool Meister work provides a number of opportunities to condense code and re-use (not repeat) structures and definitions for variables, constants, methods, functions, and classes.  Move these to a proper Python3 module hierarchy would be great.

**Comment by zulcss** [comment]
This has been addressed in #1770

**Comment by portante** [comment]
Addressed in PR #2005 and furthered in PR #2076.
