### ISSUE TITLE
pbench-server dependencies

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1799]
Trying to start the pbench-server (by hand, in an scl rh-python36 environment, on RHEL7) I get:

```
 $ /opt/pbench-server/bin/pbench-server
Traceback (most recent call last):
  File "/opt/pbench-server/bin/pbench-server", line 6, in <module>
    from pbench.cli.server.shell import main
ImportError: cannot import name 'main'
```
and indeed I cannot find main in `lib/pbench/cli/server/shell.py`, so something is going awry: what exactly?

**Comment by ndokos** [comment]
PR #1800 fixes the above but there are more problems:

- The server starts up as a development server listening on http://127.0.0.1:8001/ - we'll need to get a WSGI environment for it.
- The systemd pbench.service file deals with the generic case (python3 without SCL, i.e. the Fedoras and RHEL8) but it does not deal with RHEL7 and SCL.

**Comment by portante** [comment]
> The server starts up as a development server listening on http://127.0.0.1:8001/ - we'll need to get a WSGI environment for it.

Filed: https://github.com/distributed-system-analysis/pbench/issues/1801

**Comment by portante** [comment]
> The systemd pbench.service file deals with the generic case (python3 without SCL, i.e. the Fedoras and RHEL8) but it does not deal with RHEL7 and SCL.

Filed: https://github.com/distributed-system-analysis/pbench/issues/1802
