### ISSUE TITLE
util-scripts test 53 randomly fails

### ISSUE THREAD

**Issue by Maxusmusti** [distributed-system-analysis/pbench#1817]
Appears to be an issue with tool ordering (or lack thereof). Chance of occasional:
*** 126,131 ****
  +++ test-execution.log file contents
  /var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x iostat
  /var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x mpstat
 -/var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x iostat
  /var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x mpstat
  --- test-execution.log file contents
--- 126,131 ----
  +++ test-execution.log file contents
  /var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x iostat
  /var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x mpstat
  /var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x mpstat
 +/var/tmp/pbench-test-utils/opt/pbench-agent/unittest-scripts/pidof -x iostat
  --- test-execution.log file contents
Likely to do with a lack of sorting in tool-meister-start, but unconfirmed.

**Comment by portante** [comment]
Closing in favor of #1807 previously reported.
