### ISSUE TITLE
Agent 0.70 Release Notes

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#1836]
Intended as a parking area for release notes.

- [x] The `pbench-cleanup` utility command is deprecated and will be removed in a subsequent release (see PR #1828)

- [x] The release takes in the latest code from stockpile, including support for GPU data collection that Keshav implemented

- [x] The new "dcgm" tool requires Python2, an Nvidia based install which might conflict with the Pbench Agent's Python3 requirement in some cases

- [x] Layout documentation for the new behaviors of the Tool Meister work

**Comment by portante** [comment]
First pass a set of release notes for v0.70.0 at https://github.com/distributed-system-analysis/pbench/releases/tag/untagged-6ff0f8df09183fb65424.

**Comment by portante** [comment]
Added the release notes as `doc/RELEASE-NOTES.md` as part of PR #1962.

**Comment by portante** [comment]
Release notes finalized via PR #1962 and at https://github.com/distributed-system-analysis/pbench/releases/tag/v0.70.0-beta.
