### ISSUE TITLE
md5sum of log.tar.xz does not match with the one store in log.tar.xz.md5 used for unit testing tarfile upload api

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#1840]
- md5sum of `lib/pbench/test/unit/server/fixtures/upload/log.tar.xz` does not match with one stored in `lib/pbench/test/unit/server/fixtures/upload/log.tar.xz.md5`. They should match for the unit testing
- Unit test of the upload api is not actually posting any data in the post request but just writing contents to a file based on the filename passed in the request header 
- Unit test fails for if we store the right md5sum (`md5sum log.tar.xz`) in .md5 file (I think its because we are not passing any data in the request)

**Comment by portante** [comment]
Fixed as of the combination of #1869 and #1843.
