### ISSUE TITLE
pbench-sysinfo-dump syntax + logic bugs

### ISSUE THREAD

**Issue by Maxusmusti** [distributed-system-analysis/pbench#1846]
opt/pbench-agent/util-scripts/pbench-sysinfo-dump: line 100: conditional binary operator expected
/opt/pbench-agent/util-scripts/pbench-sysinfo-dump: line 94: expected )
/opt/pbench-agent/util-scripts/pbench-sysinfo-dump: line 94: expected )
/opt/pbench-agent/util-scripts/pbench-sysinfo-dump: line 94: expected )
/opt/pbench-agent/util-scripts/pbench-sysinfo-dump: line 100: syntax error near _modules="date'
/opt/pbench-agent/util-scripts/pbench-sysinfo-dump: line 100: 		_modules="date host release"'

Once these are fixed, still another logic issue afterwards causing the final step to fail

**Comment by ndokos** [comment]
There is a quote missing on line 94.

**Comment by portante** [comment]
Yes, this was something I was supposed to fix a while back and dropped the ball.  Thanks for picking this up, @ndokos, and for filing an issue for it, @Maxusmusti!
