### ISSUE TITLE
Deprecation and deletion of "pbench-*"  benchmark RPMs from COPR

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1847]
We need to come up with a policy to deprecate and eventually delete the various "pbench-*" benchmark RPMs from COPR. `uperf` in particular is available from EPEL for all platforms.

We also need to continue building the same RPMs in the meantime and avoid COPR aging them out.

**Comment by portante** [comment]
@ndokos, can you start to enumerate what changes need to be made to this git repo for this issue?

**Comment by ndokos** [comment]
This should be tracked in JIRA.

**Comment by ndokos** [comment]
Apart from the changes in PR #2751  and PR #2749, this issue does not affect anything else in the GitHub repo. It is tracked internally in Jira as PBENCH-35.

**Comment by portante** [comment]
PR #2751 was needed to close this issue since we still had an explicit dependency.
