### ISSUE TITLE
Pbench backend user management

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#1889]
To support the dashboard "user" mock implementation in the product, we need to build out full CRUD support for users within the backend API. This would take over the current dashboard JavaScript GraphQL queries and product an abstracted user management and authorization API that could be shared by our dashboard UI as well as other scripting tools.

E.g.,

```
POST <server>/user/ {"username": "name", "email": "...", ...}
PUT <server>/user/{id} {edit ...}
DELETE <server>/user/{id}
POST <server>/login {"email": "...", "password": "..."}
```
The latter would return a sessionID that would be tracked in GraphQL / postgreSQL to manage token expiration and privileges associated with the user, and which would be returned to subsequent user-authorized backend API calls via the `X-auth-token` header.

We'll very likely want to consider managing explicit user privileges and possibly even groups; although we don't need to do all of this right away, the design should ideally make it easy to expand.

I'd suggest a new Python class to encapsulate the GraphQL and bcrypt code involved to make it easily accessible; although most interaction will occur from `api/__init__` REST APIs. Note that we'll also need to process `X-auth-token` in the server upload PUT API, which likely means that the copy/move results tool will need to be able to take `--user` and `--password` options, authorize the user, and include the appropriate upload header.

**Comment by npalaska** [comment]
Yes this will greatly simplify the dashboard side implementation of queries. We try to build the entire query in the dashboard right now.  The server APIs are just abstracting away the graphql and es actual endpoints from the user but user still has to do the relevant query we just take the query and reroute it to the appropriate endpoint. We need the user to just send the simple json object and the server should take care of building the actual query. Its easier to maintain (as the changes will happen only at one place and user shouldnt be bothered)

**Comment by dbutenhof** [comment]
While we're not 100% done with implementing "users", this seems to encapsulate the work already done and merged, so I'm closing it to reduce some of the noise.
