### ISSUE TITLE
pbench-clear-tools removes tool label

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#189]
pbench-clear-tools should not remove the tool label

**Comment by ndokos** [comment]
I don't understand the problem. Can you explain?

Also, I don't remember if we could unregister tools on a remote before, but I don't think that pbench-clear-toos can do that now. Is that something that we should consider adding (back)?

**Comment by atheurer** [comment]
The problem is if you clear just one tool (of many) on a remote system, the label also gets removed.  Removing the label when all of the tools are removed is probably fine.

**Comment by atheurer** [comment]
Also, yes, pbench-clear-tools can remove 1 or all tools on a remote host

**Comment by ndokos** [comment]
I meant that pbench-clear-tools does not take a --remote option, so it cannot clear the tools on just the remote: it can only clear the tools on the remote if you clear the tools everywhere.

I'll submit a PR for the label problem - thanks for the explanation.

**Comment by ndokos** [comment]
PR #203 merged.
