### ISSUE TITLE
no documentation?

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#1899]
imagine my surprise when I went to the README.md for pbench and clicked on [the links in this section](https://github.com/distributed-system-analysis/pbench#how-is-it-installed) and got 404 (not-found) errors.   Am I just unlucky? Does this need update?   Also, is there documentation for OpenShift use specifically?

**Comment by portante** [comment]
Yes, we have to fix that.  See #1892.

**Comment by portante** [comment]
@bengland2, here is the PR (https://github.com/distributed-system-analysis/pbench/pull/1908) to fix the README on `master`, will back-port to the `b0.69` and `b0.70` branches.
