### ISSUE TITLE
Fix the agent installation guide in the current docs

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1909]
The agent installation guide in the current docs (https://distributed-system-analysis.github.io/pbench/start.html and then click on "Install") is badly outdated. We need to move the internal installation guide to the public site: most of it is on the Ansible playbooks and roles that are available publicly. An example inventory file can be added to indicate what needs to be done for a particular installation.

The FAQ should also be moved to the public docs (and updated!) .

**Comment by portante** [comment]
@ndokos, is this issue addressed by #1923?

**Comment by pravins** [comment]
I see, @riya-17 has created 2 documentation. If we can simply move those as it is to present page, i think that will fix this issue. We can ask few people to use those documents and update this page.

**Comment by ndokos** [comment]
Fixed by internal gerrit review 308059.
