### ISSUE TITLE
Add a simple "pbench set controller" API to change the name of the controller used on the pbench server

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1945]
There are times when the user want to track the pbench result tar ball collected by the agent using a name other than the one determined by `hostname -f` and the `${full_hostname}` variable (see also #1933, and #1935).

**Comment by RobertKrawitz** [comment]
Yup, this is what I need for bench-army-knife.

There should be a way to determine whether this API is available.
