### ISSUE TITLE
pbench-user-benchmark still calls stop/start-tools instead of pbench-start/stop-tools

### ISSUE THREAD

**Issue by arcolife** [distributed-system-analysis/pbench#195]
On calling pbench-user-benchmark, receiving these warnings: 

```
***************************************************************************
WARNING: the script "stop-tools" has been renamed to "pbench-stop-tools" 
Please fix your scripts: this compatibility layer will go
away in release 0.38 (approximately 2016-04-04).
The old name "stop-tools" will NOT work after that - you have been warned!
***************************************************************************
```

__..running on r7.2, pbench version 0.36__

I'm not calling start/stop tools. These are calls probably made from within pbench-user-benchmark. ..perhaps the calls to start/stop/postprocess tools haven't been replaced yet?

**Comment by ndokos** [comment]
Yes, there are three bugs: see PR #191 and #194 for the first two fixes. The third one is a check in agent/profile that I'm going to submit shortly.

**Comment by ndokos** [comment]
PR #196 has been merged as well. Closing this issue.

**Comment by arcolife** [comment]
thanks! yay. this would've inundated my logs otherwise.
