### ISSUE TITLE
Verify that `agent/base:is_redhat` function works properly under CentOS

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#1950]
We need to verify that `agent/base:is_redhat` function works properly under CentOS.

**Comment by ndokos** [comment]
What does `work properly` mean? Should it succeed or should it fail?

**Comment by portante** [comment]
> Use `_pbench_` prefixed env var for host names #1934

@ndokos, this came from your comment: https://github.com/distributed-system-analysis/pbench/pull/1934#discussion_r515956554.
