### ISSUE TITLE
Sidebar in documentation website overlaps with the footer

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench#1951]
The sidebar in the documentation website at https://distributed-system-analysis.github.io/pbench/doc.html overlaps with the footer of the website.

**Comment by anishaswain** [comment]
@aquibbaig can you please add a screenshot int he description and share your screen resolution?

**Comment by aquibbaig** [comment]
Resolution: 1920*1080

![Documenation website](https://user-images.githubusercontent.com/26324376/98078014-3d96d480-1e3f-11eb-8583-231a5b55dce3.png)

**Comment by portante** [comment]
@anishaswain, was this fixed by #1952?

**Comment by anishaswain** [comment]
> @anishaswain, was this fixed by #1952?

Yes @portante
