### ISSUE TITLE
Test failure in util-scripts/test-51

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#1953]
I get a test failure (sorting) on utils-scipts/test-51:

*** /home/nick/src/github/pbench/worktrees/portante-tox/agent/util-scripts/gold/test-start-stop-tool-meister/test-51.txt	2020-11-04 10:31:39.476131923 -0500
--- /var/tmp/pbench-test-utils/output.txt	2020-11-04 10:35:20.003134030 -0500
***************
*** 4,11 ****
  starting tool data sink
  starting localhost tool meister
  waiting for all successfully spawned SSH processes to show up as subscribers
- channel payload, "'{"hostname": "testhost.example.com", "kind": "ds", "pid": NNNNN}'"
  channel payload, "'{"hostname": "testhost.example.com", "kind": "tm", "pid": NNNNN}'"
  --- Finished test-51 test-start-stop-tool-meister (status=0)
  +++ pbench tree state
  /var/tmp/pbench-test-utils/pbench
--- 4,11 ----
  starting tool data sink
  starting localhost tool meister
  waiting for all successfully spawned SSH processes to show up as subscribers
  channel payload, "'{"hostname": "testhost.example.com", "kind": "tm", "pid": NNNNN}'"
+ channel payload, "'{"hostname": "testhost.example.com", "kind": "ds", "pid": NNNNN}'"
  --- Finished test-51 test-start-stop-tool-meister (status=0)
  +++ pbench tree state
  /var/tmp/pbench-test-utils/pbench

**Comment by portante** [comment]
Closing in favor of #1954.
