### ISSUE TITLE
More flexibility in managing index prefixes

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#1969]
The current dashboard code is wired to a particular index version through the `config.json` file; e.g., `v5.run.`.

When absorbing the query logic into the Pbench web server APIs (e.g., `/api/v1/controllers/list`) I hardcoded the version; however this is not a good long-term solution.

1. This should be tied to the index template discovery logic in `indexer.py`, probably persisting the index names and versions discovered in a database (e.g., Redis);
1. However, we also want the option to deploy multiple dashboard using the same server to process a "previous version" during a migration period. One option would be an optional HTTP header that would default to the "active" version but could be overridden to select the "previous" version. This might imply that Pbench server upgrade would "demote" the current "active" index version data (in Redis, Postgres, etc) to "previous" and harvest templates to create the new "active" version map.

This needs to be considered as we move forward with 0.71; it would be nice to have this resolved before we finalize the release.

**Comment by portante** [comment]
Won't fix since the Dashboard will no longer be exposed to Elasticsearch index names.
