### ISSUE TITLE
`_PbenchLogFormatter.format()` doesn't handle existing `asctime` property.

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2003]
This seems to have been an old problem that something new I pulled in (possibly requests_mock) is now triggering in my `query_controllers.py` context. The `_PbenchLogFormatter.format()` method tries to format UTC time from a current value of `record.asctime` if the property exists. However, if it does exist, it should be a string, which causes `datetime.utcfromtimestamp()` to throw `TypeError` ... and as this is unhandled, Python displays traceback.

Because the `asctime` property is reserved and defined, but not populated until it hits a formatter, this suggests that we've never before run with a competing formatter that added `asctime`, and we've always taken the `AttributeError` and generated a fresh timestamp. Now, something else is populating `asctime`, with a string, and we're taking the `TypeError` instead,.

The most likely fix would seem to be to format using `record.created`, which is the `time.time()` value captured when the `LogRecord` was created.

**Comment by dbutenhof** [comment]
For reference, the current code is:

```
        if self._fmt.find("{asctime}") >= 0:
            try:
                record.asctime = datetime.utcfromtimestamp(record.asctime).isoformat()
            except AttributeError:
                record.asctime = datetime.now().isoformat()
```

That is, if the logging format includes an ASCII time, try to replace the current `LogRecord`'s `asctime` property with a reformatted ISO UTC date string. If the property doesn't exist, Python raises `AttributeError` which causes Pbench to format a new date string from the current time.

One fix is to simply replace the reference to `record.asctime` (a string) with `record.created` (the `time.time()` value recorded when the `LogRecord` was created). Only if that property doesn't exist (which should never be the case) would we create a date string from the current time:

```
        if self._fmt.find("{asctime}") >= 0:
            try:
                record.asctime = datetime.utcfromtimestamp(record.created).isoformat()
            except AttributeError:
                record.asctime = datetime.now().isoformat()
```

While that seems reasonable, I don't think we should ever expect that `record.created` might not exist, so the exception handler here is probably pointless.

Another possibility is to simply accept an existing `record.asctime` as-is rather than blindly replacing it. The risk here might be that it's already been formatted as a local time, whereas we want to see UTC times; blindly replacing it avoids that ambiguity.

**Comment by portante** [comment]
So let's get to the bottom of what code is adding the `asctime` field with a value that is not a string.  The [LogRecord](https://docs.python.org/3/library/logging.html#logrecord-attributes) clearly state it is supposed to be a string.

Do we know what type it is when the error occurs and what its `repr()` renders?

**Comment by portante** [comment]
This error only seems to be happening with PR #1914.  The errors are not raised on [`master`](http://jenkins.perf.lab.eng.bos.redhat.com/job/pbench-ci-multi/job/master/12/console).

**Comment by dbutenhof** [comment]
> So let's get to the bottom of what code is adding the `asctime` field with a value that is not a string. The [LogRecord](https://docs.python.org/3/library/logging.html#logrecord-attributes) clearly state it is supposed to be a string.
> 
> Do we know what type it is when the error occurs and what its `repr()` renders?

No, sorry; I guess I wasn't clear enough. That's backwards. Our code is incorrectly expecting that `asctime` (if it exists) is a binary timestamp.

Whatever is now populating the `asctime` property is doing it correctly. It's a "human readable ASCII time string", precisely as required by the spec, but our code can't handle that case and blows up with `TypeError` because a properly formatted human readable ASCII time string isn't an `int` as required by `utcfromtimestamp()`.

This has to mean we've simply never encountered that case; this code snippet has _always_ taken the `AttributeError` path and generated a new date string with the "wrong" binary time (though it's probably off by a millisecond, if that), by using `now()` instead of the `record.created` that was captured when the `LogRecord` was created (and which was almost certainly used to construct the current `record.asctime` we're stumbling over).

**Comment by dbutenhof** [comment]
> This error only seems to be happening with PR #1914. The errors are not raised on [`master`](http://jenkins.perf.lab.eng.bos.redhat.com/job/pbench-ci-multi/job/master/12/console).

Correct. I added something that's registering its own `Formatter` subclass and decorating the `LogRecord` with an `asctime` property before we get it. The thing is, regardless of what's doing this, it's quite correct, and our code is wrong. If we "solve" it by simply getting rid of that, we're just ignoring the bug in our own code and it's bound to bite us later.

As I mentioned above, it does present the option of simply accepting an existing `asctime` value instead of replacing it. If we do that, we risk logging in local time despite our intent to log in UTC. One possibility here would be to use the `Formatter.converter` attribute to force every `Formatter` subclass using `formatDate` to generate UTC; but that won't help if the other formatter is, like us, ignoring all that mechanism and hardcoding the conversion and formatting.

**Comment by portante** [comment]
> The thing is, regardless of what's doing this, it's quite correct, and our code is wrong.

Agree.  You are correct.  I looked at the original code [this was taken from](https://github.com/openstack/swift/blob/1d4249ee9d176d5563631521fb17aa24baf7fbf3/swift/common/utils.py#L2092) and they are using the `formatTime()` of the formatter.  This is a mistake I made pulling this code over.

We should do the same thing, invoke `formatTime()`, but override `formatTime()` in our formatter to use UTC.  And given pyexbulk is "opinionated", do the same thing there.

**Comment by dbutenhof** [comment]
> We should do the same thing, invoke `formatTime()`, but override `formatTime()` in our formatter to use UTC. And given pyexbulk is "opinionated", do the same thing there.

We can override `Formatter.datefmt` or simply pass our own fixed format string; or we can figure out the documented mechanism to override the default format using the `converter` attribute when we instantiate our formatter; e.g.,

```
        formatter = _PbenchLogFormatter(fmt=logfmt)
        formatter.converter = time.gmtime
```

or just seeing the `converter` property in our `_PbenchLogFormatter.__init__()`. Then, in theory, we could simply use the superclass date formatter because it'd pull that property.
