### ISSUE TITLE
WARNING: the script "metadata-log" has been renamed to "pbench-metadata-log" 

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#201]
seen during postprocessing on pbench-agent-0.36-93gace4263.noarch

**Comment by ndokos** [comment]
PR #202 

@jeremyeder: thanks!
The name was in a trap that is supposed to be triggered on receiving an INT or QUIT signal.  Is that how you encountered it? If not, there is something deeper going on.

**Comment by ndokos** [comment]
I believe this is fixed. If not, please reopen the issue.
