### ISSUE TITLE
Consider moving container registry to a config option, along with image name and tags

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2016]
See _original comment by @dbutenhof in https://github.com/distributed-system-analysis/pbench/pull/2015#discussion_r534240825_.

Let's consider moving the container registry used to pull images to a config option, along with image name and tags for the particular usage.

**Comment by Maxusmusti** [comment]
Is this still relevant? We are now using an installed prometheus executable rather than a container, so the code mentioned in the original comment no longer exists.
