### ISSUE TITLE
ansible task fails while installing pbench-server

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench#2030]
I was trying to install `pbench-server` using the command `ansible-playbook -vv --user=root -i {myserverhosts.inv} pbench-server-install.yml`. The installation fails at the following task.
```
TASK [pbench-server-vars : fetch the pbench install directory from remote] *****
task path: /home/abaig/Desktop/Work/Redhat/pbench/server/ansible/roles/pbench-server-vars/tasks/main.yml:7
fatal: [dhcp31-179.perf.lab.eng.bos.redhat.com]: 

FAILED! => {"changed": true, "cmd": "pbench-config install-dir pbench-server", 
"delta": "0:00:00.002808", "end": "2020-12-10 04:31:57.519513", "msg": "non-zero return code", 
"rc": 127, "start": "2020-12-10 04:31:57.516705", "stderr": "/bin/sh: pbench-config: command not found",
 "stderr_lines": ["/bin/sh: pbench-config: command not found"], "stdout": "", "stdout_lines": []}
```

**Comment by ndokos** [comment]
This is *probably* the same problem as the one described in #2138: if you try to install a 0.69.x pbench-server RPM but you use the playbooks/roles from the main branch, the result is as shown above. Granted, I cannot know for sure: there isn't enough detail above to know whether this is the actual scenario taking place, but it is suggestive.

**Comment by portante** [comment]
Please feel free to re-open if you determine that the RPMs used where from the `main` branch.
