### ISSUE TITLE
Uninstalling the pbench server deletes the whole /opt/pbench-server directory

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2042]
`yum erase pbench-server` removes the whole `/opt/pbench-server` directory, including things that are not put there by installing the RPM (e.g. the `pbench-server.cfg` file). The RPM should be restructured not to touch those.

**Comment by portante** [comment]
See https://github.com/distributed-system-analysis/pbench/blob/315ce8fca7d9357fb82326ed66e4ef34459aabec/server/rpm/pbench-server.spec.j2#L96.

**Comment by webbnh** [comment]
Confirmed:  this still happens in V0.71.
