### ISSUE TITLE
Refactor "Metdata" / "URL" model to hold required information in better format

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#2054]
I think I had in mind a bit more generalization than this, but it's OK to start. This is really just the dashboard "URL", which I'd seen as one particular metadata key. While we can generalize later, I'd thought in terms of mapping the "URL"/saved-view into a PUT ("key": "dashboard-view", "id": "session-id", "value": "config/description") where Pbench didn't need to understand that the dashboard-view value is config/description.

But this is fine; we can go with making the dashboard saved-view the first-order implementation of metadata and grow it from there after we figure out exactly what we want in the schema, how we handle singletons vs lists, datatypes, etc.

_Originally posted by @dbutenhof in https://github.com/distributed-system-analysis/pbench/pull/1937#discussion_r545907296_

**Comment by portante** [comment]
Long term we want to drop the URL storing model, see https://github.com/distributed-system-analysis/pbench-dashboard/issues/133.
