### ISSUE TITLE
The sosreport collect failed with latest sos-4.0-2

### ISSUE THREAD

**Issue by dulili** [distributed-system-analysis/pbench#2057]
when run pbench-fio there is error log "[pbench-sysinfo-dump]sosreport collection failed!"
The sos command change to sos report with latest sos-4.0-2.

**Comment by portante** [comment]
@dulili, can you trying out the `0.69.7-17g039fc810a` from https://copr.fedorainfracloud.org/coprs/portante/pbench/?  It is possible we have already fixed that.

**Comment by portante** [comment]
Looks like this was fixed in v0.70 with PR #1819 and #1848.
