### ISSUE TITLE
Add SIGHUP signal handler to the pbench indexer

### ISSUE THREAD

**Issue by riya-17** [distributed-system-analysis/pbench#2060]
SIGHUP: re-evaluate the list of tar balls to index after indexing of the current tar ball has finished

- Report the current state of indexing
            - SIGHUP
            - Current tar ball being processed
            - How many remaining
            - How many have been completed
            - Errors encountered
            - Handler Behavior:
            1. Kicks a special thread to log indexing state data
            2. No exception raised

**Comment by portante** [comment]
See PR #1940.
