### ISSUE TITLE
Visualization container clean, aisle 30 (use of magic colon)

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2078]
The `":"` seems like a bit of a "magic number" that's not really necessary here (you could have omitted the environment variable or set it to `""`), and a bit of documentation at least in the README might be in order here, but I won't worry about it too much. Maybe consider cleaning this up when you add the PCP visualizer path?

_Originally posted by @dbutenhof in https://github.com/distributed-system-analysis/pbench/pull/2075#discussion_r566192982_

**Comment by Maxusmusti** [comment]
Addressed in #2091
