### ISSUE TITLE
Need proper psycopg2 RPMs added as pbench-server RPM dependencies

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2094]
Server installation needs to install the psycopg2 module: the pbench-server service uses it to connect to the Postgres database. This can be done with a PyPI module: `pip3 install psycopg2-binary` or it could be done by installing the psycopg2 RPM (if available).

This will require a bit or research. Depending on the outcome, we either need to add the RPM as a requirement in the spec file, or add the PyPI module in requirements.txt.

**Comment by ndokos** [comment]
RHEL8 has an RPM for it:

    python38-psycopg2.x86_64                                    2.8.4-4.module+el8.2.0+5234+f98739b6                              rhel8-AppStream                 


So does Fedora:

    python3-psycopg2.x86_64                                                                                   2.8.6-1.fc33                                                                 updates

RHEL7 has SCL packages for python 3.4, 3.5, 3.6 and 3.8 - the 3.8 looks like this:

     rh-python38-python-psycopg2.x86_64                                             2.8.4-5.el7                                         rhel-server-rhscl-7-rpms   

So we could add it to the spec file server reqs.

**Comment by portante** [comment]
We should declare that we won't support the pbench-server code running on anything but non-SCL environments where Python 3.8 and later are available.

**Comment by ndokos** [comment]
The server `requirements.txt` file lists `psycopg2-binary`. I presume that's enough and that this issue can be closed. @npalaska, @dbutenhof: any objections?

**Comment by dbutenhof** [comment]
That's an interesting question. I have a vague notion that we ran into some sort of dependency problem last Thursday; but if so, I neglected to record it. I suppose I could try watching the video, but that's a frightening concept. And even if I'm right, I don't think it was this one. So ... maybe?

**Comment by ndokos** [comment]
I don't remember `psycopg2` problems (but that does not much). Let's leave it open until the next jam session then and see if it rears its ugly head. If not, we can close it then.

**Comment by portante** [comment]
> So we could add it to the spec file server reqs.

Let's definitely add them to the server RPM spec file as `Requires`.
