### ISSUE TITLE
How do we reconcile the existing satellite server work flow with the notion of users and PUT operations?

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2097]
From PR [2074](https://github.com/distributed-system-analysis/pbench/pull/2074#discussion_r564791026_)

----

Yes, I didn't really try to think about the satellite workflow. It's really going to become a "front end / cache" for the internal server; __but__ that thought raises a really intriguing question we'll have to resolve. Do we replicate the user database between the master and its satellites? Do they have different user databases? If so... how do we figure out what user to use when we pull a dataset from the satellite to the master?

I think I'm officially _not_ thinking about satellites in the context of the PR. They're effectively a `pbench-move-results` which doesn't fit at all in the new world. Your suggestion to change the shim to do a local PUT doesn't really help, either, because that doesn't address the user ownership issue.

**Comment by dbutenhof** [comment]
I very much like the idea Pete brought up in a 1x1 this morning, although there are a lot of details we need to resolve.

In essence, it means introducing a new satellite API that's effectively the `GET` equivalent of the current server `PUT` API that replaces the 0.69 `scp` to the server. The "main" server will now periodically attempt to `GET` data from the satellite. We should consider at least a second API to query whether there are any waiting data sets, and probably metadata like count, size, and name. The server could then sort by size and individually request each waiting data set individually.

There's also a potential to use a message broker system like `smee.io` to allow the satellite to deliver messages for which the main server (inside our firewall) can listen just as we do for external GitHub and internal Jenkins.

The remaining issue involves coordinating ownership data between the two servers. One possibility is for the main server to retain the live user database, and use an encrypted HTTPS PUT periodically to clone the database to the satellite server. (We could restrict this, by adding a user metadata attribute to mark an account as usable via satellite, and only replicate those users.) Any data `PUT` to the satellite must be associated with a "main" server user, and the agent needs to prove that it has authorization to store that data on the main server, not just the satellite. This is going to take a lot of careful thought to avoid security problems.

**Comment by dbutenhof** [comment]
Summary of a 1x1 conversation between @portante and me last week. We don't actually need a satellite server at all.

Our (fairly raw, but theoretically plausible) concept is that the satellite becomes nothing but an external reverse proxy server connected to the internal server by an SSH tunnel configured by something on the server. Such a "satellite" would need no local users, database, or file system, because any client connecting via PUT (and potentially additional APIs if we want, e.g., to use pbench-generate-token externally rather than having to use a token generated from inside the firewall) will actually be talking directly to the real internal server.

**Comment by webbnh** [comment]
So connect the dots for me:  if the end-user client still uses the 0.69 `scp` to submit results, how does a "reverse proxy server" provide the necessary support?  (I'll grant that, for a 0.7x client, we don't need anything more than a proxy/tunnel deployment, but I'm not seeing how that supports a 0.69 client; but, I concur that, even for a 0.69 client, the satellite server doesn't need a local notion of users.)

**Comment by dbutenhof** [comment]
No dots to connect. This is not a 0.69 compatibility story; it's a satellite story to allow a server to accept datasets from outside a firewall. This was previously a complete second server from which the main server would periodically grab data.

**Comment by portante** [comment]
From @dbutenhof: "The new Pbench server will drop support for an external satellite as it's almost impossible to support, instead building a secure authentication structure that allows us to expose the Pbench service outside the firewall... probably (eventually) as a managed Red Hat service."
