### ISSUE TITLE
Inconsistency in gold unittest tarballs

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2098]
A number of unit test tarballs have metadata where the run name doesn't match the actual tarball basename (e.g., testdir vs test-7.6.tar.xz). I had originally tried to build the Dataset name from metadata in the index case, and found that I was duplicating entries because index used the metadata name while others used the file name.

This is no longer an issue for dataset tracking, since I'm using the filename consistently everywhere.

The question here is whether these tarballs should be considered "corrupt" in a way that Pbench is apparently not currently detecting? Should the test tarballs (I think most of the 7x sets) be corrected? Should we be detecting and failing if we get real tarballs like this?

**Comment by portante** [comment]
We decided not to address this in the short term, and instead will address this concern via implementation of proper functional tests.
