### ISSUE TITLE
Specify owner, group, and mode when creating symbolic links

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2105]
In `server/ansible/roles/pbench-server-activate-setup-results-host-info/tasks/main.yml` we create symbolic links without specifying the `owner`, `group`, or `mode`.  This is generally not a problem, because the code runs with the expected owner and group, and the link is created with the default umask value.  However, it would be problematic if the implicit ownership requirement was violated or if the current umask value was overly restrictive, so the playbook recipe should specify these values explicitly (as do the previous recipes which create the files being linked to).  ([Discussion](https://github.com/distributed-system-analysis/pbench/pull/2040#discussion_r574020506))

**Comment by portante** [comment]
Since we are going to move away from file system-based data storage to an object-based storage sub-system, we decided this is not worth pursuing in the interim.
