### ISSUE TITLE
should we return "username" on successful user login

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench#2107]
We currently return a `message` and `user token` as response_object on a successful user login. If we do not return any user details such as "username" the redirection to the `profile/overview` page will take the username field from the login form than the response returned from the server, (which we could store, but currently we do not).

What if we returned a username along with the token only on a `200 OK` response status?

**Comment by npalaska** [comment]
We can certainly return a username, I will update the PR https://github.com/distributed-system-analysis/pbench/pull/1937 to reflect this change

**Comment by npalaska** [comment]
Closing this issue as its been addressed in PR #1937
