### ISSUE TITLE
Verify email after signup process

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench#2110]
This step would be an enhancement on top of our initial signup process. Ideally, we would want the server to send an email to the user's email and would update the user after success. A possible reason why this extra effort would come in handy for us is that it would prevent creation of unnecessary accounts.

On the implementation end, the user schema needs to include a `verified` field, which is updated on successful verification. Also, there needs to be an email service to send a URL to verify the mail id. We could reuse this service as a part of `password recovery` workflow. Our system however has to establish a way to link the URL back to the to-be-verified account.

**Comment by portante** [comment]
We are planning on employing "keycloak" going forward, which should take care of all this (we think).
