### ISSUE TITLE
security issues with jwt

### ISSUE THREAD

**Issue by aquibbaig** [distributed-system-analysis/pbench#2118]
I was exploring ways to securely store "json web tokens" on the frontend, seems like that is a common problem with most applications in terms of security. Three ways to store jwt in the frontend are:
- Local storage - Prone to XSS via `localStorage` object.
- Session storage - We lose data when we move to another tab/window or reload the page.
- Cookie - Prone to XSS via `document.cookie` and CSRF attacks.

What's the best way?

- Using a httpOnly cookie hides the cookie from js attacks and CSRF.
- Use the server to set the cookie on the frontend like for example: `resp.SetCookie` and the frontend gets the cookie.
- Serve frontend from the backend application

**Comment by aquibbaig** [comment]
Just came across this blog from [Hasura](https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/).

According to me, what we can do is the following:
- store the jwt (access token)  `in memory` as a js variable, therefore removing all chances of xss or csrf.
- That way it will expire when someone reloads the page.
- use something called as a `refresh token` stored as an HttpOnly cookie, which can be used to get the access token back for the user.

**Comment by aquibbaig** [comment]
@dbutenhof @portante @npalaska Just made a rough sketch of the workflows, if I have missed something please let me know.

## How login workflow should look like from the dashboard's persepective:
![User authentication_ Login](https://user-images.githubusercontent.com/26324376/109143575-3406e480-772e-11eb-9880-0f7ff8dbafa0.jpeg).

> Note that the expiry of the refresh token is much higher than access token, which means that if the user has lost access to refresh token he will be logged out of all his sessions in 15m (expiry of access token), provided that we request for new access token with each request.

## What happens when the user reloads the page
![User authentication_ Page refresh (1)](https://user-images.githubusercontent.com/26324376/109144059-b55e7700-772e-11eb-96e2-8f1b2b340215.jpeg)

Case to handle:
- What happens when the access token expires for some reason when you are making a request without reloading the page(expiry time of access tokens is pretty small)? That way you cant get an access token until you refresh and you'll be logged out. My idea is that you can check for the expiry of accessToken with every request you make and ask the server for a new one when it actually expires. That should handle the case.

**Comment by dbutenhof** [comment]
Hmm; interesting, but I'm going to have to read up a bit on these tokens and "httpOnly" cookie "refresh tokens". I don't really have a feel for how that works operationally at the server level yet.

I also don't think I like the idea of "quickly expiring" tokens for general client access; although it might be OK for a JS-driven front end, it sounds complicated and very unconventional for a Python or curl-driven client.

**Comment by aquibbaig** [comment]
> I also don't think I like the idea of "quickly expiring" tokens for general client access; although it might be OK for a JS-driven front end, it sounds complicated and very unconventional for a Python or curl-driven client.

The idea is that the access token needs to be short lived than the `refresh_token` and according to the use case it can be 15m, 2h and even 1d, also you have to recover a new access token in the background when it's lost. I think they have to compromise some security loopholes to make the token short.

 According to Hasura's documentation:
> But if I have a valid and signed JWT and someone steals it from the client, can’t they use my JWT forever?
Yes! If a JWT is stolen, then the thief can can keep using the JWT. An API that accepts JWTs does an independent verification without depending on the JWT source so the API server has no way of knowing if this was a stolen token! This is why JWTs have an expiry value. And these values are kept short. Common practice is to keep it around 15 minutes, so that any leaked JWTs will cease to be valid fairly quickly. But also, make sure that JWTs don’t get leaked.

**Comment by dbutenhof** [comment]
You can't use it "forever" because Pbench will stop accepting it when it expires or when the session logs out and we remove it from the access token database. But of course if people don't actually log out, that really depends on the encoded expiration timestamp in the JWT token.

Solutions like the one laid out here are difficult to use for testing and exploration from curl or Postman, and it also feels a bit like "security by obscurity" ... "you snagged a token once, but I'll bet you can't do it again before it expires" ... is that a realistic niche? Perhaps.

I'm going to have to find time to read through the entire article and do some additional research to really understand how this works and get a feel for the pros and cons. In any case, thanks for researching and writing this up, and it's an awesome place to start the conversation.

**Comment by aquibbaig** [comment]
Sure @dbutenhof!

**Comment by webbnh** [comment]
@aquibbaig, at this point we're moving out of my range of applicable knowledge.  Given that Dave is engaging, I think I'll step back.

**Comment by portante** [comment]
We believe our future switch to using keycloak will obviate this issue.
