### ISSUE TITLE
pbench-move-results  line 118: [: too many arguments again 

### ISSUE THREAD

**Issue by databloom** [distributed-system-analysis/pbench#2119]
The immediate error looks like a previous bug that I think was fixed by quoting conditional variables, this is against code pulled today (feb 22/21) (see rpms installed at bottom)

Post test run, if I execute  

#pbench-move-results --user=pbench

_[error][2021-02-22T21:58:52.584704816] ERROR: results host unreachable: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pbench-results-host-info.versioned/pbench-results-host-info.URL001 was not found on this server.

[debug][2021-02-22T21:58:52.591608860] the following ssh command failed: "ssh -q -i /opt/pbench-agent/id_rsa -o StrictHostKeyChecking=no <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /pbench-results-host-info.versioned/pbench-results-host-info.URL001 was not found on this server.</p>
</body></html> exit"_

However:

#ssh -q -i /opt/pbench-agent/id_rsa -o StrictHostKeyChecking=no pbench@pbenchserver
Last login: Mon Feb 22 23:00:26 2021 from 10.61.10.61

Pbench Results Server

-bash-4.2$ exit

Issue #1
I think I've misinstalled the keys or my pbenchserver uri for the ssh access problem. 

My pbench-agent.cfg:

[DEFAULT]
pbench_install_dir = /opt/pbench-agent
# CHANGE ME!
pbench_results_redirector = pbenchserver
# CHANGE ME!
pbench_web_server = pbenchserver 

Issue #2 

The Ansible playbooks installed demo.py and an Apache without configuration details for pbench.

Is there an online guide for how Apache is configured to support serving this URI ?

_The requested URL /pbench-results-host-info.versioned/pbench-results-host-info.URL001 was not found on this server._

Packages installed:

configtools.noarch                0.3.1-3                        @ndokos-pbench 
pbench-agent.noarch               0.52-2gd1023f4a                @ndokos-pbench 
pbench-dashboard.noarch           0.52-1gbb9ce25                 @ndokos-pbench 
pbench-dbench.x86_64              4.00-1                         @ndokos-pbench 
pbench-fio.x86_64                 3.3-2                          @ndokos-pbench 
pbench-iozone.x86_64              3.430-1                        @ndokos-pbench 
pbench-iperf.x86_64               2.0.5-1                        @ndokos-pbench 
pbench-linpack.x86_64             11.1.3-1                       @ndokos-pbench 
pbench-server.noarch              0.69.5-1g22ed51ea7             @copr-pbench   
pbench-smallfile.x86_64           1.9.1-1                        @ndokos-pbench 
pbench-stress.x86_64              1.0.4-1                        @ndokos-pbench 
pbench-sysbench.x86_64            0.4.12-1                       @ndokos-pbench 
pbench-sysstat.x86_64             11.2.0-1                       @ndokos-pbench 
pbench-uperf.x86_64               1.0.4-1                        @ndokos-pbench 
pbench-web-server.noarch          0.67-1g0ccc2265                @ndokos-pbench 

Thanks in advance !

**Comment by portante** [comment]
@databloom, what version of the pbench-agent are you using?  And what version of the pbench-server do you have installed?

**Comment by ndokos** [comment]
@databloom: it seems you have installed a very old version of pbench-agent: the installed package list says `0.52-2`. The current version is `0.69-4`. Please upgrade: a lot of things has changed since 0.52-2.

And have you installed a server? What version? How did you install it? You seem to be able to ssh to the server, but it seems that the server does not have the underlying infrastructure set up correctly.

**Comment by databloom** [comment]
I'll get everything up to 0.69-4, let's close this

**Comment by databloom** [comment]
Closing to sync all components to current codebase

**Comment by databloom** [comment]
Not seeing external docs on how to install pbench-server, pbench-dashboard, only ansible playbooks btw. Flying blind a bit on how the agent registered the uploaded tarballs to the pbench-server and how pbench-dashboard is installed and where apache fits into it all.

**Comment by ndokos** [comment]
@databloom: indeed, we have concentrated more on the agent installation docs and less on server installation docs (internally, we run a server that can be used by other groups, but that won't help externally). We are going to get server docs out eventually, but we need to clean up the ansible playbooks first.

If I may ask, how did you hear about pbench? And what are you planning to do with it? Having an idea about that will help us plan a bit better. Thanks for any info you can share!
