### ISSUE TITLE
Re-implement pbench-kill-tools to hunt down tool meisters on remote nodes and stop them

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2120]
Based on review feedback in PR #2005, we really should re-implement `pbench-kill-tools` to communicate with the Redis Server, find all the remote pids of Tool Meisters, and ssh to those hosts to kill those processes.

**Comment by npalaska** [comment]
Do we still want to do this as the pbench-kill-tools is deprecated and already a no-op?

**Comment by portante** [comment]
@ndokos, let me know if you are still planning on driving this work (you were assigned it back in October of 2021).  If you are not planning on driving it, I'd like to own this issue to find a solution.  That is, unless @dbutenhof wants to own it given his comments on #2666 and work on PR #2625.

**Comment by dbutenhof** [comment]
I had planned to concentrate on Jira along with trying to do some refactoring on `pbench-tool-meister-start` and `pbench-tool-meister-stop` to enable better unit testing... in the immediate short term. I'd be more than happy to let you take this one on.
