### ISSUE TITLE
Add ability to run PCP as a transient tool as well as a persistent tool

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2122]
As of PR #1986, we have PCP supported as a persistent tool.  This is great for some environments, but for others, where network activity is unwanted, we'd like the ability to run the PCP tool as a transient tool, where the `pmcd` and `pmloggers` are both run by the Tool Meister, with the data being collected locally to the Tool Meister.  The collected would be sent to the Tool Data Sink when `pbench-send-tools` is requested.

**Comment by Maxusmusti** [comment]
SOLUTION AT: https://github.com/portante/pbench/pull/14

**Comment by portante** [comment]
Implemented in PR #2196.
