### ISSUE TITLE
We need to restrict the external user from updating auth_tokens 

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#2127]
We internally modify auth tokens associated with a user when a user re-login. However, we need to add an interface to avoid end-user trying to update the auth tokens.

_Originally asked by @webbnh in https://github.com/distributed-system-analysis/pbench/pull/1937#discussion_r586822648_

**Comment by dbutenhof** [comment]
Note that an easy way to accomplish this (and you've already started on this path) is to treat that client JSON stream as a completely separate "translation" of the internal object. That is, we never accept a `User` object from an API, only a JSON structure containing specific managed field values to apply to internal object properties. And, vice versa, we never actually return an internal object, but a limited/filtered JSON representation of specific managed object properties.
