### ISSUE TITLE
Need to allow pbench-fio to match newer versions rather than exact

### ISSUE THREAD

**Issue by frival** [distributed-system-analysis/pbench#2142]
Right now `pbench-fio` will only run if it detects `fio` version 3.21 is installed - any other version and `pbench-fio` exits with an error.  However, the pbench-agent can coexist with more than one fixed major/minor version and we'll likely run into situations where newer major (and possibly minor) versions of RHEL ship a newer `fio` than the exact match.  Most likely a simple `>=` rather than `=` test would be sufficient; hopefully there doesn't need to be a list of known-broken versions as that would be ... unfortunate.

**Comment by portante** [comment]
We could consider using `rpmdev-vercmp` from the `rpmdevtools` package.  See https://stackoverflow.com/questions/2996279/how-does-yum-compare-versions.

This would allow us to modify `agent/util-scripts/require-rpm` to see if the required RPM is the same or older than the installed version.  But, it would add a new dependency.

Seems like it would be worth it.

**Comment by portante** [comment]
See also https://utcc.utoronto.ca/~cks/space/blog/linux/RPMShellVersionComparison.

**Comment by portante** [comment]
#2210 was revoked after the merge on the `main` branch.  New fix in PR #2234.
