### ISSUE TITLE
New pbench-generate-token tool is not installed in/by the RPM

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2146]
We missed one problem with this merged code: when building an RPM we don't include the new command.  We need to add it for the RPM in `agent/Makefile`.

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench/issues/2137#issuecomment-804285457_

**Comment by webbnh** [comment]
Click is meant to be self-discovering, so having the tools installed via a static Makefile seems like it might be swimming upstream. We should discuss how we want to move forward for the Click-based tools. (For testing, I installed it via `pip install --editable .`, so I imagine that there is some similar command that we would want the Makefile to run, rather than doing it via an explicit or bulk copy operation.)

**Comment by portante** [comment]
The `agent/Makefile` runs the setup.py install, and then creates a source tar ball so that we can build in COPR.  We just need to update the Makefile so that it knows what to include.
