### ISSUE TITLE
CLI user management tool

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2183]
We could use a CLI user management tool. (Note we may get this for free with integration into a support identity manager, but in the interim this would be convenient for testing and administration.)

This would allow listing, creating, modifying, and deleting users from the server command line.

Among other things, our setup procedure might use this to create the "admin" user on installation.

**Comment by webbnh** [comment]
@npalaska, I suggest that you ask Nikhil -- he's looking into that.

**Comment by webbnh** [comment]
Presumably, we'll have/want a GUI for this -- a web page which lists users and offers various ways of manipulating them.  But, as Dave says, we'll presumably want a CLI version as well, for all the reasons that he lists.

But, our user management capabilities will be greatly dependent upon our implementation.  If we end up integrating RH SSO, then the server-side support for user management will have to be able to respond to requests from the GUI or the CLI by interacting with SSO.  If we go with some other identity management system (Auth0, Cognito, you-name-it), then what we can do and how we do it will be dictated by the system's capabilities.

But, for the moment, we can presume that we'll be able to

- list existing users
- delete users
- create users
- modify users' characteristics and capabilities (whatever those are and/or evolve to be)

I expect that what Dave is envisioning is another simple tool like `pbench-generate-token` which grabs a few items from the user and makes a request to the server REST API.  Presumably it will need a token...which creates an interesting chicken-and-egg problem for creating the "admin" user on installation, but maybe we can find a clever way around that (like, if the server determines that are no existing users, then it's willing to accept the first request even without a valid token, especially if that request is to create the admin user...).

(And, yes, I know that @npalaska _is_ Nikhil... :-D )
