### ISSUE TITLE
We need some efficiency metrics for fio tests

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#22]
Often using a result metric based on throughput is not enough to compare one test to another, because the bottleneck may come from a hard limit like network link speed or drive speed.  Having an alternative metric that shows efficiency helps us better understand the result.  For example, IOPS/cpu, or Mbps/CPU.  We need to add some metrics like this for fio.

**Comment by portante** [comment]
We talked about implementing this when #38 is done.

**Comment by atheurer** [comment]
I am going to close this and create a new issue for modular efficiency metrics for all benchmarks
