### ISSUE TITLE
bench-scripts should be renamed in the Getting started guide

### ISSUE THREAD

**Issue by smalleni** [distributed-system-analysis/pbench#224]
Currently the guide talks about benchmarks with name pbench_fio etc, but looks like the bench-scripts have been renamed to us a '-' instead of an underscore

**Comment by lukas-vlcek** [comment]
Also "register-tool-set" has been renamed to "pbench-register-tool-set".

**Comment by ndokos** [comment]
I believe PR #266 and #267 have addressed this issue, so I am closing it. If you think there are problems still, please reopen it.
