### ISSUE TITLE
Add builds for Fedora 24

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#226]
Fedora 24 alpha is out, can you please begin building packages for Fedora 24?  Note that for Ansible to work against Fedora 24 cloud images, you must have these:

```
dnf install -y python libselinux-python python-dnf
```

**Comment by ndokos** [comment]
I rebuilt most of the pbench-<benchmark> (plus pbench-sysstat)  RPMS for Fedora 24 on COPR. iperf is the only exception: it's a bit broken on F24 and I haven't figured out how to fix it yet.

I still need to rebuild pbench-{agent,server,web-server} RPMs. For the agent, I'll probably wait until v0.38 is released.
