### ISSUE TITLE
`pbench-make-result-tb` does not seem to create a tar ball when `--target-dir=./` is provided

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2270]
pbench-agent-0.69.7

```
$ pbench-make-result-tb --result-dir=/var/lib/pbench-agent/fio__2021.04.21T09.19.31/ --target-dir=./
```

Won't create tarball.

**Comment by ndokos** [comment]
I think this is just a permissions problem: if I run it as root, it succeeds. Are we expecting it to succeed if we don't run it as root?

Eventually, of course, we won't to get away from root, but I don't think 0.69.7 does that.

**Comment by portante** [comment]
> I think this is just a permissions problem: if I run it as root, it succeeds. Are we expecting it to succeed if we don't run it as root?

No.

> In fact, if I run it non-root but in a directory where I have write permissions, it _almost_ succeeds: it complains about permissions on /var/lib/pbench-agent/pbench.log and if I open _that_ up for writing by everybody, then it succeeds.

You if you have a `pbench-agent.cfg` file that uses a `pbench_run` directory this writable, everything thing should work.

> Eventually, of course, we want to get away from root, but I don't think 0.69.7 does that.

You can get away with that if you change the configuration file to not reference `/var/lib/pbench-agent`.

**Comment by portante** [comment]
Closing as invalid since the `b0.69` code branch requires `root` by default.  Non-root users have to change the configuration file, and we won't be making the kinds of changes we need for this old branch.

Marking for future work.
