### ISSUE TITLE
Refactor `verify_user` method in `auth` module

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#2275]
I feel like the structure of this code is obfuscating its function.  `verify_user()` is really "determine whether the requesting user matches the specified username and return the requesting `user` value", which really isn't very much code.  (That is, it seems like, as things are, the situation would be clearer if the subroutine body were just in-line'd.)  And, then, we have to layer the admin checks on top of that.

I think the code would be better if the subroutine returned a boolean indicating whether the current user had the right to update/destroy the specified user and also, for convenience, the specified user's `User`.  That would encapsulate most of the `is_admin()` checks in one place, and the calling code could do a simple check of the "verified" value.  That is, if the specified user doesn't exist, the caller gets a `False`; if the requestor is an admin, the caller gets a `True`; otherwise, the caller gets a `True` only if the target matches the requestor.  And, we get the target back, which (I think) saves us a database query (i.e., I don't think we need to query the database for the requestor's `User` -- I think that comes from the `Auth` `current_user()` call -- so we only need to query for the target's `User`).  The caller can determine the "user does not exist" case based on a `user == None` return value, and otherwise a `verified == False` means "not authorized".

I don't think it's helpful to reuse the `user` variable -- it initially represents the requestor, but it is later overwritten with the target, and that's potentially confusing.

_Originally posted by @webbnh in https://github.com/distributed-system-analysis/pbench/pull/2218#discussion_r625247721_

**Comment by portante** [comment]
We believe our adoption of keycloak in the near future will render this meaningless.
