### ISSUE TITLE
Use the `geerlingguy.epel` role from Galaxy and get rid of our implementations

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2293]
I'm not fluent in Ansible Galaxy, and probably it's more trouble than it'd be worth to package a separate "collection"? But since this role (and maybe others) seem to be identical for Agent and Server sides, would it be possible/practical to publish a single role that can be referenced by both sides? (And potentially used elsewhere?)

_Originally posted by @dbutenhof in https://github.com/distributed-system-analysis/pbench/pull/2292#discussion_r628148516_

**Comment by ndokos** [comment]
We should be using the `geerlingguy.epel` role from Galaxy and get rid of our implementations.

**Comment by ndokos** [comment]
We are no longer installing EPEL through the `pbench_agent_install.yml` playbook. The addition of it in PR #2292 was undone with PR #2947.  Closing as `wontfix`.
