### ISSUE TITLE
gunicorn logs directory, `/var/log/pbench`, needs to be created by RPM owned by `pbench` user

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2303]
The gunicorn logs directory, `/var/log/pbench`, needs to be created by the RPM, owned by `pbench` user, on install.

**Comment by dbutenhof** [comment]
Well, yes; but only if we want separate gunicorn log files. You'd previously expressed the preference for merging them into the pbench-server Logger, which I believe we can do.

These jam errors came from the fact that I'd patched `shell.py` to add `--access-logfile` and `--error-logfile` options to the gunicorn spawn as a simple workaround to see what's happening. I pointed them arbitrarily at `/var/log/pbench` but forgot to create the directory before restarting the server.

We already have #2261 to record the need to add access/error logging to our gunicorn configuration.

**Comment by portante** [comment]
Closing in favor of #2261.
