### ISSUE TITLE
It appears `fio-postprocess` is operating O(N2) or O(N3) processing log files

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2306]
Place-holder issue based on evidence seen that for a 24-hr fio job, the processing of the resulting log files is O(N2) or O(N3), with an observed 1.4GB of resident memory for the process.

**Comment by portante** [comment]
Core problem appears to be the use of `value_exists` (https://github.com/distributed-system-analysis/pbench/blob/19c8b975a90e8e4bf4c48d9f7e05533ee93a7a76/agent/bench-scripts/postprocess/BenchPostprocess.pm#L443) in `fio-postprocess` (https://github.com/distributed-system-analysis/pbench/blob/5af8529739b718bd4b7df5cc5f7541eb41a85590/agent/bench-scripts/postprocess/fio-postprocess#L261), where every line read from the file is compared against every previous line read from the file.

Instead the timestamps should be taken advantage of to see if they go backwards, so this can be checked in O(N) instead of O(N^2).

**Comment by portante** [comment]
The `value_exists` function is only used by `fio-postprocess`.

**Comment by portante** [comment]
After fixing the behavior to remove `value_exists` calls from the main processing loop, the next blocker is `calc_aggregate_metrics`.

From what I can tell, it gratuitously used `get_timestamps()`, and then its uses `calc_sum_series()` which uses the `get_value()` which looks to operate O(N^2).

**Comment by webbnh** [comment]
I've been reworking the basic aggregate data structure which holds the time-series data.  I've got the changes implemented up to the call to `calc_aggregate_metrics()`.  The improvement in performance of that segment has been dramatic (on the order of 10x).  I've pushed the changes through the first part of that routine, and now I'm diving into the subroutines which it uses -- everywhere I look, I keep running into additional O(N^2) operations.  I'm hoping that the changes that I'm making will make them all linear.

**Comment by webbnh** [comment]
I've completed the changes to the `fio-postprocess` script and its dependent module.  The good news is that it still produces results identical to the `main` branch, and it now runs Dave's large case in under 5 minutes.  The bad news is that many of the changes affected the lower-level code which _other_ post-processing scripts depend on, so I cannot merge the changes until I integrate them with the changes.

**Comment by webbnh** [comment]
I've completed the changes required to address this problem and put them up for review.

**Comment by webbnh** [comment]
I had to put the review in "draft mode" while I chased down issues with testing.  Those issues have now been resolved, and the PR is ready for review.
