### ISSUE TITLE
Drop Apache for Nginx to front Gunicorn

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2314]
The Apache configuration we are currently using is not correct.  The guidance given by the Gunicorn documentation is to use a proxy, but gives a detailed example using Nginx.

We deployed it in testing against a default nginx install and it working using:

```
[root@pbench-staging nginx]# git diff
diff --git a/conf.d/default.conf b/conf.d/default.conf
index ff2ced6..5f4766f 100644
--- a/conf.d/default.conf
+++ b/conf.d/default.conf
@@ -1,9 +1,32 @@
+upstream app_server {
+    # fail_timeout=0 means we always retry an upstream even if it failed
+    # to return a good HTTP response
+
+    # for UNIX domain socket setups
+    # server unix:/tmp/gunicorn.sock fail_timeout=0;
+
+    # for a TCP configuration
+    server localhost:8001 fail_timeout=0;
+}
+
 server {
     listen       80;
     server_name  localhost;

+    client_max_body_size 30G;
+
     #access_log  /var/log/nginx/host.access.log  main;

+    location /api {
+        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
+        proxy_set_header X-Forwarded-Proto $scheme;
+        proxy_set_header Host $http_host;
+        # we don't want nginx trying to do something clever with
+        # redirects, we set the Host: header above already.
+        proxy_redirect off;
+        proxy_pass http://app_server;
+    }
+
     location / {
         root   /usr/share/nginx/html;
         index  index.html index.htm;
```

We still need to ensure we can serve local files properly with the `autoindex` feature.  But this appears to be the direction we should take.

**Comment by portante** [comment]
- [ ] We'll want to configure nginx to log to syslog

- [ ] We should consider using `unix` sockets for the connection between Nginx and Gunicorn

- [ ] We may also want to create a container combining the nginx deployed along side the pbench-server Gunicorn app

**Comment by dbutenhof** [comment]
> We still need to ensure we can serve local files properly with the autoindex feature. But this appears to be the direction we should take.

This should be just a matter of removing `/etc/httpd/conf.d/pbench.conf` and restarting Apache ... and making sure that NGINX redirects anything that's not `/api/` to it. _Or_ of course either somehow configuring NGINX to serve files ... or adding the result file path `GET` to Pbench now rather than later... in either case we could simply drop Apache entirely.
