### ISSUE TITLE
Add generic error handling to support common logging/abort patterns

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2324]
Potentially.  There are ways to add generic error handling (see https://python.plainenglish.io/python-web-development-with-flask-error-handling-36349a7f82c).

This specific problem is that `abort()` does not give us a way to add color to what is logged.

But in another commit, we could re-work this code that it only raises an exception class we know about where, we provide a response code, message (optional), and logging context.

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench/pull/2317#discussion_r634747252_

**Comment by webbnh** [comment]
According to the [Flask documentation](https://flask.palletsprojects.com/en/2.0.x/errorhandling/#unhandled-exceptions) unhandled exceptions do in fact result in a `500/Internal Server Error` response.  If we don't like the default handling of that, we can hook it using [flask.Flask.handle_exception()](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.handle_exception).

Likewise, [`flask.abort()`](https://flask.palletsprojects.com/en/2.0.x/api/#flask.abort) apparently raises exceptions, as well.  I believe that these are logged by default, and if we don't like the default handling, [they can be hooked as well](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.handle_http_exception).

Apparently, [Flask uses standard Python Logging](https://flask.palletsprojects.com/en/2.0.x/logging/#logging), but it's fully configurable.

So, really, I'm not sure the API code (at least at the top level) needs to be doing any exception handling or logging (except for special cases, like restoring invariants and other clean-up) -- we should be able to get Flask to do all that stuff for us.

**Comment by webbnh** [comment]
According to the [Flask documentation](https://flask.palletsprojects.com/en/2.0.x/errorhandling/#unhandled-exceptions) unhandled exceptions do in fact result in a `500/Internal Server Error` response.  If we don't like the default handling of that, we can hook it using [flask.Flask.handle_exception()](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.handle_exception).

Likewise, [`flask.abort()`](https://flask.palletsprojects.com/en/2.0.x/api/#flask.abort) apparently raises exceptions, as well.  I believe that these are logged by default, and if we don't like the default handling, [they can be hooked as well](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.handle_http_exception).

Apparently, [Flask uses standard Python Logging](https://flask.palletsprojects.com/en/2.0.x/logging/#logging), but it's fully configurable.

So, really, I'm not sure the API code (at least at the top level) needs to be doing any exception handling or logging (except for special cases, like restoring invariants and other clean-up) -- we should be able to get Flask to do all that stuff for us.
