### ISSUE TITLE
Move the AdminUserDeletion exception to the `users_api` module

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2334]
This exception does not appear to be related to the users model.  This seems to be only used by the `user_api` module.  Perhaps it should be moved there?

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench/pull/2218#discussion_r638271879_

**Comment by npalaska** [comment]
Closing this issue as its already fixed in https://github.com/distributed-system-analysis/pbench/pull/2329
