### ISSUE TITLE
pbench-web-server : no executable?

### ISSUE THREAD

**Issue by jayunit100** [distributed-system-analysis/pbench#234]
I noticed that after running `yum install -y pbench-web-server` i get a directory:

```

├── html
│   └── static
│       ├── css
│       │   ├── v0.2
│       │   └── v0.3
│       └── js
│           ├── v0.2
│           └── v0.3
└── node_modules
```

- However, there isn't an actual executable in that directory.  
- In addition, there is no `index.html` top level file in that directory.

But, according to the package summary : 

```
Summary     : The pbench web server bits
```

Seems to indicate that there is a server that is deployed by this binary?  Also I don't see any unit files or anything being run to indicate its a backgroundable item.  

- Probably im just missing something obvious... but maybe the pbench-web-server item should be renamed if its not actually a web-server?

**Comment by portante** [comment]
@jayunit100, yes it does not provide a web-server itself, it provides files for a web-server.  So it assumes that you have apache (I think) installed locally, and that `/var/www/html` exists so that it can create the right links.

We might want to consider it depending on apache.

**Comment by k-rister** [comment]
@portante: It should work with just about any web server so a strict apache dependency is probably a bit too far.  The dependency is detailed in the internal documentation but I don't see that in what is public.

**Comment by jayunit100** [comment]
At least we should update the info in the package to define that it's just static content and not an executable "web server bits" sounds, literally, like it's an executable web server (to me).

**Comment by ndokos** [comment]
The docs on github now include a description of the pbench-web-server RPM: http://distributed-system-analysis.github.io/pbench/doc/server/pbench-web-server.html

**Comment by ndokos** [comment]
Can this be closed? Do we need to rename the RPM?
