### ISSUE TITLE
pbench configuration file does not exists after installation

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2343]
pbench-agent-0.69.9-24g90314ee7c.noarch

# pbench-register-tool-set
ERROR: failed to fetch tool set, default-tool-set, from the pbench-agent configuration file

Workaround:
cp pbench-agent.cfg.example pbench-agent.cfg

**Comment by portante** [comment]
Fixed by #2358, along with #2389.
