### ISSUE TITLE
`sos report` in Fedora 34 produces a SHA256 checksum file, not an MD5 file

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2363]
That makes `pbench-sysinfo-dump` conclude that the `sos report` generation failed.

**Comment by ndokos** [comment]
This should probably be fixed in master and backported to 0.69.

**Comment by portante** [comment]
The commit where sos changed to SHA256 is: https://github.com/sosreport/sos/commit/dc6cf40c4f637110162c305311f616f0fe60b89f.

That appears to have landed in 4.1.
