### ISSUE TITLE
Implement full semantics for defaulting "user" and "access" in dataset queries

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2370]
I liked the idea of defaulting a missing `"user"` to the authorized user; however, in terms of API expressiveness, defaulting to "all users" is probably more useful. It also has the distinct advantage of making a missing `"user"` do the same thing regardless of whether you're logged in or not.

OK, so:

`{}` means all private and public data for all users (with the proviso that unless I'm ADMIN, I can only see my own private data).

`{"user": "drb"}` means all public and private data for user "drb". (Which will return only public data for "drb" unless the authenticated user is "drb" or ADMIN.)

`{"user": "drb", "access": "private"}` means only private data for user "drb". (Must be "drb" or ADMIN to return data.)

`{"user": "drb", "access": "public"}` means only public data for user "drb".

`{"access": "private"}` means all private data, regardless of user; an unauthenticated request would return nothing, while a non-ADMIN user would see only their own private data.

`{"access": "public"}` means all public data regardless of the owner. (Which, for a non-logged-in user, is indistinguishable from `{}`, but would be different for a logged-in user, and more differenter for a logged-in ADMIN user. That is, for an authenticated user, `{}` would return the user's own private data as well, while `{"access": "public"}` won't; for an ADMIN user, `{}` would return all data.))

_Originally posted by @dbutenhof in https://github.com/distributed-system-analysis/pbench/pull/2355#discussion_r660105897_

**Comment by webbnh** [comment]
> `{"user": "drb"}` means all public and private data for user "drb".

With the proviso that, unless I'm ADMIN, the request won't return "drb"'s private data, unless the request comes from user "drb"....

> `{"access": "private"}` means all private data, regardless of user; this is legal only for an ADMIN user, and of dubious real world value.

I would dispute the "legal" part:  if we do a straightforward implementation, in the typical case (i.e., a logged-in, non-Admin user), this selector will return only the private data belonging to the requestor.  It would not be illegal, and it might be a common use case (e.g., it would free the dashboard from having to track and specify the current user...).  (Obviously, an Admin user will get _all_ private data back while a non-logged in user will get nothing.)

Similarly, `{"user": "drb", "access": "private"}` should be a legal request even if the requestor is not user "drb" and even if it's not an Admin...it's just that, in that case, the request won't get any data back.

**Comment by dbutenhof** [comment]
Thanks for the corrections, Webb. I updated the base issue. Which keeps it straightforward and easy to read, but unfortunately leaves your comments dangling since there's no real history of changes. Sorry 'bout that. ;-)

**Comment by webbnh** [comment]
No worries; and, since the issue description is now perfect, I deleted my comment.  😁

I contemplated editing the description myself, but I figured I should test the "legal" question first.

And, once you've read this, feel free to delete it, too.  👼
