### ISSUE TITLE
pbench-fio does not detect some fio run failures

### ISSUE THREAD

**Issue by hifzakh** [distributed-system-analysis/pbench#2378]
Some of the `fio-result.txt` files generated by the fio benchmark show an error at the top that indicates an unsuccessful run. One example of this error is `disk quota exceeded.` 

pbench-fio does not detect these errors and classifies these runs as successful.

**Comment by webbnh** [comment]
@hifzakh, could you post pointers to a few examples?  (URLs would be very helpful, but attaching an example file here would be illustrative, too.)

**Comment by hifzakh** [comment]
> @hifzakh, could you post pointers to a few examples? (URLs would be very helpful, but attaching an example file here would be illustrative, too.)

I mostly came across the following two cases. 

1. http://pbench.perf.lab.eng.bos.redhat.com/incoming/e24-h13-740xd.alias.bos.scalelab.redhat.com/fio_kata-2-ceph-local-prelim-1-processes-16-direct-0-fdatasync-1-seconds-600-kata-podaffinity_2021.05.27T23.46.09/1-read-4KiB/sample1/fio-result.txt
2. http://pbench.perf.lab.eng.bos.redhat.com/incoming/virtlab506.virt.lab.eng.bos.redhat.com/fio__2020.09.10T08.28.57/4-write-1024KiB/sample2/fio-result.txt

**Comment by webbnh** [comment]
Well, those are yucky but excellent examples of misbehavior.  Hopefully, this won't be hard to fix (but I'm deep into other stuff at the moment, so I'm resisting the temptation to look at it).
