### ISSUE TITLE
Lightweight memory-based logger for unit tests

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2384]
In  a discussion in PR #2340 , @webbnh suggested the use of a lightweight logger for unit tests:

> It would be better to use and in-memory logger for unit testing, if that's practical. Just a thought, in case you were interested in pursuing it.
> 
> In short, it would be a logger which implements the existing interface but which "writes" messages to a buffer in memory instead of writing them to a file on disk. I'm not sure exactly what our options are for that. The logging facility is pretty flexible, as is Python in general (i.e., most places where you need a file, you can instead supply a "file-like object", which can then do what you want). So, one of us would need to do some research. But, I think it would be worthwhile, especially for the unit tests, where we either ignore the log or read it immediately -- having the messages go out to disk is extra overhead, and it requires us to set up directories and to clean them up afterwards, none of which is necessary for the task of testing.

**Comment by webbnh** [comment]
We took our first steps in this direction in #2414, adding the [`test_logger` fixture](https://github.com/riya-17/pbench/blob/fd7ada4c789e9eef28fde117f229564f7ff2d8eb/server/lib/pbench/test/conftest.py#L27).  Currently, this still uses a `FileHandler` to store the log in a file, but it should now be straightforward to substitute [`MemoryHandler`](https://docs.python.org/3/library/logging.handlers.html#memoryhandler) to place the log in memory and free us from using a disk file.
