### ISSUE TITLE
Containerize the pbench-server

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2385]
We need a process for creating a container image, or images, for the pbench-server.

Initially this could be just one image where the pbench-server API process and all the cronjobs are run.

It could be that we create separate container images, one for the API process, and one for the cronjobs.

**Comment by webbnh** [comment]
Most of this work is now complete:  see #2585.  However, with regard to the items in the [previous comment](https://github.com/distributed-system-analysis/pbench/issues/2385#issuecomment-951305566):
- SELinux is currently disabled inside the container (it came that way...), so the code to do the labeling is in the script which builds the container, but it is commented out.
- As for putting the Git hash in the configuration file, the script which builds the container does not yet do this.  (I have a nice idea for how it could, but, if there is a standalone tool which can manipulate the configuration file (Ansible seems to have the capability built-in), that would probably be a better approach.)  Also, I'm not sure where to get the version and revision numbers from.
