### ISSUE TITLE
Server API: generalized "GET schema" API

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2410]
From a comment by @portante in #2382:

Can we consider a slightly different approach?  It is very likely that we'll be changing this API in the future both because it uses a name that belies the mechanism in which the data is stored, `index/mapping`, and because it is hard-coded to one kind of data, `run`.

As a proposal, can we make this be a "JSON schema" API, where a `GET` method returns the list of available JSON schema names on `json/schema`, and a `GET` on `json/schema/<name>` returns the JSON schema for that `name`?

Then the caller can do what it wants with the schema, and we don't have to put very specific behaviors for just returning keys in the API.

Additional commentary by @dbutenhof:

I believe this is a great suggestion, but I don't think we understand a general use case for such an interface beyond the dashboard's current use of  the RUN document template for SEARCH. I would like to be able to expose various JSON schema documents, including Dataset templates, API request and response payloads, and possibly other things. We need to decide on a common format (e.g., standard JSON schema language, Elasticsearch template syntax, etc.)

For now, this is a great step towards separating the dashboard from direct Elasticsearch, as well as a *fix* for the current elasticsearch passthrough API `GET`/`POST` bug (which, with this PR, I believe is no longer a concern unless we eventually decide to formalize a privileged raw Elasticsearch passthrough)... so I'd like to get it in and we can step back and figure out what sort of "schema" we wish to expose and in what form then make another iteration later. (E.g., in a `/api/v2` interface layer.)

As such, I'm going to resolve this conversation and move it to an issue.

**Comment by portante** [comment]
API direction is now purely using those defined by the Pbench Server for specific behaviors.
