### ISSUE TITLE
Remove prep-shim from 0.72 server!

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2421]
The current Pbench server dataset `PUT` upload isn't a full replacement for `pbench-server-prep-shim-002`, which for some reason I'd failed to completely internalize until now.

During the server jam session, we saw a logged failure due to `pbench-server-prep-shim-002` attempting to create a `Dataset` record owned by the imaginary `pbench` user. I initially assumed this was because we really shouldn't be running `prep-shim` anymore, and that it's interfering with `PUT`.

This isn't entirely true. The current `PUT` implementation is a direct replacement for `ssh`; it creates the `Dataset` record owned by the authorized client of `PUT`, but creates the files expected by `pbench-server-prep-shim-002` and depends on it to move the tarball and md5 file and set up the state link directories to get the dataset into the server pipeline.

This is a bug: `PUT` needs to completely replace `pbench-server-prep-shim-002` so that we can get rid of it and close the door on unowned `ssh` uploads entirely.

So,

- [x] `PUT` needs to *replace* the operations of `pbench-server-prep-shim-002` rather than depending on it to bring the new dataset into the server pipeline.
- [ ] We should completely delete the pbench-server-prep-shim-002 tool from 0.72: it's useless and dangerous
- [ ] The standard `prep-shim` intake directory should be removed from the install
- [ ] The host_info web API should be removed or redesigned, dropping the intake directory from the response, which is no longer relevant. (Maybe we don't completely delete it, however, as we do want a way to query the status of the server.)

**Comment by riya-17** [comment]
Hey, @dbutenhof we don't have put-shim in 0.72 server. I wanted to confirm are you talking about put-shim or prep-shim here?

**Comment by dbutenhof** [comment]
> Hey, @dbutenhof we don't have put-shim in 0.72 server. I wanted to confirm are you talking about put-shim or prep-shim here?

Thanks, Riya; Somehow I managed to refer to prep-shim using two different incorrect terms in this issue, and didn't get it right once. I guess `put-shim` was on my mind at the time!
