### ISSUE TITLE
Dealing with server "roles" and "tasks" in end-of-life 0.69 with put-shim

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2426]
I'd like to hear @ndokos or @portante interpret exactly what the intended purpose was for the `pbench-prep` role and `pbench-prep-task`. This looks weird to me, as `pbench-prep-task` seems to be the mechanism for getting the prep-shim into crontab; but that task isn't listed under the "normal" `pbench-results` role. I don't quite see how that gets into `crontab` normally, but maybe it'd be clear if I spent the time analyzing the 0.69 utility that constructs the `crontab` from this info. (I've only looked at the `main` version, and not thoroughly.)

I'd also like some feedback on the "interesting question" I raised earlier: do we *break* the end-of-line 0.69 to work *only* as a repeater for 0.72, or do we use roles and tasks to simply create a new mode of operation that would also allow "normal" use? (We don't care, I think, and I don't know that anyone else is maintaining a 0.69 server or would have any interest in continuing to do so ... and we certainly don't want to encourage that.)

_Originally posted by @dbutenhof in https://github.com/distributed-system-analysis/pbench/pull/2414#r690320000_

**Comment by dbutenhof** [comment]
The "interesting question" to which that clip refers:

This raises an interesting question: do we want to handle this new server configuration by adding a *role*, perhaps something like `pbench-repeater`, which might have a `tasks` list with just `pbench-server-put-shim` and `pbench-dispatch`? Then the "normal" server configuration just wouldn't have a put-shim task, while the new "end of life" 0.69 default would have only put-shim ... without breaking a `pbench-results` (or any other role) deployment should someone really want to do it?

**Comment by portante** [comment]
First of all, when all is said and done with 0.69 server and the 0.72 is "ready", then the ONLY 0.69 server code will be the "put" shim from PR #2414.

In that case, all other mechanisms can be dropped.

Instead of writing the "put" shim as a crontab base application, it'd be better written as a `systemd` service, using `inotify` to determine when to wake up and run.

**Comment by webbnh** [comment]
I'm starting to think that the put-shim work should be placed on its own branch:  it's got several facets which are in all likelihood going to require several commits/PRs to get right, and it's quite possible that more 0.69 work is going to crop up between 0.69.9 and 0.69.EOL which are going to be awkward to layer on top of 0.69.EOL, especially if the latter involves (as Peter correctly points out) removing everything but the put-shim.

**Comment by ndokos** [comment]
"Roles" and "tasks" in the config file were meant to customize what would run on a server. "Tasks" are basically cron job specifications and roles are collections of tasks. A production server would run the `prep`, `results`, `backup` and `maintenance` roles (i.e. everything). A satellite server might run just the `prep` role. The default `roles` is overridden in the server-specific config file in that case.

The crontab for each server is constructed by looping over the `roles` for that server and for each role looping over its tasks.

**Comment by riya-17** [comment]
I added the important points from the discussion. We can discuss how we want to move further from here.

- adding a role, perhaps something like `pbench-repeater`, which might have a `tasks` list with just `pbench-server-put-shim`.
- put-shim work should be placed on its own branch:
- "real" server would run the put-shim cron job which will have a separate role for `put-shim` or we would run it on a separate machine somewhere, maybe a VM, whose only job is to run the put-shim. ?

**Comment by portante** [comment]
PR #3292 will solve this issue.

**Comment by portante** [comment]
Fixed by #3292.
