### ISSUE TITLE
Tools from default tool group are used even with another tool group

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2435]
`pbench-agent-0.69.9-1ga12a9aa0f`

Steps to reproduce:
 1) Add `kvmstat` tool to default tool group
 2) Add another tool group without `kvmstat` tool

```
[pbench/tools]
default-tool-set = sar, iostat, mpstat, pidstat, proc-vmstat, proc-interrupts, turbostat, perf, kvmstat
another-tool-set = sar, iostat, mpstat, pidstat, proc-vmstat, proc-interrupts, turbostat, perf
```

3) `pbench-register-tool-set  --group=another`
```
sar: pbench-sysstat-12.0.3 is installed
sar tool is now registered in group another
iostat: pbench-sysstat-12.0.3 is installed
iostat tool is now registered in group another
mpstat: pbench-sysstat-12.0.3 is installed
mpstat tool is now registered in group another
pidstat: pbench-sysstat-12.0.3 is installed
pidstat tool is now registered in group another
proc-vmstat tool is now registered in group another
proc-interrupts tool is now registered in group another
turbostat: kernel-tools is installed
turbostat tool is now registered in group another
kvmstat tool is now registered in group another
perf: perf is installed
perf tool is now registered in group another
```

`kvmstat` has been added to the `another` tool group, even when it is configured to be only in the `default` tool group.

**Comment by riya-17** [comment]
@portante for installing a particular toolset we use `toolset` as option, as mentioned in the usage of `pbench-register-tool-set` command 
```pbench-register-tool-set -h
usage:
pbench-register-tool-set --toolset=<tool-set> [--group=<group-name>] [--interval=<interval>] [--no-install] [--remotes=<remote-host>[,<remote-host>]] [--labels=<label>[,<label>]]
pbench-register-tool-set --toolset=<tool-set> [--group=<group-name>] [--interval=<interval>] [--no-install] [--remotes=@<remotes-file>]

```

if we are using `pbench-register-tool-set --toolset=another` it is working perfectly fine.

What is `group` used for?

**Comment by riya-17** [comment]
Seems like `--group` option is used for giving an external name for a group. like in the config file the toolset name that is given as `another-tool-set` .

----------------------
if we install it using this command:
`pbench-register-tool-set --toolset=another`

it will install the tools with `default` tool group name.

-----------------------------

if we install it using following command:

`pbench-register-tool-set --toolset=another --group=light`

it will install it under `light` group name.

**Comment by riya-17** [comment]
We haven't specified the `--toolset` option in the above experiment due to which it is installing the `default-tool-set`. Only the group name is given which results in the `default` toolset being installed with the `another` group name.

**Comment by ndokos** [comment]
We think this is a documentation issue, not a code issue. We'll need to modify the User Guide (?)

**Comment by webbnh** [comment]
Can we close this Issue as a duplicate of #2344?  (Same tool; same root cause; same resolution?)

**Comment by aokuliar-rh** [comment]
This is indeed duplicate of #2344 , closing
