### ISSUE TITLE
How to install need to be fixed

### ISSUE THREAD

**Issue by mkumatag** [distributed-system-analysis/pbench#244]
in section - http://distributed-system-analysis.github.io/pbench/pbench-agent.html#sec-5 I see a instruction mentioned installing repo from link - http://repohost.example.com/repo/yum.repos.d/pbench.repo but this link is inaccessible

**Comment by psuriset** [comment]
manju, Try this 

https://copr.fedorainfracloud.org/coprs/ndokos/pbench/

Thats just example link.

**Comment by psuriset** [comment]
@mkumatag  ^

**Comment by mkumatag** [comment]
Yes, I tried that repo and working fine. Is there a plan to support debian as well and I was looking for to build it for ppc platform so that we can leverage on ppc64le.

**Comment by psuriset** [comment]
@mkumatag  

 Core issue here is working with multiple package systems:
-The pbench packages (pbench-agent, benchmark packages, tool packages, etc.) will need .deb versions. This will require some new/enhanced build scripts. If someone is familiar with taking a RPM spec file and doing the equivalent for .deb, that would help a lot.
-A few of the package commands in pbench need some package format abstraction. For example, check_install_rpm function needs to change to check_install_package, with logic to pick rpm or deb.

**Comment by ndokos** [comment]
I have updated the documentation (see PR #266 and #267). I believe the installation instructions are correct (if not necessarily very convenient). Please check and if you see any problems, let me know.
Thanks!

**Comment by ndokos** [comment]
I think this can be closed. If anybody disagrees, please reopen and let me know.
