### ISSUE TITLE
The default tool set and backward compatibility

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2466]
PR #2390 proposes changing the default tool set to make it lighter (avoiding perf and pidstat collection in particular). Some people have asked for that, but the change might surprise some users who really want the heavy data. If there is going to be a surprise, it is important to surprise such users early and not after the fact: nobody wants to collect data for a day or a week and then find out that the data they really expected to be there are not.

Some possibilities (not mutually exclusive):

- Warn about the changes in email, release notes and other docs. 
- Provide prominent feedback, describing the data that are going to be collected at the beginning of a run.
- Get rid of the default tool set all together and make the tool registration fail until the user selects a tool set (per run or somehow  more permanently).
- Keep the default tool set but define it in the site-specific agent config file, rather than the generic default config file. Begin by defining it to be the current (heavy) set, but instruct users on how to change it *now* to a lighter tool set.

**Comment by portante** [comment]
Fixed by #2390.
