### ISSUE TITLE
Clean up dataset load errors in jschart

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#249]
When a dataset load error is encountered in jschart an obnoxious "Load Errors" message is prominently displayed in the chart area.

Would like to improve upon this by being more subtle with the error message while giving the user more information about what is wrong (probably add more details to the javascript console including the dataset name).

![foo](https://cloud.githubusercontent.com/assets/15911116/15396297/13ca0ddc-1da1-11e6-894d-802ba3821a7f.png)

**Comment by k-rister** [comment]
Looking into this is revealing some other subtle bugs with empty datasets that need to be fixed as well.

**Comment by k-rister** [comment]
I have a fix that handles this more gracefully.  Datasets that have load errors are now flagged as invalid and hidden.  In the table invalid datasets are marked with a yellow highlight and pinned at the top so that they are clearly visible to the user.  The large error message in the chart body is gone and there are log entries in the Javascript console.  It looks like this now:

![invalid-dataset](https://cloud.githubusercontent.com/assets/15911116/15681036/75aa5946-271d-11e6-8279-43c851c01ad2.png)

While invalid datasets will exist in both the table and the legend many of the traditional user initiated actions (highlighting, unhiding, etc.) are ignored.

**Comment by portante** [comment]
@k-rister, really nice!
