### ISSUE TITLE
A large dataset cannot be marked as "published"

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2490]
The recent [Greenfield Installation Exercise](https://docs.google.com/document/d/1DQP0BL3CChQmkxUxuD5-iuYRakcmCjeikeW5iJQHRfw) revealed a problem with publishing a large dataset.

Publishing a large dataset involves updating each of the Elasticsearch "documents" which comprise the dataset.  This is currently done in a single, bulk request.  Elasticsearch has a configurable maximum size for such requests which, by default, is "only" 100 Mb.  For a large dataset, this is likely to be too small to allow all the documents to be modified in a single request.  Attempting to do so currently produces a somewhat cryptic error from ES which is translated into a rather opaque message from the API.

**Comment by dbutenhof** [comment]
Need to investigate this more. I hacked in some code to stringify the JSON bulk query and humanize the size in the log message before we call Elasticsearch. It shows the failed bulk update document as "only" 3.7 Mb. A query to our ES server confirms that our max request size is essentially 100Mb (more like 104Mb), and I can't find any reference to a separate constraint on bulk update queries, nor can I come up with an easy explanation of why our 3.7 Mb payload would be affected by a 104 Mb request limit.

```
UPDATE public operation will update 20920 Elasticsearch documents in 4 indices (3.7 MB JSON): ['staging-pbench.v6.run-data.2020-09', 'staging-pbench.v6.run-toc.2020-09', 'staging-pbench.v5.result-data-sample.2020-09-24', 'staging-pbench.v5.result-data.2020-09-24']
```

After some research this morning, I think I need to take the step I'd deliberately skipped when I initially implemented this, to use the `elasticsearch` bulk helper with a generator feed; (or probably `pyesbulk` on top of that), as it appears the helper supports automatically "chunking" the request (by default at something like 500 documents), and although the documentation is not entirely clear on this point it seems reasonable to assume this is intended to avoid the problem we're hitting.
