### ISSUE TITLE
Non-deterministic outcomes of Tool Meister tests under Jenkins

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2499]
Certain of the Tool Meister "unit tests" occasionally report errors ([example](http://jenkins.perf.lab.eng.bos.redhat.com/job/pbench-ci-multi/job/main/111/console)) like:
```
pbench-tool-meister-stop [...] failed to execute successfully.
```

**Comment by portante** [comment]
We took the action in our Jenkins CI environment to reduce the # of jobs concurrently runnable to avoid jobs interfering with each other.

But it is hard to determine if we have solved the problem.  We just haven't seen it recently.
