### ISSUE TITLE
Remove support for `pbench-run-benchmark`

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2511]
The support for `pbench-run-benchmark` requires Ansible, which is a large package which alone makes the container size significantly larger.  For this and other reasons, we would like to shed this dependency, and we believe that our user requirements for `pbench-run-benchmark` have been superseded by other support and will go away completely once we have integrated with benchmark wrapper.

Therefore, we should remove `pbench-run-benchmark` from the Agent code, and we should do this in time for the V0.71 Beta, to allow us to discover any lingering needs for this support.

**Comment by portante** [comment]
The `pbench-run-benchmark` interface has been marked deprecated in the v0.71 release via PR https://github.com/distributed-system-analysis/pbench/pull/2545.
