### ISSUE TITLE
Move away from "controller" as primary query access key, towards metadata

### ISSUE THREAD

**Issue by dbutenhof** [distributed-system-analysis/pbench#2512]
The dashboard Overview page is "curation central", focusing on all data owned by the authenticated user. Right now, the key `datasets/list` API requires a controller. Essentially, this page view would require querying all of the user's controller names within some date range (probably based simply on `controllers/months`; although maybe that's not the best name anymore), and then iterate through each controller returned to get all of the datasets.

Instead, if we removed the requirement for "controller" in the `datasets/list` and `datasets/detail` queries, we could constrain the query only by user and date range. This would make a lot more sense.

We could consider adding the ability to filter the returned list by metadata, possibly including controller but also arbitrary owner-assigned metadata like, for example, a `user.group`.

This change in focus is something we've talked about, but haven't really designed. This might, for example, suggest a shift in our API structure away from the `controllers/months` and `controllers/list` APIs:

E.g.,

* `controllers/months` is really server configuration data: the full range of month-suffixed `run-data` indices. This might be `datasets/months` or even `server/months` rather than artificially associating it with "controllers"
* `controllers/list` aggregates the count for each value of `run.controller` within the user's datasets; we don't necessarily need this, or maybe it could become more of a "dataset metadata aggregation" query: e.g., "what are the values of my `user.group` metadata tag and how many datasets use each?", with "controller" just being one possible metadata tag.
* The `datasets/*` queries take "controller" mostly because the Dataset table was meant to be indexed by controller and name; we may want to either remove the controller parameter, make it optional, or replace it with a more general (optional) metadata query parameter.

**Comment by portante** [comment]
Is this closed by #2835?

**Comment by dbutenhof** [comment]
Apparently this wasn't liked to the PR.
