### ISSUE TITLE
pbench-uperf errors

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#252]
when I try to run a distributed network test with pbench-uperf, this is what I see, why the errors?

[root@ceph-r730-01-10ge system]# pbench-uperf --server-node=ceph-r730-02-10ge,ceph-r730-04-10ge --client-node=ceph-r730-03-10ge,ceph-r730-05-10ge --t rr -r 10 -i 5
Collecting system information
Starting iteration  (1 of 32)
/opt/pbench-agent/bench-scripts/pbench-uperf: line 562: [: ceph-r730-02-10ge: integer expression expected
/opt/pbench-agent/bench-scripts/pbench-uperf: line 578: [: ceph-r730-03-10ge: integer expression expected
found uperf pid 1715246 on 127.0.0.1:21000, killing
test sample 1 of 5
/opt/pbench-agent/bench-scripts/pbench-uperf: line 619: [: ceph-r730-03-10ge: integer expression expected
/opt/pbench-agent/bench-scripts/pbench-uperf: line 624: [: ceph-r730-02-10ge: integer expression expected
client[127.0.0.1]protocol[tcp]test[stream]instances[5]size[1] <-> server[127.0.0.1]
Use of uninitialized value in numeric lt (<) at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 161.
Use of uninitialized value in numeric lt (<) at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 161.
Use of uninitialized value in numeric ge (>=) at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 168.
Use of uninitialized value in numeric ge (>=) at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 168.
Use of uninitialized value $unneeded_stat2_timestamp in delete at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 171.
/opt/pbench-agent/bench-scripts/pbench-uperf: line 562: [: ceph-r730-02-10ge: integer expression expected
/opt/pbench-agent/bench-scripts/pbench-uperf: line 578: [: ceph-r730-03-10ge: integer expression expected
test sample 2 of 5

**Comment by atheurer** [comment]
I don't think "--t rr" is a valid argument, but "--test-type=rr" or "-t rr" should be.   We should probably add some better error handling for this (and not start a test when invalid option is used).

**Comment by atheurer** [comment]
Also, server-node and client-node are the wrong options.  You want --servers and --clients.  The --help specifies:

                --server-node[s]=str[,str]              An ordered list of server NUMA nodes which should be used for CPU binding
                --client-node[s]=str[,str]              An ordered list of rrclient NUMA nodes which should be used for CPU binding

and 

                -C str[,str] --client[s]=str[,str]      a list of one or more hostnames/IPs.  These systems will run the
                                                        uperf client (drive the test).
                                                        If this is omitted, the local system is the client
                                                        Note: the number of clients and server must be the same!
                                                        Clients and servers are paired according the order in the list (first
                                                        client pairs with firest server, etc)
                -S str[,str] --server[s]=str[,str]      a list of one or more hostnames/IPs.  These systems will run the uperf
                                                        server (listening for connections)
                                                        If this is omitted, the server will listen on the local system
                                                        loopback interface

**Comment by bengland2** [comment]
user brain damage!  I meant --server x --client y  -t rr

[root@ceph-r730-01-10ge system]# pbench-uperf --server-node=ceph-r730-02-10ge,ceph-r730-04-10ge --client-node=ceph-r730-03-10ge,ceph-r730-05-10ge -t rr -r 10 -i 5 --samples=3
Collecting system information
Starting iteration  (1 of 8)
/opt/pbench-agent/bench-scripts/pbench-uperf: line 562: [: ceph-r730-02-10ge: integer expression expected
/opt/pbench-agent/bench-scripts/pbench-uperf: line 578: [: ceph-r730-03-10ge: integer expression expected
...

**Comment by ndokos** [comment]
All set now (at least for now).

**Comment by bengland2** [comment]
user brain cramp
