### ISSUE TITLE
Should we check that the remotes file in `pbench-register-tool[-set]` is non-empty?

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2538]
The implementation does not currently raise an error if in specifying the  `--remotes=@foo` option, the file `foo` is empty. The `{pbench_run}/tools-v1-<toolset>` directory is created if necessary, but no tools are registered and the exit status is 0 (from either registration program).

Arguably, however, that is a potential error that the user might want to know about.

**Comment by portante** [comment]
@ndokos, is this issue completed by #2514, or is there more work to do for this issue?

**Comment by webbnh** [comment]
> is this issue completed by #2514, or is there more work to do for this issue?

@portante, this issue was opened [in response](https://github.com/distributed-system-analysis/pbench/pull/2514#discussion_r747214125) to #2514.
