### ISSUE TITLE
Considerations for the pbench-server when handling legacy `--user` and `--prefix` metadata

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2546]
From https://github.com/distributed-system-analysis/pbench/pull/2544#pullrequestreview-807226389:

> This looks good on its own. It raises a few strategic questions about 0.72, however, with the concept of user (and prefix) as *result path* structuring rather than simply "--user as a hack placeholder for dataset owner".
>
> `pbench-results-move` doesn't support either `--prefix` or `--user`. Should it? I've been working on my class structure to comprehend and mutate the on-disk structure without considering these (and therefore without needing to read the `metadata.log` in order to discover the `RESULTS` tree structure ... and completely ignoring a `USERS` tree as it doesn't exist).
>
> Right now, the classes aren't doing unpack (because I'm not touching the current unpack code); but if we want this sort of access path customization, we need to add them into `pbench-results-move` and I'll need to discover the prefix and user paths in order to properly delete them.

**Comment by dbutenhof** [comment]
Resolved: `--prefix` is meaningless once we move away from direct Apache file viewer access to the `results` tree, and especially once we move to cache manager and S3 object store. `--user` is replaced by true users. The 0.71 `pbench-results-move` doesn't support either setting. If tarballs generated from 0.69 are pushed to the 1.0 server the values will be available as metadata under `dataset.metalog` but the server will not interpret them.
