### ISSUE TITLE
What does "module dependencies" mean in the pbench-agent spec file?

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2583]
From a [comment](https://github.com/distributed-system-analysis/pbench/pull/2556#discussion_r766634533) in #2556: 
The pbench-agent spec file has this in the RHEL8 section (and similar for RHEL9 and Fedora):

```
%if 0%{?rhel} == 8
Requires:  python36, python3-pip
# RPMs for modules in requirements.txt
Requires:  python3-cffi, python3-click, python3-requests
# RPMs for module dependencies
Requires:  python3-docutils, python3-psutil
%endif
```
The question is: who requires `python3-docutils` and `python3-psutil`?

**Comment by portante** [comment]
Let's consider this closed with PR #2901.
