### ISSUE TITLE
Investigate PAM errors in the journal log from the containerized server

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2590]
Running the containerized Pbench Server (see [instructions](https://docs.google.com/document/d/1k4zrnGNa8BdjcVvMWmFKpp26wGnXHpMJq6EA8kXOsnk)), a number of errors appear in the log, like this:
```
Jan 11 18:06:43 pbenchinacan systemd[1]: systemd-journald.service: Failed to add fd to store: Operation not permitted
```
and
```
Jan 11 18:08:01 pbenchinacan crond[523]: pam_systemd(crond:session): Failed to create session: Unit systemd-logind.service is masked.
```

While the container seems to function successfully despite these errors, they litter the log with scary red text which seems like it deserves some attention.

Note that the container creation does [modify the PAM configuration file](https://github.com/distributed-system-analysis/pbench/blob/96e9fc3956f244b3674f583c89927726c2f92d47/server/pbenchinacan/container-build.sh#L52) for `crond`, which is necessary to allow it to work, but this doesn't seem to completely address the complaints.

**Comment by portante** [comment]
Fixed via PR #3100.
