### ISSUE TITLE
Update to agent pbench.repo.j2 file under pbench_repo_install role?

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#2596]
The file content of `roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2` under pbench agent are this:
```
{% for repo in repos %}

[copr-{{ repo.tag }}-{{ repo.user }}]
name=COPR {{ repo.tag }} ({{ repo.user }}) repo
...
```
which I think either should be this 
```
{% for repo in repos %}

[copr-{{ repo.tag }}]
name=COPR {{ repo.tag }} repo
...
```
or we need to update the documentation on how to set up the `repo.user` value because if the repo.user doesnt exist and it prints this message `"AnsibleUndefinedVariable: 'dict object' has no attribute 'user'"`.

Also if we remove the {{ repo.user }} it create the correct repo file on the vm because the `{{ repo.tag }}` itself can be `pbench` or `pbench-test` or any other tag that one can have. This result in the following (assuming the repo.tag is pbench-test)

```
[copr-pbench-test]
name=COPR pbench-test repo

```
Note: In server pbench_repo_install role we don't seem to have `{{ repo.user }}`

**Comment by webbnh** [comment]
The `roles/pbench_repo_install/templates/etc/yum.repos.d/pbench.repo.j2` template is also used by the Pbench Agent containers build (see `agent/containers/images/Makefile`), and the template arguments are drawn from a YML file (which is itself produced from a template -- see `agent/containers/images/repo.yml.j2`).  The `user` value is set to the account on COPR which is to provide the RPM(s).

That said, I don't think the value in the `[]`'s in the `.repo` file is particularly important, so long as it is syntactically acceptable and unique within the DNF configuration.  Likewise, I think the `name=` value isn't critical, either, so long as it's meaningful to the human examining the DNF outputs.  But, I think it is helpful to have the username there (e.g., I can imagine ending up with a configuration where the `.repo` file has an `ndokos` entry, _and_ a `wscales` entry, as well as the `-test` entries -- I've seen that myself, although not via Ansible).

In terms of easing the end-user's woes, perhaps it would do to set up a default value for `user`?  Thus, if none is specified, things will "just work".  (One way to do this might be via the Jinja2 [default](https://jinja.palletsprojects.com/en/3.0.x/templates/#jinja-filters.default) filter, but there are other approaches, as well.)

**Comment by npalaska** [comment]
Closing this issue as it was mostly an error in my configuration file.
