### ISSUE TITLE
`pbench-run-benchmark` complains about missing `/opt/pbench-agent/bench-scripts/pbench-run-benchmark.pl`

### ISSUE THREAD

**Issue by ldoktor** [distributed-system-analysis/pbench#2624]
**Description of problem:**
After updating pbench-agent from `69.*` to `71.*` [centos-stream-9-x86_64](https://copr-be.cloud.fedoraproject.org/results/ndokos/pbench/centos-stream-9-x86_64) RPM the `pbench-run-benchmark` stopped working and complains about missing `pbench-run-benchmark.pl` file. Note the file is present in the current main sources so it looks like a packaging issue.

**Version-Release number of selected component (if applicable):**
* pbench-agent-0.71.0-1g894ea5d0f.noarch

**How reproducible:**
* Always

**Steps to Reproduce:**
1. Install pbench-agent using `https://copr-be.cloud.fedoraproject.org/results/ndokos/pbench/centos-stream-9-$basearch` repo
2. run pbench `ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 pbench-run-benchmark linpack  --run-samples=3 --threads=1,128 --clients=192.168.122.229 --linpack-binary='/usr/local/pbench-linpack-11.1.3/benchmarks/linpack/xlinpack_xeon64'`

**Actual results:**
```
22:49:48.782: virtlab722     : >> /opt/pbench-agent/bench-scripts/pbench-run-benchmark: line 10: /opt/pbench-agent/bench-scripts/pbench-run-benchmark.pl: No such file or directory
22:49:48.832: virtlab722     : >> [root@virtlab722 ~]#
22:49:53.888: root           : Sending command: echo $?
22:49:53.907: virtlab722     : >> 127
22:49:53.958: virtlab722     : >> [root@virtlab722 ~]#
```

**Expected results:**
Should execute and report results

**Additional info:**

**Comment by webbnh** [comment]
Hi Lukas, thanks for reporting this, and sorry for the trouble!

`pbench-run-benchmark` is a trampoline script which is intended to transfer control to a Perl script, `pbench-run-benchmark.pl`; however, as you observed, the target is missing from the installation.

It's not obvious how or why the Perl script is missing, but it seems to be a unique case in our sources...I'm investigating the problem, now.

**Comment by webbnh** [comment]
Hi Lukas,

I've applied my fix, and it _seems_ to address the problem.  I tried this command (which differs from yours only in the `--client` value):
```
ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3 pbench-run-benchmark linpack --run-samples=3 --threads=1,128 --clients=localhost --linpack-binary='/usr/local/pbench-linpack-11.1.3/benchmarks/linpack/xlinpack_xeon64'
```
and got no complaints about missing files; however, the run doesn't seem to have progressed beyond preparing for the first iteration -- that is, I think it's hung here:
```
...
cmdfile: /var/lib/pbench-agent/linpack__2022.03.07T19.12.20/pbench-run-benchmark.cmd
Generating all benchmark iterations
resolving default first with pbench-gen-iterations linpack --defaults-only --run-samples=3 --threads=1,128 --clients=localhost --linpack-binary=/usr/local/pbench-linpack-11.1.3/benchmarks/linpack/xlinpack_xeon64
```
I'm running a v0.71 build in a CentOS-8 container.

So...I don't know whether I can declare victory or not....

**Comment by webbnh** [comment]
Peter and I took a look at my hang scenario, and we agree that it has nothing to do with this change.  (My run was hanging because a previous run had left behind processes which were bound to the network port that the current one wanted to use, and parts of the current run were then dying rather quietly, and that left the rest hanging.)  So, I will open issues for the other bugs which turning over this rock has exposed and close this one.

Thanks, again, Lukas for report this!  😉
