### ISSUE TITLE
Add legacy functional tests for `pbench-run-benchmark` where `pbench-run-benchmark-sample` is not mocked

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2662]
The legacy functional tests for `pbench-run-benchmark` does not execute the functionality of `pbench-run-benchmark-sample`, which is where all the workload driving logic resides.  The script, `pbench-run-benchmark-sample` is mocked out, see: https://github.com/distributed-system-analysis/pbench/blob/e247796bf8c108c460606f9d4c5ddbff10041c3e/agent/bench-scripts/test-bin/pbench-run-benchmark-sample.

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench/pull/2660#discussion_r819117416_

**Comment by ldoktor** [comment]
The question is how important this is given the fact that `pbench-run-benchmark` is marked as deprecated and to be removed in next release.

**Comment by webbnh** [comment]
The previous comment notwithstanding, an alternative way to address this issue would be to add testing for `pbench-run-benchmark-sample`.

**Comment by portante** [comment]
Since `pbench-run-benchmark` is deprecated, let's not pursue this work.
