### ISSUE TITLE
Need a way to clean up orphaned Tool Meister processes

### ISSUE THREAD

**Issue by webbnh** [distributed-system-analysis/pbench#2666]
If a benchmark run crashes for some reason (e.g., see #2667), the benchmark script needs a way to clean up the left-over Tool Meister processes.  It would be handy if this mechanism were also useable from a Control-C handler, and available for users to use manually if all else fails.

Related to #2120

**Comment by dbutenhof** [comment]
Much of this is covered by #2625. Other related issues include #2120, #2173, and #2174 (possibly more).

**Comment by portante** [comment]
@dbutenhof is this something you are planning on picking up?  If not, I'll drive it.
