### ISSUE TITLE
`pbench-trafficgen --postprocess-only=y` crashes with exception

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2673]
pbench-agent-0.71.0-185g5527f23f1.noarch
pbench-trafficgen commit `47d4fe5575c94b949c4db8c5cf8d6b5c148c56bc`
trex v2.87

Full command line output:
```
pbench-trafficgen --postprocess-only=y
tool trigger strings for start: "Starting binary-search" and for stop: "Finished binary-search" are now registered for tool group: "default"
Total number of benchmark iterations: 1
Starting iteration[1-none-bidirectional-64B-1024flows-0.002pct_drop] (1 of 1)
[error][2022-03-10T15:25:27.667809057] Results directory /var/lib/pbench-agent/trafficgen__tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-10T15:25:27/1-none-bidirectional-64B-1024flows-0.002pct_drop/sample1 does not exist, skipping post-processing
/opt/pbench-agent/bench-scripts/pbench-trafficgen: line 1295: /var/lib/pbench-agent/trafficgen__tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-10T15:25:27/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.cmd: No such file or directory
chmod: cannot access '/var/lib/pbench-agent/trafficgen__tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-10T15:25:27/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.cmd': No such file or directory
tee: '/var/lib/pbench-agent/trafficgen__tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-10T15:25:27/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.out': No such file or directory
/opt/pbench-agent/bench-scripts/pbench-trafficgen: line 1297: /var/lib/pbench-agent/trafficgen__tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-10T15:25:27/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.cmd: No such file or directory
[error][2022-03-10T15:25:27.672110136] This test iteration failed
Iteration 1-none-bidirectional-64B-1024flows-0.002pct_drop complete (1 of 1), with 1 pass and 1 failures
Use of uninitialized value $first_iteration_num in hash element at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 244.
Use of uninitialized value $spacing{"iter_num"} in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 247.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 247.
Use of uninitialized value $spacing{"iter_num"} in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 273.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 273.
Use of uninitialized value $spacing{"iter_num"} in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 300.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 300.
Use of uninitialized value $spacing{"iter_num"} in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 346.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 346.
Use of uninitialized value $first_iteration_num in hash element at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 376.
Use of uninitialized value $spacing{"iter_num"} in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 377.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 377.
```

**Comment by webbnh** [comment]
> pbench-trafficgen --postprocess-only=y

This command line is incomplete:  it doesn't specify the result which should be post-processed.  In order to use this option, you need to specify the command line used to run the benchmark originally (in addition to this option).

My apologies that the documentation does not make that clear.

**Comment by webbnh** [comment]
I agree, though, that this should have a much more graceful mode of failure under these circumstances.

**Comment by aokuliar-rh** [comment]
pbench-trafficgen --config=Test --devices 0000:06:00.0,0000:06:00.1 --skip-git-pull --traffic-generator=trex-txrx --postprocess-only=y
tool trigger strings for start: "Starting binary-search" and for stop: "Finished binary-search" are now registered for tool group: "default"
Total number of benchmark iterations: 1
Starting iteration[1-none-bidirectional-64B-1024flows-0.002pct_drop] (1 of 1)
[error][2022-03-14T09:53:15.522084695] Results directory /var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15/1-none-bidirectional-64B-1024flows-0.002pct_drop/sample1 does not exist, skipping post-processing
/opt/pbench-agent/bench-scripts/pbench-trafficgen: line 1295: /var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.cmd: No such file or directory
chmod: cannot access '/var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.cmd': No such file or directory
tee: '/var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.out': No such file or directory
/opt/pbench-agent/bench-scripts/pbench-trafficgen: line 1297: /var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15/1-none-bidirectional-64B-1024flows-0.002pct_drop/process-iteration-samples.cmd: No such file or directory
[error][2022-03-14T09:53:15.525881054] This test iteration failed
Iteration 1-none-bidirectional-64B-1024flows-0.002pct_drop complete (1 of 1), with 1 pass and 1 failures
Use of uninitialized value $first_iteration_num in hash element at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 244.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 247.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 247.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 273.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 273.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 300.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 300.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 346.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 346.
Use of uninitialized value $first_iteration_num in hash element at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 376.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 377.
Use of uninitialized value in concatenation (.) or string at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 377.

Am I doing something wrong?

**Comment by webbnh** [comment]
> Am I doing something wrong?

I don't know...what are you trying to do?  😀

This command,
```
pbench-trafficgen --config=Test --devices 0000:06:00.0,0000:06:00.1 --skip-git-pull --traffic-generator=trex-txrx --postprocess-only=y
```
is a request to Pbench to (re-)post-process an _existing_ result produced by that command line (as previously invoked, without the `--postprocess-only` switch).  So, if you don't have an existing result in `/var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15/1-none-bidirectional-64B-1024flows-0.002pct_drop` before you run this command, we should expect to see the `[error][<timestamp>] Results directory <results-dir>/sample1 does not exist, skipping post-processing` message.

Now, that said, we probably shouldn't be seeing any of the messages which come after that, but that's a different story.

**Comment by aokuliar-rh** [comment]
I have /var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15 on my filesystem, but it does not contain 1-none-bidirectional-64B-1024flows-0.002pct_drop file.

ls /var/lib/pbench-agent/trafficgen_Test_tg:trex_r:none_fs:64_nf:1024_fm:si,di,sm,dm_td:bi_ml:0.002_tt:bs_2022-03-14T09:53:15
generate-benchmark-summary.cmd  pbench-trafficgen.cmd  result.csv  result.html  result.json  result.txt

Is there a possibility that this result already have been processed and I cannot do any more postprocessing?

Sorry for dumb question, but I am not sure how should I test this functionality. 

My workflow at the moment:

1) run 
# pbench-trafficgen --config=Test --devices 0000:06:00.0,0000:06:00.1 --skip-git-pull --traffic-generator=trex-txrx 
to create results
2) run
# pbench-trafficgen --config=Test --devices 0000:06:00.0,0000:06:00.1 --skip-git-pull --traffic-generator=trex-txrx --postprocess-only=y
to postprocess results.

What am I doing wrong?
Thanks a lot
A.

**Comment by webbnh** [comment]
> Is there a possibility that this result already have been processed and I cannot do any more postprocessing?

That's not a dumb question -- that's a perfectly reasonable thing to ask.  The answer is, "no":  postprocessing is additive, not destructive -- you should be able to re-post-process as many times as you like.

> What am I doing wrong?

Assuming that your initial run was successful, I don't see anything wrong there....  @portante?

**Comment by portante** [comment]
TrafficGen is no longer supported starting in v0.71 and later.
