### ISSUE TITLE
`pbench-trafficgen` wants to use `dpdk-devbind` script, but `dpdk-tools` provides `dpdk-devbind.py`

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2675]
pbench-agent-0.71.0-14g4cbc95439.noarch
pbench-trafficgen commit `47d4fe5575c94b949c4db8c5cf8d6b5c148c56bc` (HEAD -> master, origin/master, origin/HEAD)
trex v2.87
```
pbench-trafficgen --config=Test --devices 0000:06:00.0,0000:06:00.1
tool trigger strings for start: "Starting binary-search" and for stop: "Finished binary-search" are now registered for tool group: "default"
found IOMMU option, continuing
found dpdk-tools, continuing
configuring device 0000:06:00.0
/opt/pbench-agent/bench-scripts/pbench-trafficgen: line 175: dpdk-devbind: command not found
[error][2022-03-09T18:02:23.250941767] could not unbind device, exiting
```
Package `dpdk-tools` provides `dpdk-devbind.py`:
```
dpdk-tools-2:20.11-3.el9.x86_64 : Tools for setting up Data Plane Development Kit environment
Repo        : beaker-AppStream
Matched from:
Filename    : /usr/bin/dpdk-devbind.py
```
This issue can be worked around by
```
    ln -s /usr/bin/dpdk-devbind.py /usr/bin/dpdk-devbind
```

**Comment by webbnh** [comment]
This smells like a `dpdk-tools` packaging bug.  There's lots of [documentation](https://doc.dpdk.org/guides/tools/devbind.html) on the [net](http://manpages.ubuntu.com/manpages/bionic/man8/dpdk-devbind.8.html) which refer to the [tool](https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/10/html-single/ovs-dpdk_end_to_end_troubleshooting_guide/index) without the `.py` extension.

**Comment by portante** [comment]
TrafficGen is no longer supported starting in v0.71 and later.
