### ISSUE TITLE
`pbench-trafficgen` requires `iommu_intel=on` even on AMD machines

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2676]
pbench-agent-0.71.0-14g4cbc95439.noarch
pbench-trafficgen commit `47d4fe5575c94b949c4db8c5cf8d6b5c148c56bc` (HEAD -> master, origin/master, origin/HEAD)
trex v2.87
```
pbench-trafficgen --config=Test --devices 81:00.0,81:00.1  --traffic-generator=trex-txrx
[error][2022-03-04T17:33:12.676816505] could not find IOMMU option, intel_iommu=on, in /proc/cmdline, exiting
```
`intel_iommu=on` is completely redundant on AMD machines. AMD requires `iommu=pt` instead. 
This is a cosmetic problem, when adding `iommu_intel=on` and `iommu=pt` to the kernel command line, everything works. It is just a little bit confusing.

**Comment by webbnh** [comment]
> This is a cosmetic problem, when adding `iommu_intel=on` and `iommu=pt` to the kernel command line, everything works. It is just a little bit confusing.

I'd say it's more than a "cosmetic" problem -- as things stand, the tool refuses to run unless it finds the specific parameter setting in the kernel's boot command line; yeah, you can hack your way around that easily enough (if you have access to the command line...), but it's kind of unreasonable.  (I think it should be a warning at most....)

**Comment by portante** [comment]
TrafficGen is no longer supported starting in v0.71 and later.
