### ISSUE TITLE
[RFE] Please add some sort of `--insecure` option to `pbench-trafficgen`

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2677]
pbench-agent-0.71.0-14g4cbc95439.noarch
pbench-trafficgen commit `47d4fe5575c94b949c4db8c5cf8d6b5c148c56bc` (HEAD -> master, origin/master, origin/HEAD)
trex v2.87
```
pbench-trafficgen --config=Test --devices 81:00.0,81:00.1  --traffic-generator=trex-txrx

Connecting to trex-tgn.cisco.com (trex-tgn.cisco.com)|173.36.109.208|:443... connected.
WARNING: The certificate of ‘trex-tgn.cisco.com’ is not trusted.
WARNING: The certificate of ‘trex-tgn.cisco.com’ doesn't have a known issuer.
```
Cisco seems to have some issues with SSL certificate chain, could you please add some sort of `--insecure` option to `pbench-trafficgen`, which allows to bypass this ?

**Comment by webbnh** [comment]
I recommend that you install trafficgen (and trex) manually, and then run `pbench-trafficgen` with `--skip-trex-install` and with `--skip-git-pull`.  This will enable you to avoid the certificate issue and the version skew problems that we're currently wrangling with.

**Comment by webbnh** [comment]
> work with a certain minimum version of trafficgen

Unfortunately, in this particular case, and for the foreseeable future, it will presumably be a _maximum_ version of trafficgen.  For getting beyond that version, we'll be looking toward something like integration with Benchmark-Wrapper.

**Comment by portante** [comment]
TrafficGen is no longer supported starting in v0.71 and later.
