### ISSUE TITLE
pbench-trafficgen requires tmux, but does not installs it automatically

### ISSUE THREAD

**Issue by aokuliar-rh** [distributed-system-analysis/pbench#2678]
pbench-agent-0.71.0-14g4cbc95439.noarch
pbench-trafficgen commit `47d4fe5575c94b949c4db8c5cf8d6b5c148c56bc` (HEAD -> master, origin/master, origin/HEAD)
trex v2.87
```
pbench-trafficgen --config=Test --devices 0000:81:00.0,0000:81:00.1\
--traffic-generator=trex-txrx
/opt/trafficgen/launch-trex.sh: line 243: tmux: command not found
```
can be manually workarounded simply by
```
dnf install tmux
```
Could you please add tmux as a pbench-trafficgen dependency?

**Comment by webbnh** [comment]
Sorry, Adam -- `/opt/trafficgen/launch-trex.sh` is a part of trafficgen, not of Pbench, so, to the extent that it depends on `tmux`, the installation of trafficgen should provide it.

Pbench should not be in the business of providing the benchmarks (and their dependencies) itself.  I realize that the `pbench-trafficgen` script historically pulled trafficgen benchmark from Git, but, as your current troubles demonstrate, that's not a sustainable model, and it's one that we are trying to move away from...so, adding additional dependencies isn't in the plan.

**Comment by portante** [comment]
FWIW, this smacks of a version skew problem between the tafficgen code and the `pbench-trafficgen` code.

**Comment by webbnh** [comment]
> this smacks of a version skew problem

In that case, reference #2223.
