### ISSUE TITLE
Google Season of Docs - Organization Project Proposal - 2022

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2687]
Create a wiki page describing the project proposal for our organization, pbench.

Below is the initial write-up that will land on the Wiki based on https://developers.google.com/season-of-docs/docs/org-proposal-template.

We have also created a project board for it as well, https://github.com/orgs/distributed-system-analysis/projects/16/views/1

----

# Update and Publish the Pbench Agent User's Guide on Read-the-Docs - Pbench

## About Pbench

Pbench is a performance data collection framework for capturing, archiving and curating, analyzing, and visualizing performance data.  The project has three main parts to it: the agent, which captures and collects various data related to performance; the server, which archives the data and provides the curation capabilities, along with the analysis; and the dashboard, which provides the UI to the curation on the server and visualization.

### Problem

Most of the documentation we have for Pbench surrounds the "agent".  We have some documentation in the `gh-pages` branch and some in the `doc` and `docs` sub-directories of the `main` branch.  The current situation is problematic because different pieces of documentation are updated without the others, with no coordination, and too much duplication.

The first, "immediate", goal is to get to one set of documentation for the "agent" published on Read-the-Docs, where the GitHub pages links to those docs, and the `main` branch has one directory where all the documentation sources live.

The second goal is to correct and improve the documentation by making sure it reflects the latest behaviors and serves as a comprehensive reference guide.

### Scope

 * Reorganize the physical source code for the documentation to eliminate duplication (`gh-pages` branch is a full copy of `main`, where there is one copy of the documentation source in the `docs` directory)
 * A clear process is established for building the documentation and publishing to Read-the-Docs
 * Enhancing the documentation to streamline and remove duplication along the way
 * Rewriting sections to match current behaviors
 * Adding missing gaps in the documentation

### Measuring Success

We can measure success by accomplishing the following tasks:

 * Replace `gh-pages` branch layout with a small page that links to "Read-the-Docs"
 * Consolidate the `doc` and `docs` directory into one
 * Create a process for building and pushing to `Read-the-Docs`
   * Release branch automation a stretch goal
 * Review the various sub-system behaviors to ensure they have coverage in the documentation

### Timeline

Calendar year 2022:

 * April 14th - doc development begins
 * April 14th thru May 12th - orientation period
 * June 15th - June 22nd - first monthly evaluation period
 * July 15th - July 22nd - second ...
 * August 15h - August 22nd - third ...
 * September 15th - September 22nd - fourth ...
 * October 14th - October 21st - fifth and final monthly evaluation period
 * November 15th - case study and final project evaluation

### Budget

```
Budget Item                Item Amount   Running Total   Notes
Technical writer stipend        $5,000          $5,000
                                         Total: $5,000
```

## Additional Information

 * [Timeline for Season of Docs 2022](https://developers.google.com/season-of-docs/docs/timeline)

 * [Pbench Season of Docs 2022 - Project Board](https://github.com/orgs/distributed-system-analysis/projects/16/views/1)

**Comment by engr-krooozy** [comment]
Hello @portante 

I am an aspiring GSOD participant for 2022 and I am quite excited about this project. 

Looking forward to connect with you further and learn more about the scope of the project.

**Comment by portante** [comment]
Unfortunately, this project was not selected.
