### ISSUE TITLE
Tool Meister should retry tar ball creation on first failure ignoring warnings

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2692]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description

If the first tar ball fails on creation, the Tool Meister issues a log message indicating the error, but does not complete the protocol with the Tool Data Sink, leaving the Tool Data Sync to hang waiting for ever.

### To Reproduce

There is no known way to make this happen in a reproducible fashion.

### Actual Results

```
192.168.122.192 0280 2022-03-14 21:38:02,387 ERROR 26848 140432394401600 pbench-tool-meister _send_directory 1307 -- Failed to create tar ball; return code: 1
192.168.122.192 0281 2022-03-14 21:38:02,389 WARNING 26848 140432394401600 pbench-tool-meister driver 1721 -- 1 failures encountered for action, <bound method ToolMeister.send_tools of <pbench.agent.tool_meister.ToolMeister object at 0x7fb8f5ac8dc0>>, on data, {'action': 'send', 'args': None, 'directory': '/var/lib/pbench-agent/fio__2022.03.15>
```

### Expected Results

Tool Meister properly sends a tar ball completing the protocol sequence.

### Additional information

Ideally, the Tool Data Sync should timeout if it doesn't hear from a Tool Meister.

The Tool Meister should be able to re-try the `tar` ball creation ignoring all warnings to gather whatever data it can.

The output of the tar command should be captured and logged remotely.

We could consider having all Transient tool `stderr` logged remotely.

**Comment by portante** [comment]
Here are the contents of a Tool Meister work directory where we can see all the `tm-*.out` and `tm-*.err` files which arguably should be just captured and sent remotely instead of living in files.

```
tm.default.26848.ul9har60/192.168.122.192/tm-iostat-start.out
tm.default.26848.ul9har60/192.168.122.192/tm-iostat-start.err
tm.default.26848.ul9har60/192.168.122.192/tm-mpstat-start.out
tm.default.26848.ul9har60/192.168.122.192/tm-mpstat-start.err
tm.default.26848.ul9har60/192.168.122.192/tm-proc-interrupts-start.out
tm.default.26848.ul9har60/192.168.122.192/tm-proc-interrupts-start.err
tm.default.26848.ul9har60/192.168.122.192/tm-proc-vmstat-start.out
tm.default.26848.ul9har60/192.168.122.192/tm-proc-vmstat-start.err
tm.default.26848.ul9har60/192.168.122.192/tm-sar-start.out
tm.default.26848.ul9har60/192.168.122.192/tm-sar-start.err
tm.default.26848.ul9har60/192.168.122.192/tm-iostat-stop.out
tm.default.26848.ul9har60/192.168.122.192/tm-iostat-stop.err
tm.default.26848.ul9har60/192.168.122.192/tm-mpstat-stop.out
tm.default.26848.ul9har60/192.168.122.192/tm-mpstat-stop.err
tm.default.26848.ul9har60/192.168.122.192/tm-proc-interrupts-stop.out
tm.default.26848.ul9har60/192.168.122.192/tm-proc-interrupts-stop.err
tm.default.26848.ul9har60/192.168.122.192/tm-proc-vmstat-stop.out
tm.default.26848.ul9har60/192.168.122.192/tm-proc-vmstat-stop.err
tm.default.26848.ul9har60/192.168.122.192/tm-sar-stop.out
tm.default.26848.ul9har60/192.168.122.192/tm-sar-stop.err
```

**Comment by portante** [comment]
Let's ignore all warnings on the re-try only.  Something like `tar --warning=none`, so that we capture the errors when we try the first time, but the tar up whatever we can on the re-try.  And we should do something to remark in the data collection that we encountered warnings on the initial `tar` command.

**Comment by webbnh** [comment]
Can we capture `stderr` on the first pass, and include that capture on the second?  (That's a joke...but only sort of....  🙂)
