### ISSUE TITLE
What to do about ansible playbooks in the tree

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2700]
We currently have a set of ansilbe roles in the tree that are used to install the pbench agent on a set of hosts. These roles are packaged on Ansible Galaxy as the `pbench.agent` collection. We also have a set of playbooks in the tree, but these are at best examples (and fairly trivial ones at that) of playbooks that run a specific role (or a small set of roles). In most cases, the "real" playbooks are kept internally (personal copies are not uncommon). So the question is: do we want to continue carrying the playbooks in the tree or jettison them?

If we decide to continue carrying them, I think they should be clearly labeled as examples (and perhaps moved into an `examples` subdirectory), with some documentation added to show how to use them for a specific case (e.g. the playbooks currently  use `remote_user` but maybe `become` is more appropriate in other cases: do we want to document that or do we assume that people will know enough about Ansible to be able to adapt them to their needs? Do we provide separate examples for the two cases?) We'd also need to add new playbooks or enhance the existing ones to illustrate what is needed for new capabilities (e.g. firewall port opening of the pbench controller for read/Tool Data SInk).

If we jettison them, is it enough to document the available roles and expect the user to be able to write appropriate playbooks for their use? Or do we refer them to Ansible documentation for that?

Although the above was directed towards the agent, similar questions exist for the server (except that we have not yet made those roles available on Galaxy).

**Comment by ndokos** [comment]
We are probably going to jettison the server ansible roles altogether, in favor of a containerized deployment model.

**Comment by portante** [comment]
Nothing to do here anymore.  The server ansible sub-tree has been removed with PR #2936 and the agent ansible re-organization with PR #2991 resulted in the playbooks now residing in their own sub-directory.
