### ISSUE TITLE
Why are we not using the user's ID for authorization?

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2824]
Why are we not using the user ID for authorization?  Shouldn't we be translating the name to an ID before hand?

_Originally posted by @portante in https://github.com/distributed-system-analysis/pbench/pull/2820#discussion_r866009319_

**Comment by dbutenhof** [comment]
[PBENCH-646](https://issues.redhat.com/browse/PBENCH-646), under the IAM epic
