### ISSUE TITLE
Improve error message for `pbench-generate-token` when server is unreachable

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2839]
The `pbench-generate-token` command has a bad failure mode if server is unreachable:

    Expecting value: line 1 column 1 (char 0)

**Comment by webbnh** [comment]
I believe that this message is a `JSONDecodeError` coming from a call to `json.loads()`, but I cannot figure out which one.  I suspect that it is one inside [this call to `response.json()`](https://github.com/distributed-system-analysis/pbench/blob/e1124bd6a7494dfc66d47597adcd80b5051e5998/lib/pbench/cli/agent/commands/generate_token.py#L33), but I cannot say for sure.  (Why would the response not be in JSON format?)

How was this error obtained?

When I try this, I get either "bad login" or "cannot connect":
```
$ pbench-generate-token --username me --password foo
Cannot connect to 'http://pbench.example.com/api/v1/login'
[...]
$ pbench-generate-token --username me --password foo
Bad login
```
So, the command seems to be behaving as expected, for me....

**Comment by dbutenhof** [comment]
This actually happened to me several times, too, but Peter beat me to writing it up:

```
[root@dhcp31-136 ~]# pbench-generate-token --username roger --password roger
Expecting value: line 1 column 1 (char 0)
```

You're correct that it's a problem in deserializing the response body, presumably because the utility failed to notice the failure. In my case, the server address responds, but the server wasn't running. (It's a proxy error.)

From `/var/log/httpd/access_log`:

```
10.74.16.228 - - [24/May/2022:11:28:27 +0000] "-" 408 - "-" "-"
```

And `/var/log/httpd/error_log`:

```
[Tue May 24 11:28:16.650153 2022] [proxy:error] [pid 213363:tid 140409577658112] (111)Connection refused: AH00957: HTTP: attempt to connect to 10.1.170.201:8001 (10.1.170.201) failed
[Tue May 24 11:28:16.650204 2022] [proxy_http:error] [pid 213363:tid 140409577658112] [client 10.16.31.136:59586] AH01114: HTTP: failed to make connection to backend: 10.1.170.201
```

**Comment by webbnh** [comment]
OK, so the challenge is that some responses will have JSON bodies and some won't, and the tool has to have some way of telling them apart....  I suppose that it could assume that it's JSON and, if it gets a `JSONDecodeError` it could just use the message as is.  Sound reasonable?

**Comment by dbutenhof** [comment]
Maybe; I'm not sure we have a log of exactly which paths we're hitting here on the client side.

We may get a raw HTTP error, or an HTTP error with a JSON response body (e.g., our standard `"message"` key), or a JSON body with the username and token value. Or at least, that's three possible alternatives. We need to at least handle all of them cleanly.
