### ISSUE TITLE
Pbench agent `profile` emitting error message on Python 3.10 environments

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#2884]
I logged into a system that had just installed the `pbench-agent` v0.71.0 release, a Fedora 36 box with Python 3.10 as the system default, and the following message was emitted before my first command prompt:

```
ls: cannot access '/opt/pbench-agent/lib*/python3.*/site-packages': No such file or directory
```

This appears to be due to the fact that for Python 3.10 the python modules are installed under `/opt/pbench-agent/local/lib*/python3.*/site-packages/` (note the addition of `local` before `lib` in the path).

**Comment by webbnh** [comment]
Possibly related is #2872.

**Comment by webbnh** [comment]
FWIW, if/when we adapt to the Fedora packaging rules, this problem will presumably go away....

**Comment by ndokos** [comment]
Closing now that PR #3020 is merged.
