### ISSUE TITLE
[check_install_rpm] the installation of pbench-fio-2.2.5 failed

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#289]
Just updated to 0.39 and get this message when running pbench-fio.  Making a small edit to the pbench-fio script allows it to work:

> $ diff -u pbench-fio~ pbench-fio
> --- pbench-fio~ 2016-07-15 16:24:17.000000000 -0400
> +++ pbench-fio  2016-07-18 11:41:57.032009189 -0400
> @@ -12,7 +12,7 @@
>  benchmark_rpm=$script_name
>  benchmark="fio"
>  benchmark_bin=/usr/local/bin/$benchmark
> -ver=2.2.5
> +ver=2.2.11
>   
>  # Every bench-script follows a similar sequence:
>  # 1) process bench script arguments
>

**Comment by ndokos** [comment]
Ugh - thanks for finding this! I'll fix it and build an updated RPM.

**Comment by ndokos** [comment]
PR #290 addresses this plus two more version mismatches: iozone and netperf (although the netperf script seems to have bit-rotted a bit: I'll open an issue for it).
