### ISSUE TITLE
pbench-agent-0.39-2g4f9ab11.noarch.rpm missing process-iteration-samples

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#292]
rpm2cpio pbench-agent-0.39-2g4f9ab11.noarch.rpm | cpio -itv | grep process-iteration-samples
1097 blocks

Not sure how this happened, but that script is critical for pbench-uperf

**Comment by ndokos** [comment]
Caught by an exclude pattern that was too wide. Building pbench-agent-0.39-3g4f9ab11 now.
Update with

    dnf clean expire-cache
    dnf update pbench-agent
