### ISSUE TITLE
[BUG] pbench-linpack --pre-check-only does not work properly

### ISSUE THREAD

**Issue by ldoktor** [distributed-system-analysis/pbench#2924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `pbench-linpack --pre-check-only` does not work properly on the latest 0.71.

### To Reproduce

pbench-linpack --pre-check-only 11.1.3

### Actual Results

[linpack] ERROR: You must specify the version of the LINPACK binary

### Expected Results

It should check whether `pbench-linpack-11.1.3` is installed

### Additional information

I am using the https://download.copr.fedorainfracloud.org/results/portante/pbench-test/epel-9-x86_64/04557342-pbench-agent/pbench-agent-0.71.0-1g546bbc124.noarch.rpm version

The problem seems to be the `--` opt parsing. The workflow is:

1. `arg=--pre-check-only` (`@* => --pre-check-only -- 11.1.3`)
2. `shift` (`@* => 11.1.3`)
3. `--pre-check-only` is handled
4. `arg=--`
5. `shift` (`@* => 11.1.3)
6. `--` is handled, which contains additional `shift`, which shifts out the 11.1.3 (`@* =>`)
7. `pre_check ${@}` is executed but because of the additional `shift` it won't include the version argument

**Comment by ldoktor** [comment]
Note this had been observed while trying to run pbench-linpack on a remote client via `pbench-linpack --clients=$ADDR` which reports missing pbench-linpack, which is installed on both host and the guest.

**Comment by ndokos** [comment]
@ldoktor I think the fix is to get rid of the `shift` on line 112. I know you are on your way out the door, but you might want to try it. Effectively, your workaround provides an extra argument for the `shift` to chomp on, in order to leave the rest alone. That's what I'm implementing. Let me know when you get back :-)

**Comment by ldoktor** [comment]
That was my suspect as well but I was afraid to break some other workflow :-) Thank you for the quick fix.

**Comment by ldoktor** [comment]
@ndokos you asked for it so I gave it a try... There is still one more thing to do: https://github.com/distributed-system-analysis/pbench/pull/2929
