### ISSUE TITLE
Bugs in pbench-tool-trigger and pbench-list-triggers

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#296]
pbench-tool-trigger depends on the environment variable `pbench_run` which specifies the default run directory for pbench (/var/lib/pbench-agent). That is normally defined by sourcing the base file (/opt/pbench-agent/base) in pbench scripts. However, pbench-tool-trigger is generally used by user scripts, which means that either they will have to source the base file themselves, or we have to make pbench-tool-trigger get the value of pbench_run from the config file, the same way that the base file does.

pbench-tool-trigger is still using the non-prefix names for {start,stop}-tools.

pbench-list-triggers does not work at all.

**Comment by portante** [comment]
See PR #301
