### ISSUE TITLE
[BUG] pbench-uperf run fails with port 20000 open in the firewall because it starts with 20010

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#2968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

pbench-uperf is supposed to start with port 20000 for the first server and then go up with an increment of 10 for each subsequent pair. Instead, it starts with 20010.

### To Reproduce

I opened port 20000 (on both client and server hosts) and ran

```
pbench-uperf --samples=1 --clients=${UPERF_CLIENTS} --servers=${UPERF_SERVERS} --test-types=stream,maerts,bidirec,rr --instances=8 --protocols=tcp,udp --runtime=30 --message-sizes=16384
```

### Actual Results

```
# cd ${pbench_run_dir{
# cat */sample1/client\:\:dhcp31-125-server\:\:dhcp31-106\:20010--client_output.txt
Error getting SSL CTX:1
Allocating shared memory of size 162984 bytes
Error connecting to dhcp31-106

** TCP: Cannot connect to dhcp31-106:20010 No route to host
Error getting SSL CTX:1
Allocating shared memory of size 159592 bytes
Error connecting to dhcp31-106

** TCP: Cannot connect to dhcp31-106:20010 No route to host
Error getting SSL CTX:1
Allocating shared memory of size 159592 bytes
Error connecting to dhcp31-106

...
```

Note the port number.

### Expected Results

No errors.

### Additional information

The bug is that we set `$server_nr=1` before the loop in `bench-scripts/pbench-uperf:L613`.  We should be starting at 0.

**Comment by portante** [comment]
Not worth changing the actual behavior, we should fix the documentation to describe the current behavior.

**Comment by ndokos** [comment]
I'll fix the doc. In addition, the doc needs to mention that the local ports on each system need to be open.
