### ISSUE TITLE
Problems installing the pbench agent on RHEL 9.2

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#3054]
When running the ansible script (using `ansible` RPM v2.9.7, Fedora 35), you get the following error:

```
$ ansible-playbook -i ./myhosts.inv pbench-agent-install.yml

PLAY [install pbench-agent] *************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [10.16.31.196]

TASK [pbench_repo_install : ensure we have the pbench.repo file properly in place] ******************************************************
fatal: [10.16.31.196]: FAILED! => {"changed": false, "checksum": "d74554308e882e7a6f9463530f9f71090a273c0f", "msg": "Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!"}

PLAY RECAP ******************************************************************************************************************************
10.16.31.196               : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

However, the package you really need, at least for RHEL 9, is the following, and once it is installed, install completes without issue.

```
dnf install python3-libselinux.x86_64
```

(It seems they flipped the name.)

**Comment by webbnh** [comment]
> It seems they flipped the name.

IIRC, both names are in use, depending on which version of which distro you are targeting.  (And, IIRC, both names are available in the _same_ distro in certain cases.)

Looking at [server/rpm/pbench-server.spec.j2](https://github.com/distributed-system-analysis/pbench/blob/d8f871dcc1fdb5ebbef23e11b9a636d6b17588bb/server/rpm/pbench-server.spec.j2#L16), we use `python3-libselinux` on RHEL-7 and `libselinux-python3` everywhere else.

Looking at [jenkins/development.Dockerfile.j2](https://github.com/distributed-system-analysis/pbench/blob/d8f871dcc1fdb5ebbef23e11b9a636d6b17588bb/jenkins/development.Dockerfile.j2#L140), we use `python3-libselinux`...but I'm not clear on which distro version that's targeting.

So...yeah.

**Comment by portante** [comment]
This was an agent install.

**Comment by webbnh** [comment]
Yeah, but the stuff in the spec file and Dockerfile are the names of RPM packages...which doesn't so much have anything to do with what they are being installed _for_....  🤣

**Comment by portante** [comment]
But the issue is that this was hit on the agent side, but we don't have that dependency in the RPMs on the agent side.  Something in the Ansible environment for the agent caused this.

**Comment by portante** [comment]
That is, this has nothing to do with the Pbench Server of the Jenkins environment.

**Comment by webbnh** [comment]
I get that this has nothing to do (_presumably_...) with the Pbench Server or the Jenkins stuff.  I hauled those up as examples of where we, nevertheless, do install the package in question, and where it has various names.

Nevertheless, are you suggesting that the Agent doesn't have a (direct) dependency on the SELinux Python bindings?  If that's the case, then (presumably) the Agent has an indirect dependency on them, and that dependent hasn't gotten the memo regarding the current name of the library package.  (I hope DNF can help find it....)

**Comment by portante** [comment]
> I get that this has nothing to do (_presumably_...) with the Pbench Server or the Jenkins stuff. I hauled those up as examples of where we, nevertheless, do install the package in question where it has various names.

Gotcha.

> Nevertheless, are you suggesting that the Agent does not have a (direct) dependency on the SELinux Python bindings?

Yes

> If that's the case, then (presumably) the Agent has an indirect dependency on them, and that dependent hasn't gotten the memo regarding the current name of the library package. (I hope DNF can help find it....)

It is unclear if it is an indirect RPM dependency of the `pbench-agent` RPM itself, or if it is some ansible module or command being invoked by ansible that has that dependency.

We need to get from Tom the Ansible step that failed, which is not included above.

**Comment by portante** [comment]
It appears to be coming from https://github.com/distributed-system-analysis/pbench/blob/main/agent/ansible/collection/roles/pbench_repo_install/tasks/main.yml#L9.  Looks like an Ansible `template` module thing.

**Comment by portante** [comment]
This most likely https://github.com/ansible/ansible/issues/56243.

**Comment by portante** [comment]
Confirmed that an Ansible version update as described in https://github.com/ansible/ansible/issues/56243 fixed the issue.
