### ISSUE TITLE
Centrally log pbench-server operations

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#310]
Instead of only using local log files, consider sending (structured) logs to a central server.

**Comment by portante** [comment]
We have started to address this issue with #1089.  As we convert more of the server infrastructure to python we'll be able to log centrally much easier.

**Comment by riya-17** [comment]
@portante @ndokos Can you please throw more light on this issue?

**Comment by portante** [comment]
We want to use the [`SyslogHandler`](https://docs.python.org/3/library/logging.handlers.html#sysloghandler) instead of the [`FileHandler`](https://docs.python.org/3/library/logging.handlers.html#filehandler) for production going forward, while still using the `FileHandler` during the unit tests.
