### ISSUE TITLE
improve class variable initialization of `OpenIDClient` class

### ISSUE THREAD

**Issue by npalaska** [distributed-system-analysis/pbench#3102]
We still have the issue that we're calling an instance method from inside the instance's constructor.  We should have that big "caution" comment here warning those who come after that before line 64 is the object initialization and what comes after it is something else, so that they don't add something in the wrong place.

Perhaps the solution would be for this class to provide a factory method which could be called to instantiate and initialize the class and instance; then, instead of calling the constructor, anybody who wants an `OpenIDClient` object could call the factory function, and that function could call the constructor and then use the resulting object to set the cached key value and the well-known endpoints.  It could encapsulate the settings so that they only get done once, and it could even reuse the instance if we want it to be a singleton.

Or, maybe we just need to get rid of this class too...do we really need to instantiate this object?  Do we need to do so more than once?  If not, then we probably don't need a class here.

_Originally posted by @webbnh in https://github.com/distributed-system-analysis/pbench/pull/3095#discussion_r1038643079_

**Comment by portante** [comment]
Will be solved by PR #3114 and/or derivatives.
