### ISSUE TITLE
pbench-fio: add epoch time

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#313]
Add epoch time for statistics that use 0-based timestamps.

**Comment by cronburg** [comment]
The json output of fio has a timestamp, but it's when the json is created not when the job(s) start. fio uses cpu time (rdtsc) to get the 0-based timestamps in the logs. Is there an easy way to get the unix epoch time of TSC=0 in C? Also have to increment by the value of `td->epoch` (which is as much as 200 ms from when fio starts) - each thread has its' own reference time.

**Comment by atheurer** [comment]
@cronburg, are you saying td->epoch is not the start time of the job?

I assumed it was by the line in fio.h:

struct timeval epoch;   /* time job was started */

but perhaps in practice that is not true.

**Comment by cronburg** [comment]
This:
    printf("td->epoch: %lu, %lu\n", td->epoch.tv_sec, td->epoch.tv_usec);

Prints this:
    td->epoch: 0, 122882

**Comment by cronburg** [comment]
Try out [fio PR 227](https://github.com/axboe/fio/pull/227). Enable epoch time logging with `--log_unix_epoch=1` option.

**Comment by cronburg** [comment]
@k-rister - what's the option for formatting the x-axis as a date/time with jschart? I have millisecond epoch timestamps and with a default 'xy' chart I get this:

![jschart](http://i.imgur.com/3OhhZs4.png)

**Comment by k-rister** [comment]
Replace the 'xy' with 'timeseries'.

**Comment by cronburg** [comment]
Updates I need to make to pbench-fio (tomorrow) to fully take advantage of epoch time reporting:

- configparser - allow_no_value=True in pbench-fio.
- use `--job-file` option of fiologparser_hist.py from pbench-fio to clean up grep for log_hist_msec.
- change 'xy' to 'timeseries' in jschart code generated when log_unix_epoch is present in job file.
