### ISSUE TITLE
enable collectd plugin while collecting sosreport

### ISSUE THREAD

**Issue by arcolife** [distributed-system-analysis/pbench#322]
We would need to add collectd related information to a pbench run and so we might need to add a collectd plugin to sosreport collection. Ref: https://github.com/sosreport/sos/pull/866 

Related discussions:
- https://github.com/distributed-system-analysis/pbench/issues/180
- https://github.com/distributed-system-analysis/pbench/issues/164

**Comment by ndokos** [comment]
This was done by  commit https://github.com/distributed-system-analysis/pbench/commit/20699cabaadc41e9c270ae02fcad5d35335bc0c and it is part of v0.60.
