### ISSUE TITLE
Add archive only option for uploading tar balls

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#3236]
We need an option to direct the pbench server NOT to unpack the tar ball OR index it, but just store it.

That parameter would be used in situations where a user is not interested in the Pbench Server processing data in the tar ball.

**Comment by dbutenhof** [comment]
Nikhil made a comment on my `PUT ?metadata` change that at first I thought made no sense and then I realized might actually not be a bad idea.

We could implement this as a `server.archiveonly` metadata value, with special case handling in `setvalue` much like `server.deletion`; it's a bit "out of band" but perhaps convenient, so you'd be able to do `PUT /upload/{file}?metadata=server.archiveonly:true` on upload. This would provide a natural path to rescind the directive later, too, simply by doing `PUT /dataset/metadata/{dataset} {"metadata": {"server.archiveonly": False}}` (which would implicitly `READY` the `UNPACK` operation and set the chain in motion). ((Assuming we really want to allow doing that ... but in the case of our migrated 0.69 datasets that might be handy.))
