### ISSUE TITLE
pbench-uperf where hosts are both clients and servers

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#327]
I've been able to run pbench-uperf between a single pair of hosts but when I try to run a test where hosts act as both client and server I get this:

http://pastebin.test.redhat.com/402458

I need to do this to emulate Ceph's network behavior.  reverting to my own netperf scripts until I can sort out how to use this tool.

**Comment by ndokos** [comment]
@bengland2, IIUC, a couple of people ran into this last week and @atheurer has a fix, but I'm not sure in what stage  it is. I can build a test RPM using his branch if necessary.

**Comment by atheurer** [comment]
Nick, pull request is here:
https://github.com/distributed-system-analysis/pbench/pull/328

**Comment by atheurer** [comment]
This is a duplicate of issue #321

**Comment by ndokos** [comment]
Fixed by PR#328.
