### ISSUE TITLE
fio-postprocess to generate result.json for test result sample

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#329]
This is the first step in converting pbench-fio to use the same metrics format that pbench-uperf uses.  Once the test iteration samples use the json format, the process-iteration-samples and generate-benchmark-summary scripts can be used.

**Comment by portante** [comment]
See Joe T's work from Browbeat on indexing FIO data, https://review.openstack.org/#/c/350596/

**Comment by portante** [comment]
Implemented via #590.
