### ISSUE TITLE
pbench-fio does not accept client list file

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#333]
The option to pass a file of target client names to the --clients arg is in fio but does not work in pbench-fio.   e.g., this command will succeed ...

  /usr/local/bin/fio --client=vms.list.128 <...>

... where using "pbench-fio --client=vms.list.128" will not regardless if I use --client or --clients. It tries to resolve the passed filename as a hostname.

**Comment by atheurer** [comment]
I will add a --client-file option

**Comment by wilkins11** [comment]
Thanks!

**Comment by ndokos** [comment]
Fixed by PR#336.
