### ISSUE TITLE
pbench-fio missing --config option in --help

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#335]

**Comment by ndokos** [comment]
Also max-stddev, max_failures, install, noinstall, iodepth, jobs-per-dev.

And the short option for --config is -j :-)

**Comment by atheurer** [comment]
OK, I will add those.

**Comment by cronburg** [comment]
Also the help string says `postprocess_only` but it's actually `postprocess-only`.

**Comment by ndokos** [comment]
Proposal: get rid of --noinstall and keep its default behavior only (--noinstall=n).
It's confusing and I'm not sure the "y" value is helpful.
