### ISSUE TITLE
pbench-fio errs copying logs

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#338]
I see the following errors when running pbench-fio ...

running fio job: /var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/fio.job
scp: /var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/\*.log: No such file or directory
scp: /var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/\*.log: No such file or directory
scp: /var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/\*.log: No such file or directory
/bin/rm: cannot remove '/var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/\*.log': No such file or directory
/bin/rm: cannot remove '/var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/\*.log': No such file or directory
/bin/rm: cannot remove '/var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/\*.log': No such file or directory

... and indeed the logs are not where it looks. I'm not certain what logs it's looking for but I do see them in only one of the clients dirs ... /var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/clients/vm1/

**Comment by wilkins11** [comment]
Actually I see them on vm1 because I drive pbench-fio from there. None of the other vm# subdirs have anything more than summary-result.txt. Not sure what the cp/rm errors are yet.

# ls -l /var/lib/pbench-agent/fio__2016-08-16_14:43:03/1-randwrite-4KiB/sample1/clients/vm1/
total 24K
drwxr-xr-x. 2 root root 4.0K Aug 16 14:44 .
drwxr-xr-x. 6 root root   46 Aug 16 14:44 ..
-rw-r--r--. 1 root root  994 Aug 16 14:44 fio_bw.1.log
-rw-r--r--. 1 root root 1.1K Aug 16 14:44 fio_clat.1.log
-rw-r--r--. 1 root root  994 Aug 16 14:44 fio_iops.1.log
-rw-r--r--. 1 root root 1.1K Aug 16 14:44 fio_lat.1.log
-rw-r--r--. 1 root root    0 Aug 16 14:44 fio_slat.1.log
-rw-r--r--. 1 root root  603 Aug 16 14:44 summary-result.txt

**Comment by wilkins11** [comment]
I opted to use a different test driver so that all vms would behave the same. When I run from the new driver (smfnfs), I still see the cp/rm errors and the fio log files I do see are in /var/lib/pbench-agent/fio__2016-08-16_17:27:08/1-randwrite-4KiB/sample1 but it's unclear to me if they're for one guest or an aggregate.

root@smfnfs:~
\# ll /var/lib/pbench-agent/fio__2016-08-16_17:27:08/1-randwrite-4KiB/sample1
total 880K
drwxr-xr-x.   4 root root 4.0K Aug 16 17:30 .
drwxr-xr-x.   3 root root   73 Aug 16 17:30 ..
drwxr-xr-x. 130 root root 4.0K Aug 16 17:30 clients
-rw-r--r--.   1 root root 1.9K Aug 16 17:29 fio_bw.1.log
-rw-r--r--.   1 root root 2.3K Aug 16 17:29 fio_clat.1.log
-rwxr-xr-x.   1 root root 2.1K Aug 16 17:27 fio.cmd
-rw-r--r--.   1 root root 1.9K Aug 16 17:29 fio_iops.1.log
-rw-r--r--.   1 root root  240 Aug 16 17:27 fio.job
-rw-r--r--.   1 root root 2.3K Aug 16 17:29 fio_lat.1.log
-rw-r--r--.   1 root root 784K Aug 16 17:29 fio-result.txt
-rw-r--r--.   1 root root    0 Aug 16 17:29 fio_slat.1.log
-rw-r--r--.   1 root root  163 Aug 16 17:30 result.txt
-rw-r--r--.   1 root root  31K Aug 16 17:30 summary-result.html
-rw-r--r--.   1 root root  26K Aug 16 17:30 summary-result.txt
drwxr-xr-x.   3 root root   28 Aug 16 17:30 tools-default

All the sample1/clients/vm* subdirs only have a summary-results.txt file.

**Comment by bengland2** [comment]
@ndokos and I discussed this one.  There are scp commands in pbench-fio that contain wildcards.  If no files matching the wildcard exist, then you get these kinds of errors.  Perhaps it would be more easy to understand if it detected that the test failed, told the user, and didn't try to copy the files.  It's annoying to have to wade through lengthy error messages to see what happened.   @wilkins11 is this in fact what happened?  Do you get these kinds of errors when the test succeeds?  If so it's sort of a cosmetic problem but would be nice to fix.

**Comment by wilkins11** [comment]
@bengland2, yes the scp/mv errors are present every time. Why not just direct all scp/mv output to /dev/null?

**Comment by ndokos** [comment]
Commit 19cf29d0a13bf3206329f3b588e913ae6f19384d￼  in PR #378 did just that. That should be part of the test RPM 0.39-92 (and will therefore be part of 0.40).

**Comment by ndokos** [comment]
Closing this - please reopen if necessary.
