### ISSUE TITLE
pbench-fio 2.14-1 references pbench_fio

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#340]
I did not see this prior to the recent yum update of pbench-fio.

\# rpmq pbench-fio
pbench-fio-2.14-1.x86_64

\# pbench-fio -t randwrite --samples=1 --clients=vm1,vm2 -r 120 -b 4 -s 1024m --directory=/srv/fio/ --sync=1 --ioengine sync --iodepth=2 --direct=1

verifying clients have fio installed
bash: /opt/pbench-agent/bench-scripts/pbench_fio: No such file or directory
bash: /opt/pbench-agent/bench-scripts/pbench_fio: No such file or directory
Collecting system information
   ...

**Comment by ndokos** [comment]
PR #319 fixed this.
