### ISSUE TITLE
Backport `pbench-tools-kill` to b0.72?

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#3404]
Hunting and killing wayward tool-meister paraphernalia is a pain: @portante added `pbench-tools-kill` to `main` but maybe we should backport it to `b0.72`.

**Comment by portante** [comment]
Isn't it already there?  We only branched it recently.

**Comment by ndokos** [comment]
Yes, but it's called `pbench-kill-tools` and I was looking under `t`, not under `k` :-)
