### ISSUE TITLE
run fiologparser(_hist) from fio-postprocess and generate js / html to view CSVs

### ISSUE THREAD

**Issue by cronburg** [distributed-system-analysis/pbench#343]
@ndokos how should I go about referencing `fiologparser_hist.py` from pbench scripts? Right now I manually add it to my `PATH` - it's in upstream fio, but does not get installed by `make install`.

Also note that `fiologparser_hist.py` depends on `pandas` and `numpy`. I can get rid of the pandas dependency fairly painlessly if necessary, but numpy is used throughout the whole program. Presumably we would skip / print a warning when numpy is missing.

We can also optionally run `fiologparser.py` on the non-histogram files if desired.

**Comment by ndokos** [comment]
I added a manual installation step in the spec file to install the script in /usr/local/bin. I am rebuilding the RPM on COPR pbench-test to incorporate that change.

In the longer term. @cronburg is going to submit a PR to upstream fio to have "make install" DTRT.

**Comment by cronburg** [comment]
Man page and updates to `make install` in [PR 229 to fio](https://github.com/axboe/fio/pull/229).
