### ISSUE TITLE
pbench-fio should use --client in fio command

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#358]
pbench-fio does accept a client list file now (much thanks) but doesn't need to parse it into the fio command. It should just pass the filename along to fio using the "--client \<file\>" option already present in fio, greatly reducing the size of the cmdline. This helps a LOT when sifting back through the buffers or run logs looking for a single error, even with the 256 guests I run now, and will matter even more in the scale lab. Thanks.

**Comment by wilkins11** [comment]
If possible, we should save the client-file passed with all the other stuff archived by pbench-fio.

**Comment by ndokos** [comment]
Do you have a preference for the name? It can be either the original name or a fixed name and for indexing purposes, a fixed name is prefereble, but I can certainly work around that.

**Comment by wilkins11** [comment]
no pref, something obvious I imagine. clients.list or something as simple.

**Comment by ndokos** [comment]
OK - added a commit to PR #378.

**Comment by wilkins11** [comment]
pbench-fio-2.14-9 errs using a client list file. 

> pbench-fio: line 530: typeset: 128 vms.list.128: syntax error: invalid arithmetic operator (error token is ".list.128")

Line 530:
`typeset -i nclients=$(wc -l $client_file) `
