### ISSUE TITLE
Clean up loop logic in pprof tool

### ISSUE THREAD

**Issue by mffiedler** [distributed-system-analysis/pbench#366]
The pprof tool currently uses the $interval parameter to determine the sample time for the pprof profile.   This works in practice but it does not allow separate sampling time and collection intervals.   In a long run I might only want to run pprof every 10 minutes, but do not need to have profile sampling running that whole time.  

Add logic to split the profiling interval from the tool invocation interval.

**Comment by mffiedler** [comment]
This can be assigned to me. 

@ekuric fyi if you have any comments.

**Comment by portante** [comment]
Closed by #357
