### ISSUE TITLE
Track fix for pidstat omitting kernel threads when using -l option

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#368]
See https://github.com/sysstat/sysstat/issues/125

**Comment by portante** [comment]
The following fix has been applied to sysstat upstream: https://github.com/sysstat/sysstat/commit/4554415980ef965369db76c2bd6fc85d6b6eaad2

**Comment by ndokos** [comment]
Built pbench-sysstat-11.5.1 on COPR pbench repo. This incorporates the pidstat fix that @atheurer submitted. Closing this, but if there are problems, please reopen.
