### ISSUE TITLE
 unique filenames for fio --client logs

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#370]
https://github.com/axboe/fio/pull/241  has not been accepted yet but I think it will be, this is needed for fio --client to retrieve files from remote host and assign them unique names in a test directory.   It was retrieving files before but using the same name for all clients.   I'll post here when it's accepted so that it will be easier for you to pull fio from upstream.

**Comment by ndokos** [comment]
pbench-fio-2.14-6, available from the COPR pbench-test repo, incorporates this PR, in addition to the top of the tip of axboe's repo as of this morning (2016-09-14):

https://github.com/axboe/fio/commit/308d69b5d340577b7886696f39753b7ba5ae9e11

**Comment by bengland2** [comment]
axboe/fio PR 241 was successfully merged today, so from now on you should not have to use PR 241.  Thanks @ndokos for putting up with this irritation which I should have dealt with sooner.

**Comment by ndokos** [comment]
No problem at all - I'll rebuild a pbench-fio RPM based on axboe/fio master. Thanks!
