### ISSUE TITLE
pbench-uperf port number usage leads to lack of scalability

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#375]
pbench-uperf cannot run very large sets of clients and servers at present, because of its port number allocation.  

**Analysis:**

I ran a test like this:

    -=>>cat pbench-uperf.sh 
    c="172.18.64"
    pbench-uperf -t stream -p tcp -i 8 -r 120 -m 4194304 -p tcp \
      -C c07-h05-6048r,c07-h09-6048r,c07-h13-6048r,c07-h17-6048r,c07-h21-6048r,c07-h25-6048r,c07-h01-6048r,$c.232,$c.240,$c.229,$c.242,$c.235,$c.245,$c.248 \
      -S c07-h01-6048r,c07-h05-6048r,c07-h09-6048r,c07-h13-6048r,c07-h17-6048r,c07-h21-6048r,c07-h25-6048r,$c.240,$c.229,$c.242,$c.235,$c.245,$c.248,$c.232

and @ndokos  noticed that the last thread did not succeed in connecting to the uperf server.  I noticed that the error for the last thread was:

    Error connecting to 172.18.64.232
    ** TCP: Cannot connect to 172.18.64.232:34000 Connection refused

I found an article [here](http://stackoverflow.com/questions/113224/what-is-the-largest-tcp-ip-network-port-number-allowable-for-ipv4) discussing TCP port number usage and it mentioned that there were constraints on what TCP port numbers a process could bind to, defined here:

    # cat /proc/sys/net/ipv4/ip_local_port_range
    32768	60999

The way that pbench assigns port numbers to uperf servers is starting at 21000 in increments of 1000.  There were 14 uperf servers created in the above test, so by the time we get to the last thread we are above this limit.   I then ran a test with only 10 threads and I do not see the error.  

**Conclusion:**

pbench-uperf could support much larger tests by incrementing port number by 10 for each new thread instead of by 1000.     This would in theory make pbench-uperf able to scale to roughly (32000-21000)/10 = 1100 threads.

What if some other process has bound the port number?  This is likely to happen for large tests.  A solution would be to detect that the port number is in use with equivalent of 

    netstat -an | grep tcp | grep -q ":$candidate_port "

and skip to next one - it really doesn't matter which port number we use so long as it is a valid port number that no one else is using and the client knows which one to use.  I might submit a PR for this if people agree.

**Comment by ndokos** [comment]
I don't think this explains what you see: ip_local_port_range is the range of dynamic ports I believe, so
everything in between should be allowed. Obviously however, smaller port numbers are also allowed (many of them are supposed to be "registered" with IANA, but nobody enforces the rule: if the port is free you can get it, and if it isn't and you don't allow yourself the flexibility of getting a different one, then you fail). So it's not clear to me why 34000 fails: it's in the allowed range - maybe it's in use and uperf does not allow itself to look for another one? Disclaimer: I'm not a network stack person, so treat this as hearsay.

**Comment by atheurer** [comment]
I don't have an answer for the range limits issue, but I am OK with incrementing the port ID by "1" each time we launch a new server.  I am fine with a PR #377, but not with PR #388

**Comment by ndokos** [comment]
PR #390 (essentially PR #377 with merge conflicts resolved) was merged. It uses an increment of 10 but that is easy to change if desired.
