### ISSUE TITLE
add support for collectd, continuously forwarded to a central server

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#379]
We need to be able to support centrally collected metrics, in particular for collectd forwarded setups.

**Comment by portante** [comment]
Doing something like:

```
$ pbench-register-tool --external-type=(prometheus|carbon|graphite|...) --url="https://tool.url/" --name="<user given name>"
```

**Comment by ndokos** [comment]
Is the name of the tool really up to the user? I thought we'd have a fixed name (e.g. "external-data-source") and the other parameters would be given to pbench-register-tool in the usual way:

     pbench-register-tool --name=external-data-source -- --source-name=... --url=... --source-type=...
