### ISSUE TITLE
pbench-uperf not generating .html file in results summary

### ISSUE THREAD

**Issue by vikaschoudhary16** [distributed-system-analysis/pbench#391]
Actually i am using a [test harness ](https://github.com/openshift/svt/tree/master/networking/synthetic) which uses pbench-uperf internally and it is expected to generate [results summary along with html files on bench server](http://pbench.perf.lab.eng.bos.redhat.com/results/dell-r620-01/uperf_pod-to-pod_PODS_1_TCP_2016-09-20_04:25:03/). Somehow html file is not getting created.

To debug further I ran pbench-uperf between two physical machines and observed following errors:
**scp: /var/lib/pbench-agent/uperf_test-run_2016-09-20_05:13:46/1-tcp_stream-64B-1i/sample1/client::dell-r620-01.perf.lab.eng.rdu.redhat.com-server::dell-r730-02.perf.lab.eng.rdu.redhat.com:20000--client_output.txt: No such file or directory**

**Comment by ashishkamra** [comment]
@atheurer @vikaschoudhary16 - is this still a problem?
