### ISSUE TITLE
pbench-fio errs using client-file

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#392]
> /opt/pbench-agent/bench-scripts/pbench-fio: line 530: typeset: 128 vms.list.128: syntax error: invalid arithmetic operator (error token is ".list.128")

This is caused by a missing "<" in line 530. It should be ...

    `typeset -i nclients=$(wc -l < $client_file)`

Once fixed, fio fails with ...

> fio: failed to resolve <vms.list.128> (Name or service not known)
> fio: failed adding client vms.list.128

This is caused by the pushd (to the pbench_run_dir sample dir) done just prior to the fio command so that the client list file is no longer local. I worked around it by passing --client-file=${PWD}/filename  instead of just the filename. I imagine pbench-fio should copy the file to the rundir.

**Comment by ndokos** [comment]
The wc error is fixed in PR #393 already (in a different way).

I'll use your suggested solution to fix the second one (in the same PR).

**Comment by portante** [comment]
Closed via #393.
