### ISSUE TITLE
pbench-fio-2.14-9 errs calling fiologparser_hist

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#394]
>   ...
> fio job complete
> Traceback (most recent call last):
>   File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
>     main(p.parse_args())
>   File "/usr/local/bin/fiologparser_hist.py", line 284, in main
>     with open(ctx.FILE[0], 'r') as fp:
> IOError: [Errno 2] No such file or directory: '/var/lib/pbench-
> agent/fio__2016-09-20_13:44:43/1-randread-4KiB/sample1/clients/\*/\*_clat_hist.\*'
> Chart Type: xy
> Traceback (most recent call last):
>   File "/usr/local/bin/fiologparser_hist.py", line 387, in <module>
>     main(p.parse_args())
>   File "/usr/local/bin/fiologparser_hist.py", line 284, in main
>     with open(ctx.FILE[0], 'r') as fp:
> IOError: [Errno 2] No such file or directory: '/var/lib/pbench-agent/fio__2016-09-20_13:44:43/1-randread-4KiB/sample\*/clients/\*/\*_clat_hist.\*'
> Chart Type: xy
> readwrite_IOPS: 3200.01 average: 3200.01 stddev: 0.0% closest-sample: 1
> Iteration 1-randread-4KiB complete (1 of 1), with 1 pass and 0 failures
> Collecting system information
>   ...

**Comment by ndokos** [comment]
@wilkins11: is it enough to say "OK, there are no clat_hist files, so we'll skip the call to fiologparser_hist.py"? Or is it the case that there *should* be clat_hist files?

**Comment by wilkins11** [comment]
I see nothing wrong with the first sentence logic. However in this case there are hist logs.  http://milo.perf.lab.eng.bos.redhat.com/pub/20160920-1344_pbfio-randread-128i-iops25-rt240m_drop2/1-randread-4KiB/reference-result/

**Comment by ndokos** [comment]
@wilkins11: is this still a problem with v0.40?

**Comment by wilkins11** [comment]
Not that I've noticed. A recent log ... http://tintin.perf.lab.eng.bos.redhat.com/pub/20160928-2354_pbfio-randwrite-128i-iops25-rt540m_drop5/20160928-2354_pbfio-randwrite-128i-iops25-rt540m_drop5.log

**Comment by portante** [comment]
Please re-open if this problem comes up again.
