### ISSUE TITLE
Plot p95 rather than p90 and p99

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#404]
The graph built in the hist dir is missing data points.   e.g.,  http://tintin.lab.bos.redhat.com/pub/20161009-1623_pbfio-randwrite-128i-25iops-120m_noTHP-base1/1-randwrite-4KiB/reference-result/hist/results.html

**Comment by wilkins11** [comment]
Hmm, looks to have been fixed already. Plz ignore.

**Comment by wilkins11** [comment]
Can we plot p95 rather than p90 and p99? I assume that's the 95th percentile call latency.

**Comment by bengland2** [comment]
can we include p95 along with the rest of the percentiles?    95th-percentile latency is what we are using in Cisco study to evaluate fio latency over time.  You collected the raw data, I just want to include it in  the graph.

**Comment by ndokos** [comment]
Closed by PR #426
