### ISSUE TITLE
pbench-moongen sometimes fails to produce metadata.log file

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#405]
As a consequence, the indexing fails.

It's not clear what causes this. If the run is interrupted, there should be at least a partial metadata.log, but in the few cases that I looked at, the file was not there at all.

**Comment by portante** [comment]
Closing this for now, and we can watch for this in the future.  We can always reopen it.

It may have been moongen runs because the getting of the sysinfo was commented out.
