### ISSUE TITLE
pbench-fio graph latency unit does not match values

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#414]
in [this example pbench-fio latency graph URL](https://s3.amazonaws.com/ben.england/pbench-fio-latency-graph.pdf), the latency unit is listed as seconds "(s)" but the values are in the hundreds of thousands, so I guess it's in microseconds, which is the unit in which fio typically produces latency values.    I think we should stick with microseconds, since newer storage devices will have latencies which are measured in microseconds (maybe nanoseconds for NVDIMM).  So the label in the upper left corner should be "Latency (microsec)"

**Comment by bengland2** [comment]
also, in the above example I forgot to mention that the x axis units have a problem too.   The X-axis label is "Time (sec)" but the values are clearly in milliseconds.  I would prefer the X-axis values were converted to seconds, in order for people to have an easier time correlating X-axis values to events during the test.  Opinions?  At a minimum, make the x-axis label match the displayed X-axis value unit.

pbench-agent version: pbench-agent-0.40-4gdc14a7b.noarch 
pbench-fio version: pbench-fio-2.14-9.x86_64

**Comment by ndokos** [comment]
Closed by PR #427.
