### ISSUE TITLE
pbench-clear-tools doesn't accept -n arg

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#415]
Just a nit, the help says --name= is the same as -n but the latter fails. -g does work for the group arg though.

\# pbench-clear-tools -g default -n pidstat
pbench-clear-tools: you specified an invalid option
The following are required:
	-g str --group=str, str = the group from which tools should be removed
	                          (the default group is 'default')
	-n str --name=str, str = a specific tool to be removed.  If no tool is specified, all tools in the group are removed

\# pbench-clear-tools -g default --name=pidstat
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h01-6048r
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h05-6048r
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h09-6048r
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h13-6048r
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h17-6048r
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h21-6048r
running . /opt/pbench-agent/profile; pbench-clear-tools --group default --name=pidstat on c04-h25-6048r
 ...

**Comment by bengland2** [comment]
I've seen the same behavior with numerous pbench utilities, I have to use the "--name=val" syntax, not the "-n v" syntax.

**Comment by ndokos** [comment]
There's been talk to eliminate the short-form options altogether (and of course fix the help strings and other documentation). If there are no objections to that, we'll probably queue it up for v0.42. If there are, then please add your comments to issue #418.
