### ISSUE TITLE
jschart zoom is broken when a stacked chart that is zoomed has a dataset hidden

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#416]
For stacked charts that are zoomed:

![image](https://cloud.githubusercontent.com/assets/15911116/20155273/ba9ab760-a690-11e6-95f9-f2df9bdb7bc4.png)

When a dataset is hidden (CPU_000), zooming is broken:

![image](https://cloud.githubusercontent.com/assets/15911116/20155298/dc6cf6c8-a690-11e6-9667-1f61cb34f854.png)

Clicking "Reset Zoom/Pan" restores order:

![image](https://cloud.githubusercontent.com/assets/15911116/20155329/f7486b6c-a690-11e6-994a-3dac6b8767a2.png)

**Comment by ndokos** [comment]
Closed by PR #412.
