### ISSUE TITLE
pbench-fio calls fiologparser_hist.py more than once

### ISSUE THREAD

**Issue by wilkins11** [distributed-system-analysis/pbench#420]
I wondered why I always saw two different 'hist' dirs in the pbench-fio output but figured one was a softlink and never confirmed. When I watched to see what pbench-fio was doing taking so long post fio, I saw the first call to the histogram log parser, rather lengthy at 500+ guests, then it went on its way post-processing, and then repeated the histogram log processing with its results in a different hist dir.

   http://pastebin.test.redhat.com/429536

pbench-fio-2.14-9.x86_64
pbench-agent-internal-0.40-1.noarch
pbench-sysstat-11.2.0-1.x86_64
pbench-agent-0.40-4gdc14a7b.noarch

See the **hist** dir here and again in the **sample1** subdir ... http://pbench.perf.lab.eng.bos.redhat.com/results/tintin/scale/20161102-2200_pbfio-randwrite-1i-4Kbs-10m_base1/1-randwrite-4KiB/

**Comment by ndokos** [comment]
So it seems that fiologparser.py is called directly from pbench-fio, as well as indirectly through fio-postprocess. Not sure yet why, whether it is necessary and if not necessary, which call to keep.

**Comment by ndokos** [comment]
fio-postprocess seems to call fiologparser.py with the wrong path. That's probably what causes the "not found" errors that @bengland2 has complained about in the past. I have a trial version of the pbench-fio script (commenting out the fiologparser call) and fio-postprocess (with fixed up args to fiologparser) which seems to work: http://pbench.perf.lab.eng.bos.redhat.com/results/alphaville/fio__2016-11-16_04:34:58/1-rw-4KiB/sample1/hist/results.html

**Comment by bengland2** [comment]
Awesome, this can all be done by fio-postprocess, and it cuts postprocessing time in half for cases where there are a lot of threads over a long period of time.
