### ISSUE TITLE
pbench-fio latency histogram-based graphs are way off

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#421]
I looked at latency graphs generated by **pbench-fio** in the **hist/** subdirectory , for high host counts they are almost all way off, looking like [this](https://s3.amazonaws.com/ben.england/bad-hist-graph.png) .  When I look at the **fio_clat.*** files produced with the test, they look nothing like this, with far lower latencies for any percentile.  And it doesn't even display the 95th percentile even though the data is already output by the histogram log parser.  So I ran the fiologparser_hist.py program on the latency histogram data in the directory, and I get totally different results.

    root@smfnfs:/var/lib/pbench-agent/20161112-1224_pbfio-randwrite-512i-128Kbs-95m_libaio/1-randwrite-128KiB/sample1
    # fiologparser_hist.py --job-file=fio.job fio_clat_hist.1.log.vm*
    end-time, samples, min, avg, median, 90%, 95%, 99%, max
    60000, 790903, 6912, 156408.027, 42758.171, 462456.341, 657543.193, 1168779.368, 3276800
    120000, 1601620, 6912, 151827.200, 42454.845, 447034.793, 644767.972, 1143305.151, 3276800
    180000, 2433222, 6912, 152102.415, 39547.639, 458578.156, 656349.349, 1147911.295, 3276800
    240000, 3300115, 6912, 146717.501, 38798.047, 447622.083, 639906.561, 1101275.875, 3276800
    ...

I think the root cause is that the job file is not passed to fiologparser_hist.py.  fiologparser_hist.py was modified by Karl Cronburg to extract the logging interval from the log_hist_msec parameter in the job file.  For example, in the [pbench-fio postprocessing script line linked here](https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/postprocess/fio-postprocess#L17)  instead of:

     system("fiologparser_hist.py $dir/fio_clat_hist.*.log.* > $dir/hist/hist.csv

Use this:

     system("fiologparser_hist.py --job-file=$dir/fio.job $dir/fio_clat_hist.*.log.* > $dir/hist/hist.csv

**Comment by ndokos** [comment]
Closed by PR #424.
