### ISSUE TITLE
pbench-uperf: result.json is not created because post process errors with division by zero error

### ISSUE THREAD

**Issue by schituku** [distributed-system-analysis/pbench#440]
The uperf post process is not creating result files when there are errors in post process scripts. The data that is creating this scenario is here:
http://perf-infra.ec2.breakage.org/pbench/results/ip-172-31-11-85/uperf_svc-to-svc_PODS_8_UDP_NN_2016-12-08_21:35:18/6-udp_rr-16384B-2i/sample1/

The snippet of log output of pbench-uperf where the error is occuring is below:

client[172.26.236.101]protocol[udp]test[rr]instances[2]size[16384] <-> server[172.25.83.163]
client[172.25.99.47]protocol[udp]test[rr]instances[2]size[16384] <-> server[172.26.29.0]
**Illegal division by zero at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 473.
Can't open /var/lib/pbench-agent/uperf_svc-to-svc_PODS_2_UDP_2016-12-07_14:31:49/6-udp_rr-16384B-2i/sample1/result.json: No such file or directory at /opt/pbench-agent/bench
-scripts/postprocess/process-iteration-samples line 174.**
Iteration 6-udp_rr-16384B-2i complete (6 of 6), with 1 pass and 0 failures
generate-benchmark-summary: could not open file /var/lib/pbench-agent/uperf_svc-to-svc_PODS_2_UDP_2016-12-07_14:31:49/5-udp_rr-16384B-1i/result.json: No such file or directo
ry
Collecting system information

CC: @mffiedler @portante @ndokos

**Comment by atheurer** [comment]
I'll take a look

**Comment by schituku** [comment]
Thanks @atheurer 
Also in pbench-agent/bench-scripts/postprocess/process-iteration-samples
https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/postprocess/process-iteration-samples#L123
and
https://github.com/distributed-system-analysis/pbench/blob/master/agent/bench-scripts/postprocess/process-iteration-samples#L130
 are throwing errors when $val is "" as opposed to expected number

**Comment by atheurer** [comment]
pull request #441 has been issued to fix this

**Comment by atheurer** [comment]
The PR has been merged and wil be in the next release.  FWIW, this problem came up because there were no transactions to be found from uperf, so the test was not going to provide any result data anyway.  It;s unclear why uperf could not get any transactions, but it can be a number of factors, like losing network connectivity, or uperf server dying, firewall not opened up, etc.

**Comment by jeremyeder** [comment]
@schituku I think next release isn't until January some time, so you'll need to carry this patch locally.  It would also be helpful to understand why uperf failed.

**Comment by schituku** [comment]
yea I got the patch locally. also started to look why uperf is not able to
get transactions
