### ISSUE TITLE
pbench-rsync-satellite needs to check the error status of the initial ssh command

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#449]
See https://github.com/distributed-system-analysis/pbench/blob/master/server/pbench/bin/pbench-rsync-satellite#L71

We need to check the error status of the initial ssh command.

**Comment by ndokos** [comment]
Are you worried about the ssh? the cd? the ls? or all of them? If ssh returns a status, we can check it and bail. But if it returns 0, we are not guaranteed that everything is OK. I'm thinking of doing this:

     hosts=$(ssh $remotehost "if cd $remotearchive;then ls ;else exit 1 ;fi")

and checking the return code. WDYT?

**Comment by portante** [comment]
Closed by #474.
