### ISSUE TITLE
stacked jschart tables do not display combined average and median values

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#453]
![image](https://cloud.githubusercontent.com/assets/15911116/21360954/ab8d39a0-c6a7-11e6-8386-8888576790c7.png)

**Comment by portante** [comment]
Reviewed changes, closing based on bug fix in associated PR.

**Comment by portante** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Merge Archit's sar indexing and grafana work onto UI branch](https://trello.com/c/QhF2Qy2y/4-merge-archit-s-sar-indexing-and-grafana-work-onto-ui-branch)
