### ISSUE TITLE
pbench-uperf: result generation script failing when there is no data in one of samples 

### ISSUE THREAD

**Issue by schituku** [distributed-system-analysis/pbench#455]
pbench data location: http://perf-infra.ec2.breakage.org/pbench/results/ip-172-31-5-240/uperf_svc-to-svc_PODS_2_UDP_NN_2016-12-19_21:08:16/

pbench post process should generate a results html for the remaining tests where data got collected successfully as long as the remaining tests have all of their samples.​  It's suspected that the script which generates the html failed once it came across the missing data.  If the iteration would have been marked as failed, it would have skipped that iteration for the html.

**Comment by portante** [comment]
@atheurer, can you take a look at this?  I don't see any `results.html` files, and one of the tests does not have a `results.json` file.

**Comment by portante** [comment]
Closed by #471.
