### ISSUE TITLE
pbench-uperf: Iteration attempt not marked as failed when there is no data collected in samples

### ISSUE THREAD

**Issue by schituku** [distributed-system-analysis/pbench#456]
Command: 
pbench-uperf --test-types=stream,rr --runtime=30 --message-sizes=64,1024,16384 --protocols=udp --instances=2 --samples=3 --max-stddev=10 --clients=172.24.194.253,172.24.234.65 --servers=172.27.19.230,172.24.147.254 --config=svc-to-svc_PODS_2_UDP_NN

pbench data location: 
http://perf-infra.ec2.breakage.org/pbench/results/ip-172-31-5-240/uperf_svc-to-svc_PODS_2_UDP_NN_2016-12-19_21:08:16/

For 16KB UDP stream iteration there are two samples where data got collected and for one sample there is no data collected but still pbench-uperf did not mark this iteration attempt as failed and retry with 3 new samples.  Currently we only fail if stddevpct is too high and pbench-uperf should fail the iteration when there is no data collected also.

**Comment by atheurer** [comment]
PR #470

**Comment by portante** [comment]
Closed by #470.
