### ISSUE TITLE
See if we can get rid of the "date" field since we have "start_run" in the run metadata

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#506]
It seems that the handling of the `date` field in the run metadata and reconciling it with the `start_run` field via the `_to_utc()` method in `index-pbench` can be removed.  Investigate at what pbench version we'll loose support for with this change.

**Comment by ndokos** [comment]
We went to UTC dates and timestamps in v0.35. I'll get rid of the backward compat code.

**Comment by portante** [comment]
The `date` field is the date timestamp in the name of the tar ball, while the `start_run` and `end_run` fields are records of when the benchmark convenience script started and stopped.

The agent code uses UTC for all of its [date operations](https://github.com/distributed-system-analysis/pbench/blob/beb61d12f33a407472d8254789afe4fb828dddc6/agent/base#L73) now.
