### ISSUE TITLE
Find out where we verify that a given pbench result tarball only uses one root directory in its hierarchy

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#507]
There is a `FIXME` in `index-pbench` which is asking for verification of an assertion which appears to be made only in comments that every pbench result tarball has a single directory at the top of the hierarchy for all files/directories in the tarball.  See: https://github.com/portante/pbench/blob/1b7bb9f0a8d34a0c82e4a9feb4823e81fcf9c6aa/server/pbench/bin/index-pbench#L1224

**Comment by ndokos** [comment]
https://github.com/portante/pbench/blob/1b7bb9f0a8d34a0c82e4a9feb4823e81fcf9c6aa/server/pbench/bin/index-pbench#L796 asserts the equality.

**Comment by portante** [comment]
As of 036d65b9905346d01b3542ba4f53252ee0549316 (v0.57) of the pbench-server code base, the `PbenchTarBall` constructor takes care of verifying that a pbench result tar ball only uses one root directory in its hierarchy.  See https://github.com/distributed-system-analysis/pbench/blob/v0.64/server/lib/pbench/indexer.py#L2599.
