### ISSUE TITLE
Does the index-pbench process know ahead of time that a tar ball checksum has passed?

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#509]
When working with a pbench tar ball for indexing, does `index-pbench` know that a tar ball has passed its md5sum test?

See https://github.com/portante/pbench/blob/1b7bb9f0a8d34a0c82e4a9feb4823e81fcf9c6aa/server/pbench/bin/index-pbench#L1257

**Comment by ndokos** [comment]
When the tarball was unpacked, its MD5 sum was checked. The `pbench-index` script (which calls `index-pbench`) does not reverify that though.

**Comment by portante** [comment]
Answered back in March of 2017.
