### ISSUE TITLE
Add a way to quarantine pbench tarballs that don't match their MD5 sums

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#527]
It would be helpful to have the ability to for `pbench-verify-tar-balls`, and for that matter, the tarball ingest process itself, to detect and quarantine tarballs that they find which do not match their MD5 sums.

This is really about detecting bit-rot in the existing, previously processed, tar balls.

**Comment by ndokos** [comment]
@tenstormavi: the script currently operates like this:
 - it checks all the tarballs in the archive against their MD5 sums.
 - It checks all the tarballs in the backup location against their MD5 sums.
 - It reports any tarballs (either in the archive or in the backup location) that fail the check.
 - It compares the two lists: the list of all tarballs from the archive and the list from the backup location and it reports discrepancies: tarballs that are in the archive but not in the backup are OK (presumably they will be backed up the next time the backup script runs). Tarballs in backup but not in the archive should not happen.

What @portante is suggesting here is that we should do more than report:

- tarballs in backup that fail the MD5 check should be moved to a quarantive directory.
- tarballs in archive that fail the MD5 check (or are not there at all) should be restored from backup (assuming that the backup is good).

In both cases, the action should be reported.

**Comment by portante** [comment]
We are not going to address this via code we write, but will address it by leveraging an S3 object store which handles bit-rot detection and correction.
