### ISSUE TITLE
pbench-remote-sysinfo-dump produces uncompressed tarball

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#536]
It uses `tar cf - *` to produce the tarball on its stdout. pbench-collect-sysinfo then redirects the output to `<mumble>.tar.xz` and uses `tar xf` to extract. That works fine, except that the tarball is not compressed. If we really want to compress it, we should replace the invocation with `tar --xz -cf - *`. The xz package is required by the pbench-agent spec file, so it should be available.

**Comment by portante** [comment]
Just to update here in this issue as well, it does not seem worth the effort to compress the remote tar ball.  See PR #544 for the discussion.
