### ISSUE TITLE
pbench-rsync-remote script needs speeding up

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#537]
It currently takes roughly 20 mins in the EC2 environment to find out that there is nothing to do.

Proposal 1: modify the linkdest of pbench-unpack-tarballs in remote environments to move the link to a new TO-SYNC directory. Those directories can be scanned and a list of tarballs to sync can be compiled much more quickly.

Proposal 2: Garbage-collect empty `<hostname>` directories in the archive hierarchy. In some remote environments, these hostnames proliferate (that's the reason for the current slowness, but the preferred fix is still proposal 1 above).

**Comment by jeremyeder** [comment]
Hi @ndokos could you please see about addressing this?

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-rsync-remote script needs speeding up](https://trello.com/c/XJGEBjWt/15-pbench-rsync-remote-script-needs-speeding-up)

**Comment by ndokos** [comment]
Fixed by #587.
