### ISSUE TITLE
Include turbostat in our build

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#54]
Add turbostat in our build process, so we can control exactly which turbostat is used.  This will work in the same manner that we use sysstat utils (sar, mpstat, iostat, pidstat).

Also always include --debug in the invocation of turbostat

@jeremyeder please let me know if this works for you.  We'll try to get this in ASAP

**Comment by jeremyeder** [comment]
Should be fine, yep.  So you'll pull it in from the latest stable upstream kernel tree and build it?

**Comment by atheurer** [comment]
Yes, whatever latest/best version is

**Comment by jeremyeder** [comment]
OK, thanks.

**Comment by ashishkamra** [comment]
closing. Please re-open if problems with turbostat.
