### ISSUE TITLE
Pull pbench-metadata-log out of pbench-collect-sysinfo

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#546]
We finally were bitten by having the `pbench-metadata-log` call embedded in `pbench-collect-sysinfo`. :(

We recently made a change in #538 to make invoking `pbench-collect-sysinfo` optional, which now prevents the `pbench-metadata-log` call from being made.

We should update all the benchmarks to call `pbench-metadata-log` directly.

**Comment by tenstormavi** [comment]
@portante Sent PR #547

**Comment by portante** [comment]
Verified implemented with #547.
