### ISSUE TITLE
Include method to derive efficiency metrics for any pbench benchmark

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#55]
This issue tracks computing efficiency metrics, to be used on any of the pbench benchmark scripts.  Currently we have efficiency metrics for pbench_uperf only, and these are Gb-sec/CPU and transactions-sec/CPU.  We want to modularize the process, in order to create any "work/resource" metric for any of the benchmarks.

**Comment by ashishkamra** [comment]
@atheurer please re-open if this has not been addressed
