### ISSUE TITLE
pbench-rsync-satellite bug: rsync races with tarball copying

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#555]
If a tarball is being copied while rsync is trying to copy it off the satellite system to another server, the script can fail (although I don't completely understand how yet). That can lead to data loss. The fix is the same as in issue #537: the TO-SYNC directory will be populated with symlinks to the actual tarballs *after* the tarball and its md5 sum are completely copied. The rsync script will *never* look for the actual tarballs, only for links in the TO-SYNC directory.

**Comment by ndokos** [comment]
Actually, I don't think there is a race: I was misled by an error message in the error log that seemed to indicate that the tarball had failed the md5 check. But it turns out that that tarball was eventually transferred completely and the md5 sum checks out. The reason that the unpacking failed was because the directory in the incoming tree that was set up temporarily (with just an index.html indicating that the unpacking was taking place) could not be removed for currently unkown reasons. Once I removed the directory by hand, the unpacking proceeded with no other problems (except for the fact that it was a 5GB tarball, so it took a long time to unpack).

Nevertheless, the TO-SYNC solution will still be implemented for speed's sake but it will also make doubly sure that we don't have any races.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-rsync-remote script needs speeding up](https://trello.com/c/XJGEBjWt/15-pbench-rsync-remote-script-needs-speeding-up)

**Comment by ndokos** [comment]
Fixed by #587.
