### ISSUE TITLE
pbench-rsync-satellite bug: need to copy prefix-editing file as well

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#557]
In addition to the tarball and its md5 sum, any prefix-editing file for the tarball also needs to be copied and applied on the main server.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-rsync-remote script needs speeding up](https://trello.com/c/XJGEBjWt/15-pbench-rsync-remote-script-needs-speeding-up)

**Comment by ndokos** [comment]
Fixed by #587.
