### ISSUE TITLE
pbench-edit-prefix: add option for hostname different from the current hostname

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#558]
Currently, pbench-edit-prefix will assume that the hostname under which a given tarball is found is the same as the hostname of the machine where the script is executed. We should allow for a different hostname (and check it of course): that will allow reorganizing results that were created using some short-lived VM as a controller. On the minus side, it will also make it somewhat easier to reorganize somebody else's results (but that's already possible and not very difficult - if this  becomes a problem, we will need to rethink the whole approach of this script).

**Comment by portante** [comment]
We are planning on deprecated `pbench-edit-prefixes`, see #1355; closing.
