### ISSUE TITLE
Consider breaking move/copy-results into two commands: create tar ball, move/copy tar ball

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#568]
It would be great if folks who are using `pbench-agent` in an environment where they are unable to post to a `pbench-server`, could properly capture a pbench run like `move/copy-results` does today.

The new command would just replace the pbench directory trees resulting from a benchmark run with the resulting tar-ball and `.md5` file, something like:

```
$ pbench-make-tar-balls
```

Then `move/copy-results` would work on move/copy them to the `pbench-server`.

**Comment by jeremyeder** [comment]
Does this imply that uses always have to call this new command or would move/copy-results then call pbench-make-tar-balls itself?

**Comment by portante** [comment]
I would think `move/copy-results` would work as it does today, invoking the new command first to generate the tar balls.  We'd just be making the new command available and documenting when to use it for remote environments.

**Comment by jeremyeder** [comment]
Perfect :-)

**Comment by portante** [comment]
Fixed by #1289.
