### ISSUE TITLE
pbench-unpack-tarballs: rmdir: failed to remove ‘<$incoming>’: Directory not empty

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#570]
pbench-unpack-tarballs creates the $incoming dir (something like ..../incoming/<hostname>/<run-name>) early in its processing loop and adds an index.html file that indicates that the unpacking of that particular run is in progress. After the unpacking is done, the index.html file is removed, the $incoming $dir is removed (with `rmdir`) and the unpacked tarball is moved from temporary storage to $incoming.

Sometimes, the `rmdir` fails as indicated above. Checking after the fact shows that the only file in it is `index.html`. Checking the return code of the removal of `index.html` does not trigger any diagnostic output, so (unless the check is wrong) the file removal returned success. But the subsequent rmdir fails so the file cannot have been removed.

Maybe there is an obvious cause to this, but if so I don't see it.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-unpack-tarballs: rmdir: failed to remove ‘<$incoming>’: Directory not empty](https://trello.com/c/O8GBZvi6/18-pbench-unpack-tarballs-rmdir-failed-to-remove-incoming-directory-not-empty)

**Comment by ndokos** [comment]
The implementation of `pbench-unpack-tarballs` is going to be completely different in v0.45. We expect that this problem will disappear at that point.

**Comment by portante** [comment]
@ndokos, @tenstormavi, is this resolved with 0.45?

**Comment by ndokos** [comment]
`pbench-unpack-tarballs` has been completely gutted and reorganized (PR #578). If this problem rears its ugly head again, it will be more likely a problem of `pbench-move-unpacked`, but so far we have not seen anything like it.
