### ISSUE TITLE
Hide latency of copying unpacked tarballs

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#576]
Consider breaking up `pbench-unpack-tarballs` into two pieces:

- The first piece will unpack the tarball into local storage and set up a link from the web document root subdir to it.
- The second piece will copy unpacked tarballs in parallel to the distributed file system where the web document root is stored, and will delete the links created by the first half.

Assuming that the local storage is big enough to accommodate peak activity, that should allow almost immediate access to the data and hide the latency of the copying. The parallelism should also help with the occasional huge tarball that takes a long time to move.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hide latency of copying unpacked tarballs](https://trello.com/c/OSTiuwx6/19-hide-latency-of-copying-unpacked-tarballs)
