### ISSUE TITLE
pbench-fio: installation of python-pandas might fail on Fedora.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#579]
Fedora 24 (and maybe later) has python2-pandas and python3-pandas packages, but no python-pandas. pbench-fio OTOH tries to install the latter. We'll probably need to tailor the package name to the distro.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-fio: installation of python-pandas might fail on Fedora.](https://trello.com/c/b9xY5Q4n/20-pbench-fio-installation-of-python-pandas-might-fail-on-fedora)
