### ISSUE TITLE
pbench-register-tool --remote flag should not allow self-registration.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [distributed-system-analysis/pbench#584]
pbench-register-tool --remote flag, we are allowing current host(for ex, the node from which we are running pbench-register-tool) to be registered as remote. Is it done, intentionally, if not can we disallow that by adding a validation?

**Comment by atheurer** [comment]
When doing this, I did not think it registered it as remote, but just did a local registration.  Please look at https://github.com/distributed-system-analysis/pbench/blob/master/agent/util-scripts/pbench-register-tool#L118

**Comment by ravisantoshgudimetla** [comment]
Thanks @atheurer for the clarification. The problem I faced seems to be - As there are 2 different ways to register a node.

- With remote registration
- Without remote registration(without --remote flag and doing it locally)

It is causing the #469 where A=B. So should we allow remote registration along with local registration as this would cause confusion and in worst case a bug?

**Comment by portante** [comment]
The current tool registration already handles this, first released in v0.66 via PR #1317.
