### ISSUE TITLE
scp commands will fail when -p <port> is used as ssh_opts in the pbench-agent-config

### ISSUE THREAD

**Issue by chaitanyaenr** [distributed-system-analysis/pbench#591]
ssh uses -p flag to connect to a remote host while scp uses -P, this will lead to failure. For example, when the ssh_opts is set to use -p 2022 in the pbench-agent.cfg file, the scp command in the pbench-move-results script which copies the results on to the remote server fails since it uses -P flag for port not -p.

**Comment by ashishkamra** [comment]
@ndokos to discuss with @tenstormavi

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [scp commands will fail when -p <port> is used as ssh_opts in the pbench-agent-config](https://trello.com/c/9tyI2hSy/33-scp-commands-will-fail-when-p-port-is-used-as-sshopts-in-the-pbench-agent-config)
