### ISSUE TITLE
Parametrize API server port for prometheus metrics in pbench agent.

### ISSUE THREAD

**Issue by ravisantoshgudimetla** [distributed-system-analysis/pbench#596]
While working on pbench prometheus, we noticed that port for API server(metrics endpoint server) is always assumed to be 8443. Can we parametrize that?

/cc @chaitanyaenr

**Comment by chaitanyaenr** [comment]
Sure, that will help us in monitoring endpoints running on different ports. I can submit a PR, but you are welcome to do so if you are interested.
