### ISSUE TITLE
Uninitialized values in generate-benchmark-summary

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#604]
Need to make the script more robust by checking whether values have been initialized:

      ....
      fio job complete
      Use of uninitialized value $metric_section in split at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 290.
      Use of uninitialized value $metric_section in printf at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 294.
      Use of uninitialized value $text in split at /opt/pbench-agent/bench-scripts/postprocess/BenchPostprocess.pm line 76.
      Use of uninitialized value $metric_section in printf at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 340.
      Use of uninitialized value $metric_section in split at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 477.
      Use of uninitialized value $metric_section in printf at /opt/pbench-agent/bench-scripts/postprocess/generate-benchmark-summary line 481.

**Comment by portante** [comment]
This has aged out, and since we have not seen this issue recently, it can be reopened if it resurfaces.
