### ISSUE TITLE
Incorrect reporting by pbench-fio in version 0.40

### ISSUE THREAD

**Issue by shekharberry** [distributed-system-analysis/pbench#606]
I am using pbench-fio for my testing but in summay-result.txt there is a mismatch to what I am seeing when I just do a test using fio and a jobfile. The pbench-fio gives throughput in  rw_kB_sec (kilobytes)  which should either be in rw_B_sec (bytes) or the decimal in the result should be correctly placed. Please see the output below for better understanding

Pbench Version Used
--------------------------------

pbench-agent-internal-0.40-1.noarch
pbench-agent-0.42-1gcf7a941.noarch

Result from just fio run:

 write: IOPS=894, **BW=55.9MiB/s (58.6MB/s)**(1678MiB/30001msec)

Same Test done using Pbench-fio reports this:

1-write-64KiB             clients      readwrite-IOPS    **readwrite-kB/sec**           read-IOPS         read-kB/sec    read-95th-lat-ms          write-IOPS        **write-kB/sec**   write-95th-lat-ms
                              172.20.1.44              890.97        **58390629.65**                       0.00                0.00                      0.00                          890.97         **58390629.65**                3.18
  

As highlighted above there is bug in pbench-fio reporting.

**Comment by portante** [comment]
@shekharberry, I am not sure you should use Red Hat internal 0.40-1 with 0.42 of the agent.  I think you need the matching version.

We just released 0.43, which likely has a fix for this.  Can you try that new version?

**Comment by portante** [comment]
@shekharberry, we have just released 0.45, can you verify this works for you, and re-open this issue if it doesn't?  Thanks!
