### ISSUE TITLE
pbench-rsync-satellite: "<instance>: remove failure" reported in subject line of email, but "OK" reported in body of message

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#614]
As of the latest 0.43 release, `pbench-rsync-satellite` will report a "`<instance>: remove failure`" reported in subject line of email, but "`OK`" reported in body of message.

```
Date: Fri, 30 Jun 2017 22:24:00 +0000
To: admins@example.com
From: pbench@example.com
Subject: pbench-rsync-satellite: <instance>: remove failure

ip-172-31-38-59: pbench-user-benchmark_pbench_test_2017-06-30_2017.06.30T22.11.11.tar.xz: OK
```

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-rsync-satellite: "<instance>: remove failure" reported in subject line of email, but "OK" reported in body of message](https://trello.com/c/VgkxspJU/21-pbench-rsync-satellite-instance-remove-failure-reported-in-subject-line-of-email-but-ok-reported-in-body-of-message)
