### ISSUE TITLE
pbench-rsync-satellite appears to emit a huge payload to stdout when syncing

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#615]
pbench-rsync-satellite appears to emit a huge payload to stdout when syncing.  The payload appears to be the output from some list of tar balls to be synced.  We need to be sure that does not go to stdout so that it won't get caught by a cronjob and emailed to the admins.

**Comment by portante** [comment]
@ndokos, @tenstormavi, can one of you check if this is still a problem?

**Comment by ndokos** [comment]
pbench-rsync-satellite has been retired  (PR #663 and PR #634).
