### ISSUE TITLE
pbench ansible register playbook needs to be updated to support infra and cns nodes

### ISSUE THREAD

**Issue by jeremyeder** [distributed-system-analysis/pbench#619]
- infra nodes are labeled as such in the inventory with ```region=infra```.
- CNS nodes use a ```[glusterfs]``` ansible marker such as:

```
[glusterfs]
node1
node2
node3
```

**Comment by jeremyeder** [comment]
@chaitanyaenr @mffiedler @ekuric @sjug

**Comment by chaitanyaenr** [comment]
@jeremyeder on it.

**Comment by portante** [comment]
Fixed by #620.
