### ISSUE TITLE
Summary file not generated after pbench-fio run completes in ver 0.44

### ISSUE THREAD

**Issue by shekharberry** [distributed-system-analysis/pbench#631]
After pbench-fio test completes the summary.txt file is not generated and test does not summarizes the result as well.
Here's an output of pbench-fio run http://perf1.perf.lab.eng.bos.redhat.com/pub/shberry/pbench_fio_run. 
This was tested in both pbench 0.43 and 0.44 and issue persists.

Best Regards
Shekhar

**Comment by ndokos** [comment]
pbench-fio was modified to use the common output routine that pbench-uperf and pbench-moongen currently use. That produces  `result.{csv,html,json,txt}` files but apart from the name, they should contain exactly the same thing that the old `summary.*` files contained. That change happened in v0.43 (and I neglected to mention it in the release notes - sorry about that). There may be more than this (ISTR that you had a problem with v0.42?), but maybe not (I hope not :-) ).

**Comment by shekharberry** [comment]
Hi Nick,

Thanks for this information. It makes sense to have a common output across
benchmarks.

Sorry for all the trouble caused.

Best Regards
Shekhar

**Comment by ndokos** [comment]
@shekharberry: can I close this issue? Is there anything that needs to be done?
