### ISSUE TITLE
Tool names are too generic

### ISSUE THREAD

**Issue by lmr** [distributed-system-analysis/pbench#64]
The executable names on pbench are too generic, specially if you have an RPM install. I'd suggest the tools to have a `pbench-` prefix, such as `pbench-register-tool-set`. There's also the possibility to have a 'shell' command, that has subcommands, so the command would turn into `pbench register-tool-set`.

**Comment by jeremyeder** [comment]
:+1 we ran into this with the rpm names as well (ended up prefixing them with pbench).

**Comment by lmr** [comment]
It looks like having a shell app with subcommands seem the standard in the post-git world. It certainly looks better than having a bunch of lengthy commands.

**Comment by akrzos** [comment]
+1 neutron script conflicts with managing neutron directly after I install pbench on an OSP controller

**Comment by jtaleric** [comment]
+1000 This hit us in a deployment recently. If we simply ran neutron net-list or neutron anything it would return blank, leaving us to think neutron was busted, when in fact it wasn't.

**Comment by ndokos** [comment]
All executables in directories that are added to PATH have been renamed to have a "pbench-" prefix.
