### ISSUE TITLE
Modify pbench-dispatch to run as a service.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#665]
pbench-dispatch is running as a cron job, scheduled every minute. That adds a minute of latency to the processing, which is OK, but we can do better: it's a simple script that examines the TODO subdirs under each controller for tarball symlinks; when it finds one, it checks its MD5 and dispatches it for further processing (unpack, index, copy-sos-report etc. - depending on which server it is running on, it will dispatch to different states).

Instead of running it as a cron job, we can have it running as a service: constantly checking, using inotify, for new tarballs in all the TODO subdirs. It also has to check when a new such subdir is added (as a result of a new controller submitting a tarball) and create the appropriate inotify watch and add it to the watch list.  When it sees a new tarball, it will do exactly what it does now: check MD5 and dispatch it appropriately.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modify pbench-dispatch to run as a service.](https://trello.com/c/pHvCuO9H/25-modify-pbench-dispatch-to-run-as-a-service)
