### ISSUE TITLE
Modify pbench-move-unpacked to check for new jobs while it is running.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#666]
pbench-move-unpacked moves unpacked tarballs from a tmp directory on the local disk to long term storage in the distributed file system. Its purpose in life is to hide the latency that this move entails. The current implementation runs as a cron job, once a minute: each invocation will copy up to a dozen tarballs in parallel. When it has finished with all of them, it will exit.

We might have a problem if one of those jobs involves a long copy (we've had cases where it takes an hour - or eight - to copy a large tarball's contents). If the other eleven jobs are reasonable, their threads will finish quickly and wait for the long one to finish. Meanwhile, more tarballs may be accumulating. 

We might be able to make the process more efficient by making pbench-move-unpacked a service (issue #665 is similar): using inotify, check the UNPACKED subdirs of all controllers and add new tarballs to the job pool; also check for new controller dirs and add a watch to its UNPACKED subdir to the watch list. Finally, if the threads all finish, idle but do not exit.

This might serve as a template for some of the other scripts as well: I don't see a need to make copy-sos-reports, backup, quarantine or verify-backup a service, but unpack and index might be good candidates for that.

**Comment by ndokos** [comment]
OTOH, @portante points out that making all of them services will allow us to containerize them much more easily.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Modify pbench-move-unpacked to check for new jobs while it is running.](https://trello.com/c/wggINaiL/24-modify-pbench-move-unpacked-to-check-for-new-jobs-while-it-is-running)

**Comment by ndokos** [comment]
@tenstormavi is reimplementing it as a service, and move-unpacked is multi-threaded, so that should resolve the problem. We also have not run into this problem yet. Closing this.
