### ISSUE TITLE
pbench-unpack-tarballs and pbench-move-unpacked: mail_content.log is created in the wrong directory

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#671]
It should be in $tmp, not in $UNPACK_PATH, I think. The latter is shared, so the scripts are going to clobber each other's file.

**Comment by tenstormavi** [comment]
PR #673 is being sent for the issue.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-unpack-tarballs and pbench-move-unpacked: mail_content.log is created in the wrong directory](https://trello.com/c/18XNrglb/27-pbench-unpack-tarballs-and-pbench-move-unpacked-mailcontentlog-is-created-in-the-wrong-directory)
