### ISSUE TITLE
pbench-satellite-cleanup is creating empty logdir on every run.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#674]
Check /pbench-local/logs/pbench-satellite-cleanup/run-<TS>.

It also needs to write something to the log when it starts and ends, as well as the number of tarballs it cleaned up. Errors need to be mailed to the admins.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-satellite-cleanup is creating empty logdir on every run.](https://trello.com/c/qZkuvMT0/28-pbench-satellite-cleanup-is-creating-empty-logdir-on-every-run)

**Comment by tenstormavi** [comment]
PR #677 is being sent for this issue.
