### ISSUE TITLE
pbench pprof tool is no longer compatible with OpenShift 3.6+

### ISSUE THREAD

**Issue by sjug** [distributed-system-analysis/pbench#675]
The OpenShift pprof endpoints are now behind OCP RBAC, so the current curl metric gathering is not functional.

Additionally the tool will need to be registered only on a master node that has the oc tool configured in order to poll for pprof data. In the query we will have to specify which host we will be gathering data for.

**Comment by ndokos** [comment]
PR #676

**Comment by portante** [comment]
Fixed by #676.
