### ISSUE TITLE
pbench-move-unpacked: sorting by size is broken

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#691]
It sorts by size of the link (i.e. the length of the target name), rather than the size of the target.

We should also check for this bug in other scripts (pbench-unpack-tarballs perhaps) which might sort by size.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-move-unpacked: sorting by size is broken](https://trello.com/c/AzyWWMyD/30-pbench-move-unpacked-sorting-by-size-is-broken)
