### ISSUE TITLE
pbench server scripts: some `list' variables are misnamed.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#692]
Probably cut and paste errors, e.g. the `list` variable in pbench-dispatch is named "pbench-unpack-tarballs.$$". Similar problems occur elsewhere. They should probably be changed to "$PROG.$$", but we also need to make sure that they don't conflict with other names (e.g. when UNPACK_DIR and TMP refer to the same place in `pbench-move-unpacked`). We should probably come up with a cookie-cutter method that can be set in `pbench-base.sh` and DTRT for all the scripts.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench server scripts: some `list' variables are misnamed.](https://trello.com/c/JCETG49b/31-pbench-server-scripts-some-list-variables-are-misnamed)
