### ISSUE TITLE
pbench-unpack-tarballs: refactor code to reduce duplication

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#693]
`pbench-unpack-tarballs` duplicates code between the two cases: unpacking in the incoming directory directly or unpacking into a temp area first. But the code in both cases is pretty much the same, so we should refactor it: do the setup in the if/else and pull the rest of the code out.

**Comment by tenstormavi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [pbench-unpack-tarballs: refactor code to reduce duplication](https://trello.com/c/PzvUqF9W/32-pbench-unpack-tarballs-refactor-code-to-reduce-duplication)
