### ISSUE TITLE
configtools restricted to < 0.4

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#711]
To run Ceph in a linode.com cluster of VMs, I use [ceph-linode](https://github.com/batrick/ceph-linode/issues) scripting.  when I run ceph-linode to deploy the Ceph cluster, it does a **yum update -y** and this fails because pbench-agent is installed and it has a restriction on version of configtools, specifically it only allows version < 0.4.  Why??  Anything that can be done about this?  I can't change linode centos-7 image and couldn't easily justify changing ceph-linode in github.

[root@li1015-89 ~]# yum update configtools
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.linode.com
 * epel: mirror.math.princeton.edu
 * extras: mirrors.linode.com
 * updates: mirrors.linode.com
Resolving Dependencies
--> Running transaction check
---> Package configtools.noarch 0:0.3.1-2 will be updated
--> Processing Dependency: configtools < 0.4 for package: pbench-agent-0.46-1g6327ec7.noarch
---> Package configtools.noarch 0:0.4.0-1 will be an update
--> Finished Dependency Resolution
Error: Package: pbench-agent-0.46-1g6327ec7.noarch (@copr-pbench)
           Requires: configtools < 0.4
           Removing: configtools-0.3.1-2.noarch (@copr-pbench)
               configtools = 0.3.1-2
           Updated By: configtools-0.4.0-1.noarch (copr-pbench-test)
               configtools = 0.4.0-1
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

I'm running centos-7 standard linode image.

[root@li1015-89 ~]# more /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
[root@li1015-89 ~]# uname -a
Linux li1015-89.members.linode.com 4.9.50-x86_64-linode86 #1 SMP Thu Sep 14 19:28:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ndokos** [comment]
Why do you need to update configtools at all? The reason that < 0.4 is required for pbench-agent is that there is a (deliberate) backward incompatibility between 0.3 and 0.4 and until pbench has been patched to work with 0.4, we cannot allow configtools to be updated to 0.4. But who requires configtools and why do they need the 0.4 version?

**Comment by bengland2** [comment]
@ndokos I think the problem was that I enabled copr-pbench-test repo instead of just copr-pbench.

[root@li1244-126 ~]# yum whatprovides configtools
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.linode.com
 * epel: epel.mirror.constant.com
 * extras: mirrors.linode.com
 * updates: mirrors.linode.com
configtools-0.3.1-2.noarch : The configtools module
Repo        : copr-pbench



configtools-0.4.0-1.noarch : The configtools module
Repo        : copr-pbench-test



configtools-0.3.1-2.noarch : The configtools module
Repo        : @copr-pbench


e-mail from Nick: 

"0.3 expects the env variable CONFIG to point to the config
file, but given that "CONFIG" is a common name, 0.4 changes it to
something less obvious. The catch is that pbench needs to have all the
instances of "CONFIG" changed to the new name before we can allow it
to use the 0.4 version.

But who is trying to pull in configtools as a dependence? And why do
they want to update it? I thought only pbench uses it.

If necessary, I can delete 0.4 from COPR, so you don't see any version
greater than 0.3."

**Comment by bengland2** [comment]
solution: disable copr-pbench-testing repo in my repo file.
