### ISSUE TITLE
pbench-fio --targets= does not work with multiple targets

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#718]
When I try to run pbench-fio with multiple targets (for example, multiple block devices), fio rejects the job file, and the root cause is that quotes were injected into the pathnames.  However, a single target succeeds.  For example, here's a command that failed:

```
pbench-fio --targets=/dev/pmem0,/dev/pmem1,/dev/pmem2,/dev/pmem3 --test-types=write --runtime=10 --bs=256 --direct=1
```

In case you're curious, /dev/pmemX is NVDIMM X, we just got a server with NVDIMMs.  When I make this change, it works.    Would you like a PR or could you just put that in?

```
[root@perf146 bench-scripts]# diff -u pbench-fi{o.orig,o}                                                                                                                    
--- pbench-fio.orig     2017-11-14 16:11:16.159970654 -0500
+++ pbench-fio  2017-11-14 16:11:30.071372821 -0500
@@ -502,7 +502,7 @@
                -ramptime="$8" \
                -size="$9" \
                -rate_iops="${10}" \
-               -targets `echo "${11}" | sed -e 's/,/" "/g'` \
+               -targets `echo "${11}" | sed -e 's/,/ /g'` \
                | sed -e 's/ = /=/g' > $fio_job_file
 
        if [ $? -ne 0 ]; then
```

**Comment by ndokos** [comment]
@bengland: thanks! I'm working on `pbench-fio` so I'll fold this in.
