### ISSUE TITLE
Enhance pbench sysinfo collection with ansible facts

### ISSUE THREAD

**Issue by ashishkamra** [distributed-system-analysis/pbench#720]
As part of sysinfo data collection, we currently collect sosreport from the hosts on which the tools are registered. The enhancement that I am proposing will collect ansible facts (http://docs.ansible.com/ansible/latest/setup_module.html#examples) in addition to the sosreport data collection. The main advantage is that the data gathered using ansible facts is in json format, and hence in a better shape to be indexed into elastic search than the sosreport data. In addition, we can use the filters in the ansible facts module to come up with a very precise cluster definition json file format (Eg, no of nodes, total CPU, total memory, total storage, and network info) that can be attached with each pbench run. The cluster definition file can eventually help with the matching algorithm for Capacity Planning efforts.

**Comment by jtaleric** [comment]
We will still need to transform the data before indexing.

**Comment by ashishkamra** [comment]
I agree. But I guess it will be easier to transform ansible facts data for indexing than scraping the same information from sosreport.

**Comment by atheurer** [comment]
On Wed, Nov 15, 2017 at 6:10 PM Ashish Kamra <notifications@github.com>
wrote:

> I agree. But I guess it will be easier to transform ansible facts data for
> indexing than scraping the same information from sosreport.
>

Probably, although I thought someone already did the scraping. As long as
the ansible addition is modular (you can turn it on/off like the others)
then I see no harm in it.  However, using this assumes you have ansible and
many of us do not.

**Comment by jtaleric** [comment]
@atheurer right, the minimum assumption would be Ansible for this gathering mechanism. 

This functionality should be a bit that is defaulted to disabled, and enabled by the user.

**Comment by jtaleric** [comment]
@ashishkamra Yes. It will be easier, however, we need to agree on the flattened structure.

**Comment by ashishkamra** [comment]
@jtaleric @atheurer 
I was looking at the existing sysinfo collection code in pbench. By default, here is the list of collection options - "block libvirt kernel_config sos topology ara"
"ara" is Ansible run analysis and below is the code snippet from 'pbench_sysinfo_dump' to run a playbook to collect the required ara data. 
`
function collect_ara_data {
        # collect data only when ara is installed
        if python -c "import ara" &>/dev/null; then
                mkdir $dir/ara
                generate_inventory > $INVENTORY
                ansible-playbook -i ${INVENTORY} --extra-vars '{"SYSINFO_DIR":"'$dir'"}' "$pbench_install_dir/ansible/ara/ara.yml"
        else
                debug_log "[$script_name]skipping, $item not installed"
        fi
}
`
In similar fashion, we can run another playbook by default that will gather the ansible facts that we care about. Something like below as copied from https://stackoverflow.com/questions/34485286/ansible-gathering-facts-with-filter-inside-a-playbook
`
- hosts: all
  sudo: yes
  gather_facts: False
  tasks:
   - setup:
       filter: ansible_*
`

**Comment by portante** [comment]
Replaced by #915.
