### ISSUE TITLE
pbench-sysinfo-dump: stdout is *reserved*.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#728]
`pbench-sysinfo-dump` produces a tar ball on its stdout: *nothing else* can appear in it. In particular, `echo "message"` is a no-no: it has to be redirected to a log file. See PR #727.

But even without such explicit `echo` calls, there is a problem with `debug_log`: this function generally redirects its output to the pbench log file, *unless* PBENCH_debug_mode is set to a non-zero value, in which case it dumps it to stdout.

For `pbench-sysinfo-dump`, we either have to get rid of `debug_log` calls all together, or we have to modify it somehow, so in this particular case we can override its standard behavior.

**Comment by portante** [comment]
Already fixed via sysinfo-dump handling in the Tool Meister [code](https://github.com/distributed-system-analysis/pbench/blob/v0.71.0/lib/pbench/agent/tool_meister.py#L1731) provided via the v0.71 release.
