### ISSUE TITLE
pbench-fio is not happy with pandas package

### ISSUE THREAD

**Issue by hongkailiu** [distributed-system-analysis/pbench#736]
```sh
# pbench-fio --test-types=read --clients=172.23.0.4 --config=SEQ_IO --samples=1 --max-stddev=20 --block-sizes=4 --job-file=config/sequential_io.job
verifying clients have fio installed
[error][2017-12-18T19:48:18.701800264] Unable to find default tools group directory, /var/lib/pbench-agent/tools-default
Could not install pandas package

# echo $?
1

# python
Python 2.7.5 (default, Dec  8 2017, 16:39:59) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-25)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas


root@ip-172-31-2-249: ~/svt/storage # yum list installed | grep pbench
configtools.noarch              0.3.1-3           @copr-pbench                  
pbench-agent.noarch             0.47-109g2cfe130  @ndokos-pbench-interim        
pbench-fio.x86_64               2.14-2            @copr-pbench                  
pbench-sysstat.x86_64           11.2.0-1          @copr-pbench  
```

It seems a workaround when i commented out "return 1" in <code>pandas_install</code> function.

**Comment by hongkailiu** [comment]
@ndokos told us the magic:
vi /opt/pbench-agent/config/pbench-agent.cfg

### Uncomment this line
pandas-package = python-pandas

**Comment by ndokos** [comment]
The correct line is added to the pbench-agent.cfg file when installing using an "internal" RPM: these RPMs are tailored for specific environments, but they also detect on what distro the RPM is being installed and can DTRT wrt such annoyances (python-pandas in RHEL vs python2-pandas in Fedora). But that has to be done manually in general.

**Comment by hongkailiu** [comment]
Understood.
Thanks.

**Comment by bengland2** [comment]
one other thing - python-pandas comes from EPEL so you have to have that as well.  Would be nice if this was documented.

**Comment by ndokos** [comment]
Ben England <notifications@github.com> writes:

> one other thing - python-pandas comes from EPEL so you have to have that as well. Would be nice if this was documented.
>

It was mentioned in the release notes for v0.40 (which is when the dependency was introduced), but
it does deserve mention in a more prominent place:

   http://pbench.perf.lab.eng.bos.redhat.com/release-notes/RELEASE-NOTES.html#sec-8-1

-- 
Nick
