### ISSUE TITLE
All benchmark packages need "pbench_" in the beginning of their name

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#75]
Too often we may use the wrong package, provided by another repo, because we do not have pbench specific naming for our benchmark packages.  We need to make sure all benchmark packages have "pbench_" prepended in their names.

**Comment by atheurer** [comment]
We should try to get this naming fixed before we deploy these package to copr

**Comment by ndokos** [comment]
Done (although the prefix is "pbench-").
