### ISSUE TITLE
seeing double on pbench results website

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#756]
when I do pbench-move-results --prefix=foo , it writes the data 2x to pbench.  Once in the prefix dir and once at the top-level dir.  This is annoying because it makes it harder to find the data I'm looking for.  The whole reason that I use a --prefix option is to avoid having to search through gobs of pbench directories.

**Comment by bengland2** [comment]
For example,  see 2 duplicates [here](http://pbench.perf.lab.eng.bos.redhat.com/results/b06-h01-1029u/2018-01-21-10mobj-4k-filestore/pbench-user-benchmark__2018.01.22T05.51.33/)  and [here](http://pbench.perf.lab.eng.bos.redhat.com/results/b06-h01-1029u/pbench-user-benchmark__2018.01.22T05.51.33/), there are many more.

Can we write a script to clean this up so if a pbench directory is in a --prefix subdirectory, we remove it from the top-level directory?

**Comment by ndokos** [comment]
This seems to be a bug in one of the server scripts (probably pbench-move-unpacked): it does not seem to get the prefix correctly. I'll fix the bug and clean up the mess. Thanks for the bug report and sorry for the inconvenience!

**Comment by ndokos** [comment]
I have tested and deployed a fix in the production environment. That should avoid the problem in the future. Please let me know if you think there is still a problem. If that looks OK, I'll submit a PR. I'll deal with the existing mess next (but not tonight).

**Comment by ndokos** [comment]
@bengland2: I actually submitted the PR before giving you a chance to test. But we won't merge it until we get the OK from you.
