### ISSUE TITLE
pbench-fio v3.3 histo. graph units wrong

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#777]
Hongkai Liu reports that with pbench-fio v3.3, the histograph graph has a label of "usec" but the data is actually in nanoseconds, very confusing.    When we switch to pbench-fio v3, we need to either transform the latency data to be in microseconds before we graph it, or we need to change the graph label.  Example attached...

**Comment by bengland2** [comment]
Hongkai supplied these links

With [pbench 0.46-78g30019c5](http://perf-infra.ec2.breakage.org/pbench/results/ip-172-31-63-239/fio_SEQ_IO_2017.11.30T18.48.20/2-read-16KiB/sample1/clients/172.20.0.8/hist/results.html)

With [pbench 0.48-166g87190ca](http://perf-infra.ec2.breakage.org/pbench/results/ip-172-31-17-61/fio_SEQ_IO_2018.02.09T20.47.31/2-read-16KiB/sample1/clients/172.22.0.13/hist/results.html)

**Comment by portante** [comment]
Closing since we support `fio` 3.21 and later now.
