### ISSUE TITLE
pbench needs GPU profiling tools

### ISSUE THREAD

**Issue by frival** [distributed-system-analysis/pbench#778]
With GPUs being integrated into many workloads we'll need to be able to profile them inside pbench.  Right now nvidia is the only game in town that works on RHEL so it would make sense to start with their tools; when AMD's driver and tools are working we'll have to revisit this so the right tool is run depending on which GPUs are installed.

For basic profiling we'll want to use `nvprof` remote profiling, capturing it with a command like `/usr/local/cuda/bin/nvprof --export-profile <data filename>`.  We can provide a basic GPU usage profile via `/usr/local/cuda/bin/nvprof -i <data filename> --log-file <profile filename>`.  I'd suggest copying both the profile output and the data file to the pbench server as the data file can then be copied to a remote system (e.g. desktop with CUDA installed) and imported to their `nsight` GUI tool for more in-depth analysis.

**Comment by jeremyeder** [comment]
question:  does NV provide any daemon that exports this stuff over REST?

**Comment by frival** [comment]
If only...  Their "normal" workflow expects that you're doing everything inside an IDE and developing / profiling interactively.  There are other profiling tools available, perhaps some that would fit the distributed model better, but I haven't been able to muck with them yet; nvidia provides a list at: https://developer.nvidia.com/performance-analysis-tools.  I don't know if that list is exhaustive.

I had intended to start simple and small and then add larger and more complex tools as we get comfortable with them, but if nvprof is insufficient I'll accelerate looking at the larger options.  Several of them are produced by HPC labs so I expect they play well in distributed environments.

**Comment by portante** [comment]
The `dcgm` "tool" is provided with the [v0.71](https://github.com/distributed-system-analysis/pbench/releases/tag/v0.71.0) release.
