### ISSUE TITLE
Accessing results tarballs over http

### ISSUE THREAD

**Issue by chaitanyaenr** [distributed-system-analysis/pbench#781]
It would be great if we can access the pbench results tarballs after moving them to the server over http so as to avoid downloading huge files in case we want them on our machine.

**Comment by ndokos** [comment]
Can you elaborate on what happens afterwards? I get the tarball, I unpack it - do I make changes? add files? And then do I submit it to the server as a new result? as a replacement for the original? Either of these has implications that we need to think about.

**Comment by portante** [comment]
@chaitanyaenr, not sure I follow the use case.  Is it:

1. `pbench-move-results`
2. `curl -X GET -o myresult.tar.xz https://pbench.server.io/results/...tar.xz`
3. `tar xf myresult.tar.xz`
4. Review contents locally?

**Comment by chaitanyaenr** [comment]
@ndokos @portante we will just use the contents locally. They will not be moved to the server again and cause duplication, As for the use case, @sjug has a tool called pbench-log-parser which compares two results, if we want to use the tool locally to compare existing scale test results then it's going to take a lot of time to download them from the server as the files are huge. So, it would be easy if we have access to the tar balls.

**Comment by portante** [comment]
@chaitanyaenr, can you get Sebastian to submit a PR for that tool as a contribution (`contrib` subdir) so we can review it?

This is how we collaborate, by exposing work that individuals have down so that others can share it and improve it.

**Comment by chaitanyaenr** [comment]
@portante sure.
