### ISSUE TITLE
Jenkins plugin for pbench data collection

### ISSUE THREAD

**Issue by nkhare** [distributed-system-analysis/pbench#8]
Jenkins have plugins to add functionality on top on Jenkin 
https://wiki.jenkins-ci.org/display/JENKINS/Plugins

It would be good to have plugin of  pbench for jenkins to save the performanace data.

**Comment by portante** [comment]
We want to keep knowledge of Jenkins separate from pbench, so that we don't have to have special logic for Jenkins.
