### ISSUE TITLE
pbench packages for non-x86 architectures needed

### ISSUE THREAD

**Issue by frival** [distributed-system-analysis/pbench#803]
With aarch64 and PPC64le being supported architectures (and s390 but nobody has asked for that yet) we need to find a way to have pbench builds for those architectures as well.  If copr doesn't have builders set up yet for the other arches it would be great (read: I need them already) to at least make RPMs available for each build until they get to that point.

**Comment by ndokos** [comment]
COPR does not support aarch64 builds currently.

We came up with a manual process for now:
- The pbench-agent RPMs are really "noarch", so we can pretend that aarch64 is x86_64 for pbench-agent purposes. That allows us to install pbench-agent.
- The benchmark RPMs (and also the sysstat tool RPM) are built locally on the aarch64 system and are installed locally.
- The pbench-fio RPM requires  python-pandas which is in EPEL, so we install the epel repo.
- There are a couple of bugs in pbench (see issue #804) that need fixing.

With those in place, I was able to run a simple pbench-fio to completion.

These are obviously stop-gap measures. We are working on a longer-term solution.
