### ISSUE TITLE
pprof script in /opt/pbench-agent/tool-scripts needs to be updated for OCP 3.10

### ISSUE THREAD

**Issue by wabouhamad** [distributed-system-analysis/pbench#814]
In OCP 3.10, atomic-openshift-master-api and master-controllers are deployed as static pod, instead of systemd services.  This script that restarts the services need to update the /etc/origin/master/master.env file to append the OPENSHIFT_PROFILE=web line, and use the provided restart shim /usr/local/lib/master-restart.

The atomic-openshift-node service remains a systemd service on the compute and infra nodes.

Currently there is a BZ https://bugzilla.redhat.com/show_bug.cgi?id=1572919 opened for profiling endpoint not starting on compute nodes in OCP 3.10.

**Comment by ekuric** [comment]
@wabouhamad I will check this issue @chaitanyaenr @jeremyeder

**Comment by mrsiano** [comment]
@wabouhamad walid, can you confirm we can close this one, since based on the BZ looks like we already listening to port <node_ip_or_hostanme>:10250
which is the correct one.

**Comment by wabouhamad** [comment]
@mrsiano yes we can close this issue. Thx
