### ISSUE TITLE
Error when comparing user benchmark results for perf148b.perf.lab.eng.bos.redhat.com controller

### ISSUE THREAD

**Issue by ashishkamra** [distributed-system-analysis/pbench#839]
I tried to compare user benchmark results for the controller - perf148b.perf.lab.eng.bos.redhat.com. I ended up with the following stack trace on the browser:

Unhandled promise rejection Error: Request failed with status code 404
Stack trace:
e.exports@http://pbench.perf.lab.eng.bos.redhat.com/dashboard/dist/main.d0c86ce94c4f38abebaf.js:20:8959
e.exports@http://pbench.perf.lab.eng.bos.redhat.com/dashboard/dist/main.d0c86ce94c4f38abebaf.js:38:6305
e.exports/</p[h]@http://pbench.perf.lab.eng.bos.redhat.com/dashboard/dist/main.d0c86ce94c4f38abebaf.js:20:7705

**Comment by gurbirkalsi** [comment]
@ashishkamra Unfortunately, we don't have a supported method for comparing user benchmark results within the platform right now. I've added an exception page that shows an error and the current supported tool data collections. This can be referenced in the following commit: https://github.com/distributed-system-analysis/pbench/pull/827/commits/9291005d60bb9e236329b20945543672babae63b

<img width="1680" alt="pbench_dashboard" src="https://user-images.githubusercontent.com/4149652/41265523-b421b962-6dc0-11e8-8503-45d1138751e2.png">

**Comment by gurbirkalsi** [comment]
Closing as this has been deployed in production.
