### ISSUE TITLE
'share' option on the comparison page does not render both Gb/Sec and Trans/Sec graphs

### ISSUE THREAD

**Issue by ashishkamra** [distributed-system-analysis/pbench#840]
'share' option on the comparison page does not render both Gb/sec and Trans/Sec graphs. It only renders graph for Gb/sec.

**Comment by gurbirkalsi** [comment]
I'm currently investigating integrating this library to handle converting the react components to printable DOM elements: https://github.com/diegomura/react-pdf

Although not ideal, a temporary solution for this is zooming out within the print view or changing the page sizing options. React components are very tricky to get into printable form; however, the library I mentioned above should be able to handle printing and even dynamic form generation for custom sharing.

**Comment by gurbirkalsi** [comment]
This issue is being tracked via PR #1041 and will be targeted for milestone v0.57

**Comment by portante** [comment]
See #1041.
