### ISSUE TITLE
Left pane covers up comparison graphs

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#842]
When comparing multiple pbench jobs, there is a left pane in the brower that has "controllers" button.  That left pane blocks part of the middle pane, blocking things like the Y axis label.  If you click the "hamburger" thingy at the top left, it will shrink, which is good, but ideally we need the middle pane to not be blocked by default.

**Comment by gurbirkalsi** [comment]
@atheurer Resolved with the following commit: https://github.com/gurbirkalsi/pbench/commit/bd468af1013abd3f17b10cb1a5d2b5834d6ca45f

**Comment by gurbirkalsi** [comment]
I removed the toggling ability for now since we do not have a comprehensive navigation for the platform. Clicking either the controllers icon or the 'PBench Dashboard' title will navigate the user back to the controllers page.

**Comment by gurbirkalsi** [comment]
This issue has been resolved with the recent release of PDash v2.
