### ISSUE TITLE
uperf RR summary graph plotting latency values instead of transactions/sec

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#843]
The summary graph (clustered bar graph comparing iterations which similar benchmark parameters) for uperf, when reporting RR tests, does not plot the actual promary metric, transactions_sec.  Instead, the values come from latency.  An example is this: http://pbench.perf.lab.eng.bos.redhat.com/results/vm1/uperf_rhel75_ga_40gb_virtio_2018.06.08T08.14.52/result.json

However, when going to the "ALL" tab, the timeseries plot is correct.

**Comment by Anisha1234** [comment]
Fixed with #1318
