### ISSUE TITLE
[Feature Request] comparison tool URL generator

### ISSUE THREAD

**Issue by atheurer** [distributed-system-analysis/pbench#844]
When we come up with a comparison of pbench results, it would be nice to share the comparison, but not in static form (pdf).  It would be very useful to share a link, that when loaded, would re-generate the comparison.  Right now, when generating a comparison, the URL in the browser is not unique, so we simply cannot copy that link today.  What we would like is a button to generate a "sharable link", with enough information embedded in the link to regenerate the same comparison by anyone who received the link.

**Comment by gurbirkalsi** [comment]
@atheurer Peter and I have discussed using Elasticsearch as a potential solution for this feature. Essentially, we would maintain a  document in ES that would contain a "global" map containing a hashed key and the value representing the configuration a user has selected to share. Let me know your thoughts!

**Comment by portante** [comment]
Fixed by #1435.
