### ISSUE TITLE
Ansible playbooks for installing the pbench repos.

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#864]
We have ansible playbooks for installing the needed pbench repos but they are not in the git repo. We need to make those available, probably in the agent/contrib area.

The current playbooks don't handle the needed dependencies. Enhance them to cover that  as well.

**Comment by portante** [comment]
@ndokos, what is the status of this work?  Didn't we already land the agent playbooks?  If so, can you link the PR here?

**Comment by ndokos** [comment]
Fixed by #1105
