### ISSUE TITLE
Make sure that python scripts are 2-or-3 compatible

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#865]
Apart from the (server-side) index-pbench script which is python3 only, all of the other python scripts in pbench are simple enough to be both 2- and 3-compatible. Make sure that they are.

Then make sure that the shebang lines in all of them invoke /usr/bin/python. That should allow the scripts to continue working no matter what the underlying platform provides.

**Comment by bengland2** [comment]
Is it /"#!usr/bin/python" or "#!/usr/bin/env python"?  [See this article](https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt) for details

**Comment by riya-17** [comment]
Hey @ndokos 

I am unable to understand this issue can you please elaborate?

**Comment by bengland2** [comment]
@riya-17 I've written lots of code that works with both python v2 and v3, in many cases it's not that much effort, let us know if you have a specific problem you are working on.   [Here's an article](https://docs.python.org/3/howto/pyporting.html)  that talks about it.

**Comment by ldoktor** [comment]
Just FYI there is a nice porting guide here: https://portingguide.readthedocs.io/en/latest/ we used previously to port different project and was very useful.

**Comment by ndokos** [comment]
There are a couple of developments that probably make this issue obsolete. First, all the server scripts that are written in python (pbench-index, pbench-backup-tarballs, pbench-verify-backup-tarballs) are python3. Second. @portante in a recent PR (PR #1254 ) made it so that the pbench-agent python scripts are also run under python3 (SCL required in the case of RHEL7) and made the changes necessary for python3 compatibility. We should probably close this issue. 

[ BTW, it is not true that making the shebang line `/usr/bin/python`  or `/usr/bin/env python` will work. But the issue was opened a long time ago when the world was a bit simpler :-) ]

**Comment by portante** [comment]
Closing at Nick's suggestion.
