### ISSUE TITLE
pprof tool script eats a core

### ISSUE THREAD

**Issue by sjug** [distributed-system-analysis/pbench#871]
The tool-scripts/pprof will consume 1 core for length of test run. This seems to be due to the new while & wait pattern?

strace:
```
...
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, [CHLD], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
...
```

**Comment by portante** [comment]
How short is the interval in use?

If the spawned processes complete before the specified interval, e.g. when there is a bug in the command that is used which results in no wait, then the wait loop will consume CPU spinning.

Adding a sleep to a [target time interval](https://stackoverflow.com/questions/645992/bash-sleep-until-a-specific-time-date) [1] would prevent that from happening.

[1] https://stackoverflow.com/questions/645992/bash-sleep-until-a-specific-time-date

**Comment by sjug** [comment]
Fixed by https://github.com/distributed-system-analysis/pbench/pull/919
