### ISSUE TITLE
Prometheus tool appears to emit duplicate JSON documents in the generated .json file from post-processing

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#881]
It appears that the generated prometheus JSON documents created by the prometheus post-processing tool is responsible for creating the duplicates.  The original prometheus metrics captured do not appear to be duplicates, but inspection of the generated .json file seems to show duplicates.

**Comment by portante** [comment]
FWIW, the server unit test, `test-7.12`, contains an example of prometheus data with duplicates.

**Comment by portante** [comment]
@chaitanyaenr, any updates?

**Comment by chaitanyaenr** [comment]
@portante didn't get a chance to work on it, will take a look and update the issue.

**Comment by portante** [comment]
@chaitanyaenr, this issue does not seem to be a priority.  Unless we can make progress on this work, we'll have to close this.

Any updates?

**Comment by portante** [comment]
With #1073, the duplicates have been removed from unit tests.

It is still possible to get duplicates in production, but that'll be harder to diagnose.  Closing for now, we re-open if we find this issue again in production.
