### ISSUE TITLE
Enhance dashboard with user id data

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#888]
v0.51 pbench-move-results has acquired a --user option that allows a user to tag results with a user id. That is indexed as part of the metadata.log file so it is available to the dashboard. That would give users another (probably more convenient) way to get at their results through the dashboard, using a user view, similar to the controller view.

**Comment by gurbirkalsi** [comment]
@ndokos This functionality has been made available with the inclusion of the search view which is currently deployed in production. Did you have something else in mind for UI/UX in terms of exposing this data in the front end?

**Comment by gurbirkalsi** [comment]
Resolved via PR #951
