### ISSUE TITLE
perl json processing can be very slow

### ISSUE THREAD

**Issue by k-rister** [distributed-system-analysis/pbench#895]
See https://perlmaven.com/comparing-the-speed-of-json-decoders for examples.

Running the pbench-trafficgen postprocessing with just JSON:PP installed took 7:26.56 in one scenario.  Just installing JSON:XS and making no code changes reduced that to 0:17.67.

**Comment by ndokos** [comment]
I rebuilt the pbench-agent RPM (current version is 0.52-2gd1023f4a on COPR) with a modified spec file that requires perl-JSON-XS. Can you try installing it and checking it out? Let me know if you find any problems.

**Comment by k-rister** [comment]
Is this something that we can test through the unit test structure?  That would seem to be much greater coverage than what I could possibly provide from running a handful of tests that I am setup for (pbench-fio and pbench-trafficgen).

**Comment by k-rister** [comment]
Can this be closed after the recent release?

**Comment by ndokos** [comment]
Not yet - @jtaleric had some objections, so I'm going to rework it a bit.

**Comment by k-rister** [comment]
Are those issues articulated somewhere?  I'm just curious, it seemed like a drop in replacement when I tested it.

**Comment by ndokos** [comment]
There is no problem if you have the EPEL repo installed everywhere. But since the post-processing is done on the controller, it's the only machine that needs perl-JSON-XS installed. Even there, we can then fall back to the perl module if EPEL is not installed (with a warning that things will be slow). The way things are now, the installation will fail.

**Comment by k-rister** [comment]
Is this not a problem in general?  How are we avoiding this elsewhere?

**Comment by ndokos** [comment]
Not sure what you mean: what is not a problem? and how are we avoiding what?

**Comment by k-rister** [comment]
What I meant was I thought we have numerous dependencies on epel in pbench, do we not?  If we do, how is the problem sighted here being avoided in those other situations?

**Comment by atheurer** [comment]
We have the same problem with fio (only for histogram post-processing).  However, my plan is to check for the package, and if not found, just not do the histogram processing.  I would really prefer we don't make EPEL a requirement, as it always seems like an extra step to get working in RHEL.  If we really do need EPEL, then it needs to be a package dependency on pbench-agent.

**Comment by ndokos** [comment]
The fio dependency on pandas will be going away as soon as we pick up the latest version of fio. @bengland2 has rewritten the script to avoid pandas (he also managed to speed it up by some large factor).

What I was considering doing was to check  *on the controller only* whether the RPM is available for installation: if available, install it and go on; if not, issue a warning and go on. For fio, I added a --remote switch to differentiate the controller from the other nodes, but I'd rather have a generic way to do that differentiation: is there such a way today? If not, maybe we should add one.

**Comment by atheurer** [comment]
@ndokos I have been looking at that new script for processing histogram logs for fio, and it drops pandas but requires unittest2, which also only comes from EPEL.

**Comment by bengland2** [comment]
I'll try to get to this quickly, I didn't realize unittest2 was causing
install problems.

**Comment by atheurer** [comment]
@ndokos FWIW, @bengland2 is removing the unittest2 dependency for the new python histogram processing script, so it looks like we will not have to conditionally run the script based on packages being present.  There is one other issue I am encountering with the script, but once that is overcome, I will have a PR that incorporates it and a lot of other fixes for FIO.  I do, however, need your assistance in getting FIO version 3.7 packaged.  Sorry fo going so far off topic....

**Comment by ndokos** [comment]
np - I'll get to that today.

**Comment by portante** [comment]
See https://perlmaven.com/json, can we use `JSON::MaybeXS` so that we don't depend on JSON::XS directly, but take advantage of it if it is installed?  This would allow us to NOT add a dependency on EPEL RPMs, but let somebody install the JSON::XS RPM from EPEL if they are having a problem.

**Comment by k-rister** [comment]
Since this issue has been raised in other threads and referenced back to this original issue can someone (@ndokos , @portante ?) post an updated status on where this currently stands?

**Comment by portante** [comment]
The current suggestion on the floor for this is to change the code to depend on the JSON::XS module explicitly, and let the packaging environment solve the problem of resolving the dependency properly.

In our case, we'll be building the Perl JSON:XS module RPM along side the pbench RPM to keep them in lock step.

@ndokos, @atheurer, @k-rister, is there a reason why we can't use `JSON::MaybeXS` instead?  Avoiding the explicit dependency?

**Comment by atheurer** [comment]
I would prefer solution in which we do not have a user wondering why something is taking several hours, then they file a github issue, then we tell them to install JSON::XS, then they need to install EPEL.  If that can be resolved by just packaging JSON::XS within pbench-agent, like we have done with SigFigs, then that would be my preference.  But I would like to hear @ndokos view on what works best for him, because I don't know if bundling the module is a burden or not.

**Comment by portante** [comment]
Taking on additional packaging tasks is already a drag.  We had a ton of work to do with sysstat, and will in the future.

Using Ansible playbooks to properly install `pbench-agent` can be another way we have folks ensure they have the `JSON::XS` installed.  That removes the burden of building and packaging and still gives the users control and allows us to describe in a documented way what is needed for `pbench-agent` to run properly.

**Comment by atheurer** [comment]
If we can have the playbook install epel and JSON::XS, then that seems fine to me.

**Comment by k-rister** [comment]
Having the playbook install the package seems fine to me.

I'm not sure I understand what JSON:MaybeXS provides over JSON:XS -- there were no code changes required to get the benefits of JSON:XS over the default JSON:PP in my testing, just installing the RPM package automatically gives the users the benefits.

**Comment by ndokos** [comment]
I built RPMs for RHEL{7,8} and Fedora2{8,9} in the COPR repo. Please try them out and let me know of any problems. They should appear as

     perl-JSON-XS.x86_64                           1:3.04-1                          copr-pbench

The process is straightforward so I don't think it's going to be a problem in the future: I doubt we are going to have the kind of incompatibilities that we get with fio/uperf/sysstat etc.

I have not done any of the changes necessary to consume this (pbench-agent dependency or changes to the perl scripts to require it instead of perl-JSON). If we decide to go this way, I'll do those next.

I can add EPEL to the RHEL7 repos in the ansible playbook (not sure EPEL for RHEL8 exists yet though - I'll check).

**Comment by ekuric** [comment]
Any chance to get this included in pbench as postprocessing without this workaround https://github.com/distributed-system-analysis/pbench/issues/1016#issuecomment-453121542 takes long to finish - ie. extending testing duration extensively. Patching `/opt/pbench-agent/bench-scripts/postprocess/process-iteration-samples` is workaround but then it has to be done always .

**Comment by portante** [comment]
We keep bumping this effort, but should really fix this for 0.67.

@ndokos, is this something you can pursue?

**Comment by ndokos** [comment]
Yes, we'll get it in to 0.67.

**Comment by k-rister** [comment]
@ndokos Can you brain dump the current status of this (or at least acknowledge if I am correct below)?

From my understanding and by my original request, we are trying to use JSON::XS to speed up JSON processing in Perl.  This module (JSON::XS) requires no code changes and is automatically preferred over JSON::PP if it is installed.  Unfortunately, JSON::XS is only available in EPEL which we are trying to avoid having a dependency on so we are attempting to build it in COPR and have it installed as a dependency of pbench.  In the meantime, any pbench user could get the benefits of JSON::XS by manually installing it from EPEL and it should automatigcally work for them.

**Comment by portante** [comment]
This seems to be solved by packaging the RPM with perl-JSON-XS as a depdency, not via the code.

Please re-open if that folks still see problems.
