### ISSUE TITLE
Bug and cleanups in activate-create-crontab

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#902]
Unquoted variable in condiitional.

Generated crontab has env settings mixed in with rules.

Unit test does not check generated crontab.

**Comment by portante** [comment]
Looks like #946 will address all of these concerns.  @tenstormavi, please consider this issue when reviewing #946.

**Comment by ndokos** [comment]
PR #946 has addressed all aspects of this issue. Closing.
