### ISSUE TITLE
Manual steps when installing a dashboard RPM

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#903]
There are a couple of manual steps that are required after installing the dashboard RPM. We should get rid of them.

The steps are:

    sed -i 's;publicPath: \'/dist/\',;publicPath: \'/dashboard/dist/\';' webpack.config.js
    node run build

**Comment by gurbirkalsi** [comment]
Closing this issue as this deployment process is now outdated with the new dashboard architecture that has been merged under PR #951.
