### ISSUE TITLE
Hardcoded URLs in the dashboard

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#904]
There are a few hardcoded URLs in dashboard code. They should be replaced with values obtained from a config file that can be supplied separately from the dashboard code itself.

**Comment by gurbirkalsi** [comment]
@ndokos Are there any contraints as to where the config file can exist within the repo?

**Comment by ndokos** [comment]
@gurbirkalsi: I don't think so. The main req is that when we install the dashboard, we can plop the config file for that particular installation down somewhere where the dashboard code can find it.

**Comment by portante** [comment]
Fixed by #827.
