### ISSUE TITLE
What should be the Archive directory structure after inotify implementation.

### ISSUE THREAD

**Issue by tenstormavi** [distributed-system-analysis/pbench#918]
Since Inotify (running server scripts from systemd) is completely new implementation from what we have right now (cron based server scripts running), we decided to put a new versioning directory under archive called fs-version-002 along with the old one i.e fs-version-001. 

Why we did that because of fs-version-002, which has a completely new directory structure of the results tarballs. It will have trie structure, based on the md5sum of the results tarballs. Along with that, there will be some other directories also like controller names and inotify watch state directories.

Now the main question is should we really require the versioning directories or we can get rid of that. I think we can eliminate both fs-version-001 and fs-version-002 and put the results under archive itself. It will be easy with the new implementation because that is still in the development phase. 

But it could create some problems with the old implementation since the old agents will be expecting the fs-version-001 directory under archive. But since we moved to our new storage node from the old one for our results, it doesn't have the unpacked results right now. I think we can leverage the situation and can process all the old results with the new implementation. And for old agents, we have to tweak the server scripts to resolve any backward compatibility problems.

Thoughts?
@ndokos @portante @chaitanyaenr

**Comment by portante** [comment]
We are not going to pursue the use of inotify because we'll be moving to an S3 object-store based implementation.
