### ISSUE TITLE
show jenkins job example

### ISSUE THREAD

**Issue by ibenrodriguez** [distributed-system-analysis/pbench#92]
how to setup and run pbench
how to push results to server after job completion

**Comment by psuriset** [comment]
pbench works well with jenkins like any other tool. 

Add required tools be registered while test in progress and also add tests with inputs in jenkins shell 

I use pbench with jenkins through out the day.  It comes very very handy to capture all required logs, and run performance benchmarks.  

Good place to start with. 
http://distributed-system-analysis.github.io/pbench/pbench-agent.html

**Comment by ndokos** [comment]
The doc that psuriset pointed to is the internal doc with sanitized names, so 
most (all?) the links are broken. Internally, we build RPMs for the agent, but the server side is completely manual atm: both the documentation and the installation/setup are works-in-progress.

**Comment by mdshuai** [comment]
@ndokos How install server by manual? Could you show me some detail step? thanks.

**Comment by psuriset** [comment]
@mdshuai https://copr.fedorainfracloud.org/coprs/ndokos/pbench/

**Comment by psuriset** [comment]
@ibenrodriguez ^

**Comment by ndokos** [comment]
There are updated installation instructions for pbench-agent, pbench-server and pbench-web-server in the README. Please check them and let me know of any problems.

**Comment by ashishkamra** [comment]
Happy to take any additional documentation PRs to make this easier
