### ISSUE TITLE
fio histogram logs can have duplicate timestamps

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#925]
this causes fio-histo-log-pctiles to break.  I am trying to get a change upstream with [this PR](https://github.com/axboe/fio/pull/682) to work around this but we need to fix fio to not do it in the first place.

**Comment by portante** [comment]
@bengland2 any updates on the status of this issue?

**Comment by bengland2** [comment]
sorry forgot to update, it's fixed upstream and I think it's in the version of fio-log-histo-pctiles.py checked into pbench.
