### ISSUE TITLE
Consider replacing pbench-*-activate-* with ansible roles and playbooks

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#936]
It seems like the various `pbench-*-activate-*` scripts could be replaced with ansible roles, and a series of playbooks composing those roles for the use cases we have.

**Comment by portante** [comment]
PR #1242 addresses work on the agent side for Ansible playbooks, and the merge PR #1199 already handles the server side Ansible playbooks.

**Comment by portante** [comment]
@ndokos, can you confirm we are done with this work?

**Comment by ndokos** [comment]
Fixed by #1199 with the sole exception of the pbench-server-activate-create-crontab role which still uses the corresponding script.
