### ISSUE TITLE
pbench-server-prep-shim-001 should consider all tar balls in the reception area

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#954]
We have found tar balls in the `fs-version-001` reception area in controller directories that don't have a `TODO` sub-directory.  This might indicate some kind of problem with the client that failed to create that TODO directory as expected.

We need to consider how to handle these orphaned tar balls properly.

**Comment by riya-17** [comment]
I think this is an invalid issue

**Comment by portante** [comment]
Addressed by #1302.
