### ISSUE TITLE
Fix pbench-index/index-pbench to remove unpacked tar ball hierarchy after it finishes indexing

### ISSUE THREAD

**Issue by portante** [distributed-system-analysis/pbench#979]
It appears that `pbench-index` or `index-pbench` is unpacking all the tar balls it has to work with but not cleaning up the unpacked directory as it goes.  This leads to an explosion of disk usage that is unnecessary, and with large tar balls can be problematic.

**Comment by ndokos** [comment]
That happens (or *should* happen) through the TMPDIR env variable: index-pbench unpacks the tarball in there to avoid keeping it all in memory IIRC. But pbench-index *should* be cleaning that up through a trap.

**Comment by portante** [comment]
Doesn't that `trap` execute when all the tar balls have been processed?  So if there are 100 tar balls to be indexed, won't all 100 get unpacked before they are all cleaned up by the 1 `trap` at the end?

**Comment by ndokos** [comment]
Yes, that's right: we'll have to get `index-pbench` to delete the unpacked tarball at the end.

**Comment by portante** [comment]
This will be addressed by #1073.

**Comment by portante** [comment]
We also need to ensure that extracted read-only files don't prevent removal of extracted tar ball hierarchy.

**Comment by portante** [comment]
Fixed as of #1091.
