### ISSUE TITLE
Number of open files should be bumped up

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#98]
In some cases, a user can run against the open file limit (the soft limit seems to be 1024, the hard limit is 4096 on my F21 box).

A root user can bump it up though, so we might want to add that to pbench-base.sh:

ulimit -n 1048576

N.B. "unlimited" or any number > 2^20 does not seem to work on F21, but YMMV.

**Comment by ashishkamra** [comment]
Closing. Re-open if seen again.
