### ISSUE TITLE
Fix index not found 404 error for empty elasticsearch indices

### ISSUE THREAD

**Issue by gurbirkalsi** [distributed-system-analysis/pbench#980]
Users are currently not able to interact with PDash due to a 404 response from the elasticsearch instance for empty indices. The plan is to resolve this by decrementing the selected user month until index containing data is found by querying for the existing available indices.

**Comment by k-rister** [comment]
What will happen with the proposed solution if the user specifies a date range for which there are no indices?

**Comment by gurbirkalsi** [comment]
The user will be redirected to the 404 page and shown a list of available months to select from.

**Comment by gurbirkalsi** [comment]
Closing as this has been resolved and merged with PR #951.

**Comment by ndokos** [comment]
Gurbir Kalsi <notifications@github.com> writes:

> Closing as this has been resolved and merged with PR #951.
>

Has the fixed dashboard been deployed?

-- 
Nick
