### ISSUE TITLE
pbench-register-tool --remote problem

### ISSUE THREAD

**Issue by bengland2** [distributed-system-analysis/pbench#989]
When I run pbench-agent-0.53-2g786732f6.noarch RPM on gprfc080, I get this error trying to remotely register a tool:

```
[root@gprfc080 jobs]# pbench-register-tool --name=sar --remote=gprfc083 default -- --interval=3
[gprfc083]bash: pbench-register-tool: command not found
```
But if I apply this patch:
```
[root@gprfc080 util-scripts]# diff -u pbench-register-too{l.orig,l}
--- pbench-register-tool.orig   2018-11-26 12:33:33.389125388 -0500
+++ pbench-register-tool        2018-11-26 12:33:50.452477883 -0500
@@ -164,7 +164,7 @@
        fi
        # can't really pass an array of tool options over ssh, so here we will actually construct the array within the ssh call, then reference that array
        debug_log "$tool_opt_array_cmd"' pbench-register-tool --name='"$name"' --group='"$group"' $label_opt -- "${tool_opts[@]}" 2>&1'
-       ssh $ssh_opts $remote "$tool_opt_array_cmd"' pbench-register-tool --name='"$name"' --group='"$group" $label_opt' -- "${tool_opts[@]}" 2>&1' | sed -e 's/\(.*\)/'[$remote]'\1/g'
+       ssh $ssh_opts $remote "$tool_opt_array_cmd"' . /etc/profile.d/pbench-agent.sh ; pbench-register-tool --name='"$name"' --group='"$group" $label_opt' -- "${tool_opts[@]}" 2>&1' | sed -e 's/\(.*\)/'[$remote]'\1/g'
        rc=$?
        if [ ! -d "$pbench_run/tools-$group" ]; then
                mkdir -p "$pbench_run/tools-$group"
```
Then it works!  All I did to the ssh command was to insert ". /etc/profile.d/pbench-agent.sh  ; " prior to executing pbench-register-tool on the remote node.
```
[root@gprfc080 util-scripts]# pbench-register-tool --name=sar --remote=gprfc083 default -- --interval=3
[gprfc083]sar tool is now registered in group default
```

**Comment by bengland2** [comment]
Same result for pbench-agent-0.53-98gcb091114.noarch, which was latest pbench-agent in copr-pbench-test repo

**Comment by portante** [comment]
@bengland2, does root on the controller (`gprfc080`) ssh without password into the remote host (`gprfc083`) as root successfully?

**Comment by portante** [comment]
We currently require that for non-interactive logins `/etc/profile.d/pbench-agent.sh` be run when we execute a command remotely via ssh.  That does not appear to be the case here.  We'll need to track down why that is happening.

**Comment by ndokos** [comment]
I guess normally we get a `.bashrc` that sources `/etc/bashrc` which in turn loops over all the files in `/etc/profile.d` and sources them. But @portante noticed that on gprfc083 tjhere is no `/root/.bashrc`.

**Comment by bengland2** [comment]
resolution: make sure .bashrc exists and contains the lines

```
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi
```
