### ISSUE TITLE
sar fails while running pbench with multi vm 

### ISSUE THREAD

**Issue by psuriset** [distributed-system-analysis/pbench#99]
running fio job: /var/lib/pbench-agent/fio_multi-vm-lvm-cache:none-io:native-disk:hdd-fs:lvm-prealloc-iodepth-1-jobs-32-ioeng:sync-profile:latency-perf-full-run-with-stefan-rhel72-patch-without-perf-ag-vcpu-2-run:1_2015-10-29_01:31:51/1-randread-4KiB/sample1/fio.job
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (28146) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11246) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11298) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11237) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11327) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11378) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11266) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11354) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11270) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11377) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11417) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11427) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11340) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11464) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11402) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11376) - No such process
/opt/pbench-agent/tool-scripts/sar: line 168: kill: (11493) - No such process
Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-85]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-85]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-87]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-87]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-98]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-98]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-86]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-86]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-84]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-84]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-95]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-95]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-90]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-90]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-88]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-88]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-91]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-91]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-89]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-89]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-96]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-96]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-94]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-94]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 98.
[virbr0-122-184]Use of uninitialized value $line in scalar chomp at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess line 97.
[virbr0-122-184]Use of uninitialized value $line in pattern match (m//) at /opt/pbench-agent/tool-scripts/postprocess/sar-postprocess

**Comment by ashishkamra** [comment]
Closing. Re-open if seen again.
