### ISSUE TITLE
Warning: "timestamp already exists with this RW type"

### ISSUE THREAD

**Issue by ndokos** [distributed-system-analysis/pbench#991]
[I didn't check if there is an issue already about this. If there is, I'll close this, but I didn't want to forget about it.]

During fio postprocessing, I see warning about "timestamp already exists with this RW type" . I have seen similar messages with uperf. I believe they are harmless but it might be good to figure out the root cause and either get rid of them or silence them:

> ...
running fio job: /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/fio.job
fio job complete
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.1.log timestamp = 2290, value = 2288541000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.2.log timestamp = 2290, value = 2288504000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.2.log timestamp = 10058, value = 136431000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.3.log timestamp = 2290, value = 2288445000, rwtype = 1)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.3.log timestamp = 10058, value = 129606000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.4.log timestamp = 2290, value = 2288508000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_clat.4.log timestamp = 10058, value = 129947095, rwtype = 1)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.1.log timestamp = 2290, value = 2288543000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.2.log timestamp = 2290, value = 2288511000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.2.log timestamp = 10058, value = 136437786, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.3.log timestamp = 2290, value = 2288459000, rwtype = 1)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.3.log timestamp = 10058, value = 136424700, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.4.log timestamp = 2290, value = 2288520000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_lat.4.log timestamp = 10058, value = 136442762, rwtype = 1)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_slat.1.log timestamp = 2290, value = 7000, rwtype = 1)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_slat.2.log timestamp = 2290, value = 17000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_slat.3.log timestamp = 2290, value = 2000, rwtype = 0)
warning: timestamp already exists with this RW type, skipping this sample (file = /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample1/clients/localhost/fio_slat.4.log timestamp = 2290, value = 19000, rwtype = 0)
The following jobfile was created: /var/lib/pbench-agent/fio_rw_2018.11.27T20.34.00/1-rw-4KiB/sample2/fio.job
[global]
....

**Comment by k-rister** [comment]
Pretty sure @atheurer knows what is going on here.

**Comment by ndokos** [comment]
Closing this in favor of #1568 which is tracking the upstream issue we opened.
